-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_tpg_0_0_tpgBackground is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    srcYUV_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    srcYUV_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    srcYUV_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    srcYUV_empty_n : IN STD_LOGIC;
    srcYUV_read : OUT STD_LOGIC;
    height : IN STD_LOGIC_VECTOR (15 downto 0);
    width : IN STD_LOGIC_VECTOR (15 downto 0);
    passthruStartX : IN STD_LOGIC_VECTOR (15 downto 0);
    passthruStartY : IN STD_LOGIC_VECTOR (15 downto 0);
    passthruEndX : IN STD_LOGIC_VECTOR (15 downto 0);
    passthruEndY : IN STD_LOGIC_VECTOR (15 downto 0);
    enableInput : IN STD_LOGIC_VECTOR (7 downto 0);
    bckgndId : IN STD_LOGIC_VECTOR (7 downto 0);
    ZplateHorContStart : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateHorContDelta : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContStart : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContDelta : IN STD_LOGIC_VECTOR (15 downto 0);
    dpDynamicRange : IN STD_LOGIC_VECTOR (7 downto 0);
    dpYUVCoef : IN STD_LOGIC_VECTOR (7 downto 0);
    motionSpeed : IN STD_LOGIC_VECTOR (7 downto 0);
    colorFormat : IN STD_LOGIC_VECTOR (7 downto 0);
    bckgndYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_full_n : IN STD_LOGIC;
    bckgndYUV_write : OUT STD_LOGIC;
    s : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of design_1_v_tpg_0_0_tpgBackground is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_4C : STD_LOGIC_VECTOR (7 downto 0) := "01001100";
    constant ap_const_lv8_95 : STD_LOGIC_VECTOR (7 downto 0) := "10010101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv8_6B : STD_LOGIC_VECTOR (7 downto 0) := "01101011";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv14_F : STD_LOGIC_VECTOR (13 downto 0) := "00000000001111";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv14_7 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000111";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv17_1FFFF : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal rampStart : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal rampVal_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal rampVal : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal hBarSel : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal hdata : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_3 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal rampVal_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_1 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal hBarSel_1 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal cmp8_fu_696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp8_reg_1397 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp2_i381_fu_702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp2_i381_reg_1447 : STD_LOGIC_VECTOR (0 downto 0);
    signal outpix_val_V_fu_708_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_val_V_reg_1452 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_val_V_1_fu_716_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal outpix_val_V_1_reg_1457 : STD_LOGIC_VECTOR (0 downto 0);
    signal outpix_val_V_2_fu_722_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_val_V_2_reg_1462 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln507_fu_730_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln507_reg_1467 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln507_1_cast_cast_fu_738_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln507_1_cast_cast_reg_1472 : STD_LOGIC_VECTOR (2 downto 0);
    signal outpix_val_V_3_fu_746_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_val_V_3_reg_1477 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_val_V_fu_754_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_val_V_reg_1482 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_val_V_14_fu_762_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_val_V_14_reg_1487 : STD_LOGIC_VECTOR (7 downto 0);
    signal barWidthMinSamples_fu_794_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal barWidthMinSamples_reg_1492 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_fu_824_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_1497 : STD_LOGIC_VECTOR (0 downto 0);
    signal barWidth_reg_1502 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_i_i_i_fu_860_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_i_i_i_reg_1508 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub40_i_fu_866_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub40_i_reg_1513 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1404_fu_872_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1404_reg_1518 : STD_LOGIC_VECTOR (16 downto 0);
    signal cmp59_i_fu_878_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp59_i_reg_1523 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp126_i_fu_884_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp126_i_reg_1528 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp141_i_fu_890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp141_i_reg_1533 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampStart_load_reg_1538 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln214_fu_972_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln214_reg_1545 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln_fu_980_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_reg_1550 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1217_fu_988_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1217_reg_1555 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_3_reg_1560 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln518_fu_1062_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln518_reg_1568 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_val_V_6_load_reg_1576 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln518_fu_1066_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal outpix_val_V_7_load_reg_1581 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_val_V_8_load_reg_1586 : STD_LOGIC_VECTOR (7 downto 0);
    signal ult_fu_1086_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ult_reg_1591 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln691_fu_1091_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln691_reg_1596 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1404_1_fu_1100_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1404_1_reg_1601 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev357_fu_1148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev357_reg_1606 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal cmp12_i_fu_1154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp12_i_reg_1611 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln691_fu_1169_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln691_reg_1616 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1404_fu_1175_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1404_reg_1621 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1488_fu_1181_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1488_reg_1626 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln1592_fu_1198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1592_reg_1631 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1592_1_fu_1211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1592_1_reg_1636 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1592_2_fu_1218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1592_2_reg_1641 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_done : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_idle : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_ready : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_srcYUV_read : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_bckgndYUV_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_bckgndYUV_write : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_4_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_4_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_3_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_5_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_5_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_11_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_11_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_10_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_10_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_9_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_9_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_2_0_0_0133363_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_2_0_0_0133363_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_1_0_0_0131361_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_1_0_0_0131361_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_0_0_0_0129359_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_0_0_0_0129359_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_2_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_1_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_1_ap_vld : STD_LOGIC;
    signal ap_phi_mux_rampVal_3_flag_0_phi_fu_464_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_3_flag_0_reg_460 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_phi_mux_hdata_flag_0_phi_fu_476_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal hdata_flag_0_reg_472 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_rampVal_2_flag_0_phi_fu_488_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_2_flag_0_reg_484 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal rampVal_3_new_0_fu_348 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_3_loc_0_fu_344 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_loc_0_fu_340 : STD_LOGIC_VECTOR (15 downto 0);
    signal hBarSel_4_loc_0_fu_336 : STD_LOGIC_VECTOR (7 downto 0);
    signal zonePlateVAddr_loc_0_fu_332 : STD_LOGIC_VECTOR (15 downto 0);
    signal vBarSel_loc_0_fu_328 : STD_LOGIC_VECTOR (7 downto 0);
    signal hBarSel_loc_0_fu_324 : STD_LOGIC_VECTOR (7 downto 0);
    signal hdata_new_0_fu_320 : STD_LOGIC_VECTOR (15 downto 0);
    signal hdata_loc_0_fu_316 : STD_LOGIC_VECTOR (15 downto 0);
    signal vBarSel_2_loc_0_fu_312 : STD_LOGIC_VECTOR (7 downto 0);
    signal hBarSel_3_loc_0_fu_308 : STD_LOGIC_VECTOR (7 downto 0);
    signal rampVal_2_new_0_fu_304 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_2_loc_0_fu_300 : STD_LOGIC_VECTOR (15 downto 0);
    signal vBarSel_3_loc_0_fu_296 : STD_LOGIC_VECTOR (7 downto 0);
    signal hBarSel_5_loc_0_fu_292 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_val_V_8_fu_288 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_val_V_7_fu_284 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_val_V_6_fu_280 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_2_0_0_0133364_lcssa373_fu_272 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_1_0_0_0131362_lcssa370_fu_268 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0129360_lcssa367_fu_264 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln705_fu_1110_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_fu_276 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln518_fu_1071_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln518_fu_968_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1730_fu_960_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1610_fu_948_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1493_fu_932_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1367_fu_924_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1212_fu_908_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_fu_774_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add2_i_fu_778_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_cast_fu_784_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_81_fu_804_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_23_fu_814_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_i_fu_830_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add5_i_fu_808_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_fu_846_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal barHeight_cast_cast_fu_856_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal loopWidth_cast15_fu_770_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal loopHeight_cast16_fu_800_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln1404_fu_1096_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal Sel_fu_1160_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln1592_fu_1186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1592_1_fu_1192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1592_2_fu_1205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        srcYUV_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        srcYUV_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
        srcYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        srcYUV_empty_n : IN STD_LOGIC;
        srcYUV_read : OUT STD_LOGIC;
        bckgndYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_full_n : IN STD_LOGIC;
        bckgndYUV_write : OUT STD_LOGIC;
        rampVal_3_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        outpix_val_V_8 : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_val_V_7 : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_val_V_6 : IN STD_LOGIC_VECTOR (7 downto 0);
        loopWidth : IN STD_LOGIC_VECTOR (15 downto 0);
        pix_val_V_17 : IN STD_LOGIC_VECTOR (7 downto 0);
        pix_val_V_16 : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_val_V_3 : IN STD_LOGIC_VECTOR (7 downto 0);
        select_ln507 : IN STD_LOGIC_VECTOR (4 downto 0);
        sext_ln507 : IN STD_LOGIC_VECTOR (0 downto 0);
        outpix_val_V_18 : IN STD_LOGIC_VECTOR (7 downto 0);
        select_ln507_1_cast_cast : IN STD_LOGIC_VECTOR (2 downto 0);
        outpix_val_V_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_val_V : IN STD_LOGIC_VECTOR (7 downto 0);
        rampStart_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        cmp8 : IN STD_LOGIC_VECTOR (0 downto 0);
        bckgndId_load : IN STD_LOGIC_VECTOR (7 downto 0);
        Zplate_Hor_Control_Start : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp2_i381 : IN STD_LOGIC_VECTOR (0 downto 0);
        zext_ln1032 : IN STD_LOGIC_VECTOR (7 downto 0);
        y : IN STD_LOGIC_VECTOR (15 downto 0);
        colorFormatLocal : IN STD_LOGIC_VECTOR (7 downto 0);
        cmp141_i : IN STD_LOGIC_VECTOR (0 downto 0);
        icmp_ln1217 : IN STD_LOGIC_VECTOR (0 downto 0);
        barWidth_cast : IN STD_LOGIC_VECTOR (10 downto 0);
        barWidth : IN STD_LOGIC_VECTOR (10 downto 0);
        shl_ln : IN STD_LOGIC_VECTOR (15 downto 0);
        Zplate_Hor_Control_Delta : IN STD_LOGIC_VECTOR (15 downto 0);
        Zplate_Ver_Control_Start : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp12_i : IN STD_LOGIC_VECTOR (0 downto 0);
        Zplate_Ver_Control_Delta : IN STD_LOGIC_VECTOR (15 downto 0);
        sub_i_i_i : IN STD_LOGIC_VECTOR (10 downto 0);
        barWidthMinSamples : IN STD_LOGIC_VECTOR (9 downto 0);
        icmp_ln1404_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        icmp_ln1404 : IN STD_LOGIC_VECTOR (0 downto 0);
        sub40_i : IN STD_LOGIC_VECTOR (16 downto 0);
        add_ln1488 : IN STD_LOGIC_VECTOR (7 downto 0);
        cmp35_i586 : IN STD_LOGIC_VECTOR (0 downto 0);
        or_ln1592 : IN STD_LOGIC_VECTOR (0 downto 0);
        or_ln1592_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        or_ln1592_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp59_i : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp126_i : IN STD_LOGIC_VECTOR (0 downto 0);
        passthruStartX_load : IN STD_LOGIC_VECTOR (15 downto 0);
        passthruEndX_load : IN STD_LOGIC_VECTOR (15 downto 0);
        icmp_ln691 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp68_not : IN STD_LOGIC_VECTOR (0 downto 0);
        rampVal_3_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_3_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_4_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        zonePlateVAddr_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hdata_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_1_out_ap_vld : OUT STD_LOGIC;
        hdata_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_new_1_out_ap_vld : OUT STD_LOGIC;
        hdata_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_2_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_3_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_2_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_3_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_5_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_5_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_5_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        outpix_val_V_11_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        outpix_val_V_11_out_ap_vld : OUT STD_LOGIC;
        outpix_val_V_10_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        outpix_val_V_10_out_ap_vld : OUT STD_LOGIC;
        outpix_val_V_9_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        outpix_val_V_9_out_ap_vld : OUT STD_LOGIC;
        p_0_2_0_0_0133363_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_2_0_0_0133363_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_2_0_0_0133363_out_o_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_0131361_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_1_0_0_0131361_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_1_0_0_0131361_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0129359_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0129359_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0129359_out_o_ap_vld : OUT STD_LOGIC;
        rampVal : OUT STD_LOGIC_VECTOR (7 downto 0);
        rampVal_ap_vld : OUT STD_LOGIC;
        hBarSel_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_2_ap_vld : OUT STD_LOGIC;
        s : IN STD_LOGIC_VECTOR (31 downto 0);
        zonePlateVAddr : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_ap_vld : OUT STD_LOGIC;
        hBarSel : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_ap_vld : OUT STD_LOGIC;
        vBarSel : OUT STD_LOGIC_VECTOR (2 downto 0);
        vBarSel_ap_vld : OUT STD_LOGIC;
        hBarSel_3 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_3_ap_vld : OUT STD_LOGIC;
        vBarSel_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_ap_vld : OUT STD_LOGIC;
        hBarSel_1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_1_ap_vld : OUT STD_LOGIC;
        vBarSel_1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        vBarSel_1_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496 : component design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start,
        ap_done => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_done,
        ap_idle => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_idle,
        ap_ready => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_ready,
        srcYUV_dout => srcYUV_dout,
        srcYUV_num_data_valid => srcYUV_num_data_valid,
        srcYUV_fifo_cap => ap_const_lv5_0,
        srcYUV_empty_n => srcYUV_empty_n,
        srcYUV_read => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_srcYUV_read,
        bckgndYUV_din => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_bckgndYUV_din,
        bckgndYUV_num_data_valid => ap_const_lv5_0,
        bckgndYUV_fifo_cap => ap_const_lv5_0,
        bckgndYUV_full_n => bckgndYUV_full_n,
        bckgndYUV_write => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_bckgndYUV_write,
        rampVal_3_flag_0 => rampVal_3_flag_0_reg_460,
        hdata_flag_0 => hdata_flag_0_reg_472,
        rampVal_2_flag_0 => rampVal_2_flag_0_reg_484,
        outpix_val_V_8 => outpix_val_V_8_load_reg_1586,
        outpix_val_V_7 => outpix_val_V_7_load_reg_1581,
        outpix_val_V_6 => outpix_val_V_6_load_reg_1576,
        loopWidth => width,
        pix_val_V_17 => pix_val_V_14_reg_1487,
        pix_val_V_16 => pix_val_V_reg_1482,
        outpix_val_V_3 => outpix_val_V_3_reg_1477,
        select_ln507 => select_ln507_reg_1467,
        sext_ln507 => outpix_val_V_1_reg_1457,
        outpix_val_V_18 => select_ln214_reg_1545,
        select_ln507_1_cast_cast => select_ln507_1_cast_cast_reg_1472,
        outpix_val_V_2 => outpix_val_V_2_reg_1462,
        outpix_val_V => outpix_val_V_reg_1452,
        rampStart_1 => rampStart_load_reg_1538,
        cmp8 => cmp8_reg_1397,
        bckgndId_load => bckgndId,
        Zplate_Hor_Control_Start => ZplateHorContStart,
        cmp2_i381 => cmp2_i381_reg_1447,
        zext_ln1032 => rampStart_load_reg_1538,
        y => y_3_reg_1560,
        colorFormatLocal => colorFormat,
        cmp141_i => cmp141_i_reg_1533,
        icmp_ln1217 => icmp_ln1217_reg_1555,
        barWidth_cast => barWidth_reg_1502,
        barWidth => barWidth_reg_1502,
        shl_ln => shl_ln_reg_1550,
        Zplate_Hor_Control_Delta => ZplateHorContDelta,
        Zplate_Ver_Control_Start => ZplateVerContStart,
        cmp12_i => cmp12_i_reg_1611,
        Zplate_Ver_Control_Delta => ZplateVerContDelta,
        sub_i_i_i => sub_i_i_i_reg_1508,
        barWidthMinSamples => barWidthMinSamples_reg_1492,
        icmp_ln1404_1 => icmp_ln1404_1_reg_1601,
        icmp_ln1404 => icmp_ln1404_reg_1621,
        sub40_i => sub40_i_reg_1513,
        add_ln1488 => add_ln1488_reg_1626,
        cmp35_i586 => icmp_reg_1497,
        or_ln1592 => or_ln1592_reg_1631,
        or_ln1592_1 => or_ln1592_1_reg_1636,
        or_ln1592_2 => or_ln1592_2_reg_1641,
        cmp59_i => cmp59_i_reg_1523,
        cmp126_i => cmp126_i_reg_1528,
        passthruStartX_load => passthruStartX,
        passthruEndX_load => passthruEndX,
        icmp_ln691 => xor_ln691_reg_1616,
        cmp68_not => rev357_reg_1606,
        rampVal_3_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_flag_1_out,
        rampVal_3_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_flag_1_out_ap_vld,
        rampVal_3_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_new_1_out,
        rampVal_3_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_new_1_out_ap_vld,
        rampVal_3_loc_1_out_i => rampVal_3_loc_0_fu_344,
        rampVal_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_loc_1_out_o,
        rampVal_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_loc_1_out_o_ap_vld,
        rampVal_loc_1_out_i => rampVal_loc_0_fu_340,
        rampVal_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_loc_1_out_o,
        rampVal_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_loc_1_out_o_ap_vld,
        hBarSel_4_loc_1_out_i => hBarSel_4_loc_0_fu_336,
        hBarSel_4_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_4_loc_1_out_o,
        hBarSel_4_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_4_loc_1_out_o_ap_vld,
        zonePlateVAddr_loc_1_out_i => zonePlateVAddr_loc_0_fu_332,
        zonePlateVAddr_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_loc_1_out_o,
        zonePlateVAddr_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_loc_1_out_o_ap_vld,
        vBarSel_loc_1_out_i => vBarSel_loc_0_fu_328,
        vBarSel_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_loc_1_out_o,
        vBarSel_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_loc_1_out_o_ap_vld,
        hBarSel_loc_1_out_i => hBarSel_loc_0_fu_324,
        hBarSel_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_loc_1_out_o,
        hBarSel_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_loc_1_out_o_ap_vld,
        hdata_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_flag_1_out,
        hdata_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_flag_1_out_ap_vld,
        hdata_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_new_1_out,
        hdata_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_new_1_out_ap_vld,
        hdata_loc_1_out_i => hdata_loc_0_fu_316,
        hdata_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_loc_1_out_o,
        hdata_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_loc_1_out_o_ap_vld,
        vBarSel_2_loc_1_out_i => vBarSel_2_loc_0_fu_312,
        vBarSel_2_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_loc_1_out_o,
        vBarSel_2_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_loc_1_out_o_ap_vld,
        hBarSel_3_loc_1_out_i => hBarSel_3_loc_0_fu_308,
        hBarSel_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_loc_1_out_o,
        hBarSel_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_loc_1_out_o_ap_vld,
        rampVal_2_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_flag_1_out,
        rampVal_2_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_flag_1_out_ap_vld,
        rampVal_2_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_new_1_out,
        rampVal_2_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_new_1_out_ap_vld,
        rampVal_2_loc_1_out_i => rampVal_2_loc_0_fu_300,
        rampVal_2_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_loc_1_out_o,
        rampVal_2_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_loc_1_out_o_ap_vld,
        vBarSel_3_loc_1_out_i => vBarSel_3_loc_0_fu_296,
        vBarSel_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_3_loc_1_out_o,
        vBarSel_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_3_loc_1_out_o_ap_vld,
        hBarSel_5_loc_1_out_i => hBarSel_5_loc_0_fu_292,
        hBarSel_5_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_5_loc_1_out_o,
        hBarSel_5_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_5_loc_1_out_o_ap_vld,
        outpix_val_V_11_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_11_out,
        outpix_val_V_11_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_11_out_ap_vld,
        outpix_val_V_10_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_10_out,
        outpix_val_V_10_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_10_out_ap_vld,
        outpix_val_V_9_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_9_out,
        outpix_val_V_9_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_9_out_ap_vld,
        p_0_2_0_0_0133363_out_i => p_0_2_0_0_0133364_lcssa373_fu_272,
        p_0_2_0_0_0133363_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_2_0_0_0133363_out_o,
        p_0_2_0_0_0133363_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_2_0_0_0133363_out_o_ap_vld,
        p_0_1_0_0_0131361_out_i => p_0_1_0_0_0131362_lcssa370_fu_268,
        p_0_1_0_0_0131361_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_1_0_0_0131361_out_o,
        p_0_1_0_0_0131361_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_1_0_0_0131361_out_o_ap_vld,
        p_0_0_0_0_0129359_out_i => p_0_0_0_0_0129360_lcssa367_fu_264,
        p_0_0_0_0_0129359_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_0_0_0_0129359_out_o,
        p_0_0_0_0_0129359_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_0_0_0_0129359_out_o_ap_vld,
        rampVal => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal,
        rampVal_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_ap_vld,
        hBarSel_2 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_2,
        hBarSel_2_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_2_ap_vld,
        s => s,
        zonePlateVAddr => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr,
        zonePlateVAddr_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_ap_vld,
        hBarSel => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel,
        hBarSel_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_ap_vld,
        vBarSel => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel,
        vBarSel_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_ap_vld,
        hBarSel_3 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3,
        hBarSel_3_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_ap_vld,
        vBarSel_2 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2,
        vBarSel_2_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_ap_vld,
        hBarSel_1 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_1,
        hBarSel_1_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_1_ap_vld,
        vBarSel_1 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_1,
        vBarSel_1_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_1_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_1066_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_ready = ap_const_logic_1)) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    hBarSel_3_loc_0_fu_308_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_3_loc_0_fu_308 <= zext_ln1610_fu_948_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_3_loc_0_fu_308 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_4_loc_0_fu_336_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_4_loc_0_fu_336 <= hBarSel_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_4_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_4_loc_0_fu_336 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_4_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_5_loc_0_fu_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_5_loc_0_fu_292 <= zext_ln518_fu_968_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_5_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_5_loc_0_fu_292 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_5_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_loc_0_fu_324_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_loc_0_fu_324 <= zext_ln1493_fu_932_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_loc_0_fu_324 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_loc_1_out_o;
            end if; 
        end if;
    end process;

    hdata_flag_0_reg_472_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                hdata_flag_0_reg_472 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_flag_1_out;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hdata_flag_0_reg_472 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    hdata_loc_0_fu_316_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hdata_loc_0_fu_316 <= hdata;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hdata_loc_0_fu_316 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_2_flag_0_reg_484_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                rampVal_2_flag_0_reg_484 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_flag_1_out;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_2_flag_0_reg_484 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_2_loc_0_fu_300_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_2_loc_0_fu_300 <= rampVal_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                rampVal_2_loc_0_fu_300 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_3_flag_0_reg_460_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                rampVal_3_flag_0_reg_460 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_flag_1_out;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_3_flag_0_reg_460 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_3_loc_0_fu_344_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_3_loc_0_fu_344 <= rampVal_1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                rampVal_3_loc_0_fu_344 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_loc_0_fu_340_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_loc_0_fu_340 <= zext_ln1212_fu_908_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                rampVal_loc_0_fu_340 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_2_loc_0_fu_312_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vBarSel_2_loc_0_fu_312 <= vBarSel_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vBarSel_2_loc_0_fu_312 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_3_loc_0_fu_296_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vBarSel_3_loc_0_fu_296 <= zext_ln1730_fu_960_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vBarSel_3_loc_0_fu_296 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_loc_0_fu_328_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vBarSel_loc_0_fu_328 <= zext_ln1367_fu_924_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vBarSel_loc_0_fu_328 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_loc_1_out_o;
            end if; 
        end if;
    end process;

    y_fu_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_276 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_1066_p2 = ap_const_lv1_0))) then 
                y_fu_276 <= add_ln518_fu_1071_p2;
            end if; 
        end if;
    end process;

    zonePlateVAddr_loc_0_fu_332_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                zonePlateVAddr_loc_0_fu_332 <= zonePlateVAddr;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                zonePlateVAddr_loc_0_fu_332 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_loc_1_out_o;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                add_ln1404_reg_1518 <= add_ln1404_fu_872_p2;
                barWidthMinSamples_reg_1492 <= barWidthMinSamples_fu_794_p2;
                barWidth_reg_1502 <= add_i_fu_830_p2(13 downto 3);
                cmp126_i_reg_1528 <= cmp126_i_fu_884_p2;
                cmp141_i_reg_1533 <= cmp141_i_fu_890_p2;
                cmp2_i381_reg_1447 <= cmp2_i381_fu_702_p2;
                cmp59_i_reg_1523 <= cmp59_i_fu_878_p2;
                cmp8_reg_1397 <= cmp8_fu_696_p2;
                icmp_ln1217_reg_1555 <= icmp_ln1217_fu_988_p2;
                icmp_reg_1497 <= icmp_fu_824_p2;
                outpix_val_V_1_reg_1457 <= outpix_val_V_1_fu_716_p2;
                    outpix_val_V_2_reg_1462(0) <= outpix_val_V_2_fu_722_p3(0);    outpix_val_V_2_reg_1462(2) <= outpix_val_V_2_fu_722_p3(2);    outpix_val_V_2_reg_1462(4) <= outpix_val_V_2_fu_722_p3(4);    outpix_val_V_2_reg_1462(7) <= outpix_val_V_2_fu_722_p3(7);
                    outpix_val_V_3_reg_1477(2) <= outpix_val_V_3_fu_746_p3(2);    outpix_val_V_3_reg_1477(4) <= outpix_val_V_3_fu_746_p3(4);    outpix_val_V_3_reg_1477(7) <= outpix_val_V_3_fu_746_p3(7);
                    outpix_val_V_reg_1452(1 downto 0) <= outpix_val_V_fu_708_p3(1 downto 0);    outpix_val_V_reg_1452(5 downto 4) <= outpix_val_V_fu_708_p3(5 downto 4);    outpix_val_V_reg_1452(7) <= outpix_val_V_fu_708_p3(7);
                    pix_val_V_14_reg_1487(6 downto 0) <= pix_val_V_14_fu_762_p3(6 downto 0);
                    pix_val_V_reg_1482(7) <= pix_val_V_fu_754_p3(7);
                rampStart_load_reg_1538 <= rampStart;
                select_ln214_reg_1545 <= select_ln214_fu_972_p3;
                    select_ln507_1_cast_cast_reg_1472(0) <= select_ln507_1_cast_cast_fu_738_p3(0);    select_ln507_1_cast_cast_reg_1472(2) <= select_ln507_1_cast_cast_fu_738_p3(2);
                    select_ln507_reg_1467(0) <= select_ln507_fu_730_p3(0);    select_ln507_reg_1467(2) <= select_ln507_fu_730_p3(2);    select_ln507_reg_1467(4) <= select_ln507_fu_730_p3(4);
                    shl_ln_reg_1550(15 downto 8) <= shl_ln_fu_980_p3(15 downto 8);
                sub40_i_reg_1513 <= sub40_i_fu_866_p2;
                sub_i_i_i_reg_1508 <= sub_i_i_i_fu_860_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln1488_reg_1626 <= add_ln1488_fu_1181_p2;
                cmp12_i_reg_1611 <= cmp12_i_fu_1154_p2;
                icmp_ln1404_reg_1621 <= icmp_ln1404_fu_1175_p2;
                or_ln1592_1_reg_1636 <= or_ln1592_1_fu_1211_p2;
                or_ln1592_2_reg_1641 <= or_ln1592_2_fu_1218_p2;
                or_ln1592_reg_1631 <= or_ln1592_fu_1198_p2;
                rev357_reg_1606 <= rev357_fu_1148_p2;
                xor_ln691_reg_1616 <= xor_ln691_fu_1169_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_3 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_hdata_flag_0_phi_fu_476_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_1066_p2 = ap_const_lv1_1))) then
                hdata <= hdata_new_0_fu_320;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hdata_new_0_fu_320 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_1066_p2 = ap_const_lv1_0))) then
                icmp_ln1404_1_reg_1601 <= icmp_ln1404_1_fu_1100_p2;
                icmp_ln691_reg_1596 <= icmp_ln691_fu_1091_p2;
                outpix_val_V_6_load_reg_1576 <= outpix_val_V_6_fu_280;
                outpix_val_V_7_load_reg_1581 <= outpix_val_V_7_fu_284;
                outpix_val_V_8_load_reg_1586 <= outpix_val_V_8_fu_288;
                ult_reg_1591 <= ult_fu_1086_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_9_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                outpix_val_V_6_fu_280 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_9_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_10_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                outpix_val_V_7_fu_284 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_10_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_11_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                outpix_val_V_8_fu_288 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_11_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_0_0_0_0129359_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0_0_0129360_lcssa367_fu_264 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_0_0_0_0129359_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_1_0_0_0131361_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_1_0_0_0131362_lcssa370_fu_268 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_1_0_0_0131361_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_2_0_0_0133363_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_2_0_0_0133364_lcssa373_fu_272 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_2_0_0_0133363_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_1066_p2 = ap_const_lv1_1))) then
                rampStart <= add_ln705_fu_1110_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_rampVal_3_flag_0_phi_fu_464_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_1066_p2 = ap_const_lv1_1))) then
                rampVal_1 <= rampVal_3_new_0_fu_348;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_rampVal_2_flag_0_phi_fu_488_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_1066_p2 = ap_const_lv1_1))) then
                rampVal_2 <= rampVal_2_new_0_fu_304;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                rampVal_2_new_0_fu_304 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                rampVal_3_new_0_fu_348 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                trunc_ln518_reg_1568 <= trunc_ln518_fu_1062_p1;
                y_3_reg_1560 <= y_fu_276;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                vBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr;
            end if;
        end if;
    end process;
    outpix_val_V_reg_1452(3 downto 2) <= "11";
    outpix_val_V_reg_1452(6) <= '1';
    outpix_val_V_2_reg_1462(1) <= '0';
    outpix_val_V_2_reg_1462(3 downto 3) <= "0";
    outpix_val_V_2_reg_1462(6 downto 5) <= "00";
    select_ln507_reg_1467(1) <= '0';
    select_ln507_reg_1467(3) <= '0';
    select_ln507_1_cast_cast_reg_1472(1) <= '0';
    outpix_val_V_3_reg_1477(1 downto 0) <= "11";
    outpix_val_V_3_reg_1477(3 downto 3) <= "1";
    outpix_val_V_3_reg_1477(6 downto 5) <= "11";
    pix_val_V_reg_1482(6 downto 0) <= "0000000";
    pix_val_V_14_reg_1487(7) <= '1';
    shl_ln_reg_1550(7 downto 0) <= "00000000";

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln518_fu_1066_p2, grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_1066_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    Sel_fu_1160_p4 <= y_3_reg_1560(7 downto 6);
    add2_i_fu_778_p2 <= std_logic_vector(unsigned(empty_fu_774_p1) + unsigned(ap_const_lv14_F));
    add5_i_fu_808_p2 <= std_logic_vector(unsigned(empty_81_fu_804_p1) + unsigned(ap_const_lv14_F));
    add_i_fu_830_p2 <= std_logic_vector(unsigned(empty_fu_774_p1) + unsigned(ap_const_lv14_7));
    add_ln1404_fu_872_p2 <= std_logic_vector(unsigned(loopHeight_cast16_fu_800_p1) + unsigned(ap_const_lv17_1FFFF));
    add_ln1488_fu_1181_p2 <= std_logic_vector(unsigned(rampStart_load_reg_1538) + unsigned(trunc_ln518_reg_1568));
    add_ln518_fu_1071_p2 <= std_logic_vector(unsigned(y_fu_276) + unsigned(ap_const_lv16_1));
    add_ln705_fu_1110_p2 <= std_logic_vector(unsigned(motionSpeed) + unsigned(rampStart));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_done)
    begin
        if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln518_fu_1066_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_1066_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_mux_hdata_flag_0_phi_fu_476_p4 <= hdata_flag_0_reg_472;
    ap_phi_mux_rampVal_2_flag_0_phi_fu_488_p4 <= rampVal_2_flag_0_reg_484;
    ap_phi_mux_rampVal_3_flag_0_phi_fu_464_p4 <= rampVal_3_flag_0_reg_460;
    ap_ready <= internal_ap_ready;
    barHeight_cast_cast_fu_856_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_846_p4),11));
    barWidthMinSamples_fu_794_p2 <= std_logic_vector(unsigned(p_cast_fu_784_p4) + unsigned(ap_const_lv10_3FF));
    bckgndYUV_din <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_bckgndYUV_din;

    bckgndYUV_write_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_bckgndYUV_write, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bckgndYUV_write <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_bckgndYUV_write;
        else 
            bckgndYUV_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp126_i_fu_884_p2 <= "1" when (dpYUVCoef = ap_const_lv8_0) else "0";
    cmp12_i_fu_1154_p2 <= "0" when (y_3_reg_1560 = ap_const_lv16_0) else "1";
    cmp141_i_fu_890_p2 <= "0" when (colorFormat = ap_const_lv8_1) else "1";
    cmp2_i381_fu_702_p2 <= "1" when (colorFormat = ap_const_lv8_0) else "0";
    cmp59_i_fu_878_p2 <= "1" when (dpDynamicRange = ap_const_lv8_0) else "0";
    cmp8_fu_696_p2 <= "0" when (enableInput = ap_const_lv8_0) else "1";
    empty_81_fu_804_p1 <= height(14 - 1 downto 0);
    empty_fu_774_p1 <= width(14 - 1 downto 0);
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start_reg;
    icmp_fu_824_p2 <= "0" when (tmp_23_fu_814_p4 = ap_const_lv7_0) else "1";
    icmp_ln1217_fu_988_p2 <= "0" when (colorFormat = ap_const_lv8_0) else "1";
    icmp_ln1404_1_fu_1100_p2 <= "1" when (add_ln1404_reg_1518 = zext_ln1404_fu_1096_p1) else "0";
    icmp_ln1404_fu_1175_p2 <= "1" when (y_3_reg_1560 = ap_const_lv16_0) else "0";
    icmp_ln1592_1_fu_1192_p2 <= "1" when (Sel_fu_1160_p4 = ap_const_lv2_2) else "0";
    icmp_ln1592_2_fu_1205_p2 <= "1" when (Sel_fu_1160_p4 = ap_const_lv2_0) else "0";
    icmp_ln1592_fu_1186_p2 <= "1" when (Sel_fu_1160_p4 = ap_const_lv2_1) else "0";
    icmp_ln518_fu_1066_p2 <= "1" when (y_fu_276 = height) else "0";
    icmp_ln691_fu_1091_p2 <= "1" when (unsigned(y_fu_276) < unsigned(passthruStartY)) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln518_fu_1066_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_1066_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    loopHeight_cast16_fu_800_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height),17));
    loopWidth_cast15_fu_770_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width),17));
    or_ln1592_1_fu_1211_p2 <= (icmp_ln1592_2_fu_1205_p2 or icmp_ln1592_1_fu_1192_p2);
    or_ln1592_2_fu_1218_p2 <= (icmp_ln1592_fu_1186_p2 or icmp_ln1592_2_fu_1205_p2);
    or_ln1592_fu_1198_p2 <= (icmp_ln1592_fu_1186_p2 or icmp_ln1592_1_fu_1192_p2);
    outpix_val_V_1_fu_716_p2 <= (cmp2_i381_fu_702_p2 xor ap_const_lv1_1);
    outpix_val_V_2_fu_722_p3 <= 
        ap_const_lv8_0 when (cmp2_i381_fu_702_p2(0) = '1') else 
        ap_const_lv8_95;
    outpix_val_V_3_fu_746_p3 <= 
        ap_const_lv8_FF when (cmp2_i381_fu_702_p2(0) = '1') else 
        ap_const_lv8_6B;
    outpix_val_V_fu_708_p3 <= 
        ap_const_lv8_FF when (cmp2_i381_fu_702_p2(0) = '1') else 
        ap_const_lv8_4C;
    p_cast_fu_784_p4 <= add2_i_fu_778_p2(13 downto 4);
    pix_val_V_14_fu_762_p3 <= 
        ap_const_lv8_FF when (cmp2_i381_fu_702_p2(0) = '1') else 
        ap_const_lv8_80;
    pix_val_V_fu_754_p3 <= 
        ap_const_lv8_0 when (cmp2_i381_fu_702_p2(0) = '1') else 
        ap_const_lv8_80;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    rev357_fu_1148_p2 <= (ult_reg_1591 xor ap_const_lv1_1);
    select_ln214_fu_972_p3 <= 
        rampStart when (cmp2_i381_fu_702_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln507_1_cast_cast_fu_738_p3 <= 
        ap_const_lv3_0 when (cmp2_i381_fu_702_p2(0) = '1') else 
        ap_const_lv3_5;
    select_ln507_fu_730_p3 <= 
        ap_const_lv5_0 when (cmp2_i381_fu_702_p2(0) = '1') else 
        ap_const_lv5_15;
    shl_ln_fu_980_p3 <= (rampStart & ap_const_lv8_0);

    srcYUV_read_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_srcYUV_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            srcYUV_read <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_srcYUV_read;
        else 
            srcYUV_read <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub40_i_fu_866_p2 <= std_logic_vector(unsigned(loopWidth_cast15_fu_770_p1) + unsigned(ap_const_lv17_1FFFF));
    sub_i_i_i_fu_860_p2 <= std_logic_vector(unsigned(barHeight_cast_cast_fu_856_p1) + unsigned(ap_const_lv11_7FF));
    tmp_23_fu_814_p4 <= colorFormat(7 downto 1);
    tmp_fu_846_p4 <= add5_i_fu_808_p2(13 downto 4);
    trunc_ln518_fu_1062_p1 <= y_fu_276(8 - 1 downto 0);
    ult_fu_1086_p2 <= "1" when (unsigned(y_fu_276) < unsigned(passthruEndY)) else "0";
    xor_ln691_fu_1169_p2 <= (icmp_ln691_reg_1596 xor ap_const_lv1_1);
    zext_ln1212_fu_908_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rampVal),16));
    zext_ln1367_fu_924_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vBarSel),8));
    zext_ln1404_fu_1096_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_fu_276),17));
    zext_ln1493_fu_932_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel),8));
    zext_ln1610_fu_948_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_3),8));
    zext_ln1730_fu_960_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vBarSel_1),8));
    zext_ln518_fu_968_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_1),8));
end behav;
