-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_729_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bckgndYUV_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_empty_n : IN STD_LOGIC;
    bckgndYUV_read : OUT STD_LOGIC;
    ovrlayYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_full_n : IN STD_LOGIC;
    ovrlayYUV_write : OUT STD_LOGIC;
    boxHCoord_loc_0 : IN STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_loc_0 : IN STD_LOGIC_VECTOR (15 downto 0);
    loopWidth : IN STD_LOGIC_VECTOR (15 downto 0);
    pixOut_val_V_9 : IN STD_LOGIC_VECTOR (7 downto 0);
    pixOut_val_V : IN STD_LOGIC_VECTOR (7 downto 0);
    pixOut_val_V_7 : IN STD_LOGIC_VECTOR (7 downto 0);
    and4_i : IN STD_LOGIC_VECTOR (0 downto 0);
    and26_i : IN STD_LOGIC_VECTOR (0 downto 0);
    tobool : IN STD_LOGIC_VECTOR (0 downto 0);
    and10_i : IN STD_LOGIC_VECTOR (0 downto 0);
    ovrlayId_load : IN STD_LOGIC_VECTOR (7 downto 0);
    boxSize_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    y : IN STD_LOGIC_VECTOR (15 downto 0);
    zext_ln1869 : IN STD_LOGIC_VECTOR (7 downto 0);
    vMax : IN STD_LOGIC_VECTOR (15 downto 0);
    hMax : IN STD_LOGIC_VECTOR (15 downto 0);
    zext_ln1869_1 : IN STD_LOGIC_VECTOR (8 downto 0);
    cmp101_i : IN STD_LOGIC_VECTOR (0 downto 0);
    boxColorG_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    crossHairX_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    cmp2_i : IN STD_LOGIC_VECTOR (0 downto 0);
    color : IN STD_LOGIC_VECTOR (7 downto 0);
    boxHCoord_loc_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxHCoord_loc_1_out_ap_vld : OUT STD_LOGIC;
    boxVCoord_loc_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_loc_1_out_ap_vld : OUT STD_LOGIC;
    boxHCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxHCoord_ap_vld : OUT STD_LOGIC;
    boxVCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_ap_vld : OUT STD_LOGIC );
end;


architecture behav of design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_729_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv8_F0 : STD_LOGIC_VECTOR (7 downto 0) := "11110000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal icmp_ln729_reg_912 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln729_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal vDir : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal hDir : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal whiYuv_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal whiYuv_2_ce0 : STD_LOGIC;
    signal whiYuv_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ovrlayYUV_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal bckgndYUV_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal color_read_reg_792 : STD_LOGIC_VECTOR (7 downto 0);
    signal crossHairX_1_read_reg_801 : STD_LOGIC_VECTOR (15 downto 0);
    signal boxColorG_1_read_reg_806 : STD_LOGIC_VECTOR (7 downto 0);
    signal cmp101_i_read_reg_811 : STD_LOGIC_VECTOR (0 downto 0);
    signal hMax_read_reg_816 : STD_LOGIC_VECTOR (15 downto 0);
    signal vMax_read_reg_821 : STD_LOGIC_VECTOR (15 downto 0);
    signal boxSize_1_read_reg_833 : STD_LOGIC_VECTOR (15 downto 0);
    signal ovrlayId_load_read_reg_839 : STD_LOGIC_VECTOR (7 downto 0);
    signal and10_i_read_reg_843 : STD_LOGIC_VECTOR (0 downto 0);
    signal tobool_read_reg_848 : STD_LOGIC_VECTOR (0 downto 0);
    signal and26_i_read_reg_855 : STD_LOGIC_VECTOR (0 downto 0);
    signal and4_i_read_reg_860 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixOut_val_V_7_read_reg_865 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_val_V_read_reg_870 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_val_V_9_read_reg_876 : STD_LOGIC_VECTOR (7 downto 0);
    signal loopWidth_read_reg_882 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1869_1_cast_fu_397_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1869_1_cast_reg_887 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1869_cast_fu_401_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1869_cast_reg_893 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_1_reg_901 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln729_fu_429_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln729_reg_907 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1839_fu_449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal hDir_load_load_fu_455_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1844_fu_459_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1849_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal vDir_load_load_fu_481_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1856_fu_485_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1861_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1918_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1918_reg_944 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_empty_76_phi_fu_299_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_76_reg_296 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_empty_75_phi_fu_316_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_75_reg_313 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_phi_ln1930_phi_fu_333_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln1930_fu_575_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter1_phi_ln1930_reg_330 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_mux_pix_val_V_4_phi_fu_343_p12 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_val_V_4_reg_340 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_val_V_4_reg_340 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_val_V_4_reg_340 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln1897_fu_687_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_pix_val_V_3_phi_fu_361_p12 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_val_V_3_reg_357 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_val_V_3_reg_357 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_val_V_3_reg_357 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_val_V_8_fu_697_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_val_V_phi_fu_381_p12 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixIn_val_V_fu_594_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_val_V_reg_377 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_val_V_reg_377 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_val_V_reg_377 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1930_fu_584_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln1866_fu_517_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1870_fu_541_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_fu_126 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_2_fu_438_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal boxTop_fu_130 : STD_LOGIC_VECTOR (15 downto 0);
    signal boxLeft_fu_134 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal or_ln1839_fu_444_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln1869_fu_507_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1867_fu_512_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln1873_fu_531_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1871_fu_536_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1918_fu_565_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1887_fu_643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boxBottom_fu_638_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1892_fu_659_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boxRight_fu_633_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1887_1_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1887_fu_648_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1892_1_fu_670_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1892_fu_664_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1897_2_fu_681_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1897_1_fu_675_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1902_fu_693_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixOut_val_V_14_fu_711_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_val_V_13_fu_704_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1946_fu_732_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_val_V_15_fu_718_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_739_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_val_V_16_fu_725_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_253 : BOOLEAN;
    signal ap_condition_332 : BOOLEAN;
    signal ap_condition_264 : BOOLEAN;
    signal ap_condition_628 : BOOLEAN;
    signal ap_condition_370 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_729_2_whiYuv_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component design_1_v_tpg_0_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    whiYuv_2_U : component design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_729_2_whiYuv_2_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => whiYuv_2_address0,
        ce0 => whiYuv_2_ce0,
        q0 => whiYuv_2_q0);

    flow_control_loop_pipe_sequential_init_U : component design_1_v_tpg_0_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_pix_val_V_3_reg_357_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_264)) then
                if ((ap_const_boolean_1 = ap_condition_332)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_3_reg_357 <= ap_const_lv8_F0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_3_reg_357 <= ap_phi_reg_pp0_iter1_pix_val_V_3_reg_357;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_val_V_4_reg_340_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_264)) then
                if ((ap_const_boolean_1 = ap_condition_332)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_4_reg_340 <= pixOut_val_V_read_reg_870;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_4_reg_340 <= ap_phi_reg_pp0_iter1_pix_val_V_4_reg_340;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_val_V_reg_377_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_264)) then
                if ((ap_const_boolean_1 = ap_condition_332)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_reg_377 <= ap_const_lv8_F0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_reg_377 <= ap_phi_reg_pp0_iter1_pix_val_V_reg_377;
                end if;
            end if; 
        end if;
    end process;

    boxLeft_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    boxLeft_fu_134 <= boxHCoord_loc_0;
                elsif ((ap_const_boolean_1 = ap_condition_628)) then 
                    boxLeft_fu_134 <= select_ln1866_fu_517_p3;
                end if;
            end if; 
        end if;
    end process;

    boxTop_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    boxTop_fu_130 <= boxVCoord_loc_0;
                elsif ((ap_const_boolean_1 = ap_condition_628)) then 
                    boxTop_fu_130 <= select_ln1870_fu_541_p3;
                end if;
            end if; 
        end if;
    end process;

    hDir_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_370)) then
                if (((icmp_ln1849_fu_470_p2 = ap_const_lv1_1) and (hDir_load_load_fu_455_p1 = ap_const_lv1_1))) then 
                    hDir <= ap_const_lv1_0;
                elsif (((icmp_ln1844_fu_459_p2 = ap_const_lv1_1) and (hDir_load_load_fu_455_p1 = ap_const_lv1_0))) then 
                    hDir <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    vDir_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_370)) then
                if (((icmp_ln1861_fu_496_p2 = ap_const_lv1_1) and (vDir_load_load_fu_481_p1 = ap_const_lv1_1))) then 
                    vDir <= ap_const_lv1_0;
                elsif (((icmp_ln1856_fu_485_p2 = ap_const_lv1_1) and (vDir_load_load_fu_481_p1 = ap_const_lv1_0))) then 
                    vDir <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    x_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_126 <= ap_const_lv16_0;
                elsif (((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    x_fu_126 <= x_2_fu_438_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and10_i_read_reg_843 <= and10_i;
                and26_i_read_reg_855 <= and26_i;
                and4_i_read_reg_860 <= and4_i;
                boxColorG_1_read_reg_806 <= boxColorG_1;
                boxSize_1_read_reg_833 <= boxSize_1;
                cmp101_i_read_reg_811 <= cmp101_i;
                color_read_reg_792 <= color;
                crossHairX_1_read_reg_801 <= crossHairX_1;
                hMax_read_reg_816 <= hMax;
                icmp_ln729_reg_912 <= icmp_ln729_fu_433_p2;
                loopWidth_read_reg_882 <= loopWidth;
                ovrlayId_load_read_reg_839 <= ovrlayId_load;
                pixOut_val_V_7_read_reg_865 <= pixOut_val_V_7;
                pixOut_val_V_9_read_reg_876 <= pixOut_val_V_9;
                pixOut_val_V_read_reg_870 <= pixOut_val_V;
                tobool_read_reg_848 <= tobool;
                trunc_ln729_reg_907 <= trunc_ln729_fu_429_p1;
                vMax_read_reg_821 <= vMax;
                x_1_reg_901 <= x_fu_126;
                    zext_ln1869_1_cast_reg_887(8 downto 0) <= zext_ln1869_1_cast_fu_397_p1(8 downto 0);
                    zext_ln1869_cast_reg_893(7 downto 0) <= zext_ln1869_cast_fu_401_p1(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_pix_val_V_3_reg_357 <= ap_phi_reg_pp0_iter0_pix_val_V_3_reg_357;
                ap_phi_reg_pp0_iter1_pix_val_V_4_reg_340 <= ap_phi_reg_pp0_iter0_pix_val_V_4_reg_340;
                ap_phi_reg_pp0_iter1_pix_val_V_reg_377 <= ap_phi_reg_pp0_iter0_pix_val_V_reg_377;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ovrlayId_load_read_reg_839 = ap_const_lv8_2))) then
                or_ln1918_reg_944 <= or_ln1918_fu_570_p2;
            end if;
        end if;
    end process;
    zext_ln1869_1_cast_reg_887(15 downto 9) <= "0000000";
    zext_ln1869_cast_reg_893(15 downto 8) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1867_fu_512_p2 <= std_logic_vector(unsigned(boxLeft_fu_134) + unsigned(zext_ln1869_cast_reg_893));
    add_ln1871_fu_536_p2 <= std_logic_vector(unsigned(boxTop_fu_130) + unsigned(zext_ln1869_cast_reg_893));
    and_ln1897_1_fu_675_p2 <= (xor_ln1887_fu_648_p2 and icmp_ln1887_1_fu_654_p2);
    and_ln1897_2_fu_681_p2 <= (xor_ln1892_fu_664_p2 and icmp_ln1892_1_fu_670_p2);
    and_ln1897_fu_687_p2 <= (and_ln1897_2_fu_681_p2 and and_ln1897_1_fu_675_p2);
    and_ln1902_fu_693_p2 <= (trunc_ln729_reg_907 and cmp101_i_read_reg_811);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, bckgndYUV_empty_n, icmp_ln729_reg_912, ovrlayYUV_full_n)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ovrlayYUV_full_n = ap_const_logic_0) or ((icmp_ln729_reg_912 = ap_const_lv1_0) and (bckgndYUV_empty_n = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, bckgndYUV_empty_n, icmp_ln729_reg_912, ovrlayYUV_full_n)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ovrlayYUV_full_n = ap_const_logic_0) or ((icmp_ln729_reg_912 = ap_const_lv1_0) and (bckgndYUV_empty_n = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, bckgndYUV_empty_n, icmp_ln729_reg_912, ovrlayYUV_full_n)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ovrlayYUV_full_n = ap_const_logic_0) or ((icmp_ln729_reg_912 = ap_const_lv1_0) and (bckgndYUV_empty_n = ap_const_logic_0))));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_assign_proc : process(bckgndYUV_empty_n, icmp_ln729_reg_912, ovrlayYUV_full_n)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((ovrlayYUV_full_n = ap_const_logic_0) or ((icmp_ln729_reg_912 = ap_const_lv1_0) and (bckgndYUV_empty_n = ap_const_logic_0)));
    end process;


    ap_condition_253_assign_proc : process(icmp_ln729_fu_433_p2, ovrlayId_load_read_reg_839, or_ln1918_fu_570_p2)
    begin
                ap_condition_253 <= ((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (or_ln1918_fu_570_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_839 = ap_const_lv8_2));
    end process;


    ap_condition_264_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_264 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_332_assign_proc : process(icmp_ln729_fu_433_p2, color_read_reg_792, ovrlayId_load_read_reg_839, or_ln1918_fu_570_p2)
    begin
                ap_condition_332 <= ((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (or_ln1918_fu_570_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_839 = ap_const_lv8_2) and (color_read_reg_792 = ap_const_lv8_0));
    end process;


    ap_condition_370_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln729_fu_433_p2, ap_block_pp0_stage0_11001, ovrlayId_load_read_reg_839, icmp_ln1839_fu_449_p2)
    begin
                ap_condition_370 <= ((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln1839_fu_449_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1));
    end process;


    ap_condition_628_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln729_fu_433_p2, ovrlayId_load_read_reg_839, icmp_ln1839_fu_449_p2)
    begin
                ap_condition_628 <= ((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln1839_fu_449_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln729_fu_433_p2)
    begin
        if (((icmp_ln729_fu_433_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_empty_75_phi_fu_316_p8_assign_proc : process(icmp_ln729_fu_433_p2, ovrlayId_load_read_reg_839, icmp_ln1839_fu_449_p2, vDir_load_load_fu_481_p1, icmp_ln1856_fu_485_p2, icmp_ln1861_fu_496_p2, ap_phi_reg_pp0_iter1_empty_75_reg_313)
    begin
        if ((((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (icmp_ln1861_fu_496_p2 = ap_const_lv1_0) and (vDir_load_load_fu_481_p1 = ap_const_lv1_1) and (icmp_ln1839_fu_449_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1)) or ((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (icmp_ln1856_fu_485_p2 = ap_const_lv1_1) and (vDir_load_load_fu_481_p1 = ap_const_lv1_0) and (icmp_ln1839_fu_449_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_75_phi_fu_316_p8 <= ap_const_lv1_1;
        elsif ((((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (icmp_ln1856_fu_485_p2 = ap_const_lv1_0) and (vDir_load_load_fu_481_p1 = ap_const_lv1_0) and (icmp_ln1839_fu_449_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1)) or ((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (icmp_ln1861_fu_496_p2 = ap_const_lv1_1) and (vDir_load_load_fu_481_p1 = ap_const_lv1_1) and (icmp_ln1839_fu_449_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_75_phi_fu_316_p8 <= ap_const_lv1_0;
        else 
            ap_phi_mux_empty_75_phi_fu_316_p8 <= ap_phi_reg_pp0_iter1_empty_75_reg_313;
        end if; 
    end process;


    ap_phi_mux_empty_76_phi_fu_299_p8_assign_proc : process(icmp_ln729_fu_433_p2, ovrlayId_load_read_reg_839, icmp_ln1839_fu_449_p2, hDir_load_load_fu_455_p1, icmp_ln1844_fu_459_p2, icmp_ln1849_fu_470_p2, ap_phi_reg_pp0_iter1_empty_76_reg_296)
    begin
        if ((((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (icmp_ln1849_fu_470_p2 = ap_const_lv1_0) and (hDir_load_load_fu_455_p1 = ap_const_lv1_1) and (icmp_ln1839_fu_449_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1)) or ((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (icmp_ln1844_fu_459_p2 = ap_const_lv1_1) and (hDir_load_load_fu_455_p1 = ap_const_lv1_0) and (icmp_ln1839_fu_449_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_76_phi_fu_299_p8 <= ap_const_lv1_1;
        elsif ((((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (icmp_ln1844_fu_459_p2 = ap_const_lv1_0) and (hDir_load_load_fu_455_p1 = ap_const_lv1_0) and (icmp_ln1839_fu_449_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1)) or ((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (icmp_ln1849_fu_470_p2 = ap_const_lv1_1) and (hDir_load_load_fu_455_p1 = ap_const_lv1_1) and (icmp_ln1839_fu_449_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_76_phi_fu_299_p8 <= ap_const_lv1_0;
        else 
            ap_phi_mux_empty_76_phi_fu_299_p8 <= ap_phi_reg_pp0_iter1_empty_76_reg_296;
        end if; 
    end process;


    ap_phi_mux_phi_ln1930_phi_fu_333_p4_assign_proc : process(color_read_reg_792, select_ln1930_fu_575_p3, ap_phi_reg_pp0_iter1_phi_ln1930_reg_330, ap_condition_253)
    begin
        if ((ap_const_boolean_1 = ap_condition_253)) then
            if ((color_read_reg_792 = ap_const_lv8_1)) then 
                ap_phi_mux_phi_ln1930_phi_fu_333_p4 <= ap_const_lv2_1;
            elsif ((not((color_read_reg_792 = ap_const_lv8_1)) and not((color_read_reg_792 = ap_const_lv8_0)))) then 
                ap_phi_mux_phi_ln1930_phi_fu_333_p4 <= select_ln1930_fu_575_p3;
            else 
                ap_phi_mux_phi_ln1930_phi_fu_333_p4 <= ap_phi_reg_pp0_iter1_phi_ln1930_reg_330;
            end if;
        else 
            ap_phi_mux_phi_ln1930_phi_fu_333_p4 <= ap_phi_reg_pp0_iter1_phi_ln1930_reg_330;
        end if; 
    end process;


    ap_phi_mux_pix_val_V_3_phi_fu_361_p12_assign_proc : process(bckgndYUV_dout, icmp_ln729_reg_912, whiYuv_2_q0, color_read_reg_792, ovrlayId_load_read_reg_839, or_ln1918_reg_944, and_ln1897_fu_687_p2, ap_phi_reg_pp0_iter2_pix_val_V_3_reg_357, pixOut_val_V_8_fu_697_p3)
    begin
        if ((not((color_read_reg_792 = ap_const_lv8_0)) and (icmp_ln729_reg_912 = ap_const_lv1_0) and (or_ln1918_reg_944 = ap_const_lv1_1) and (ovrlayId_load_read_reg_839 = ap_const_lv8_2))) then 
            ap_phi_mux_pix_val_V_3_phi_fu_361_p12 <= whiYuv_2_q0;
        elsif (((ap_const_lv1_1 = and_ln1897_fu_687_p2) and (icmp_ln729_reg_912 = ap_const_lv1_0) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1))) then 
            ap_phi_mux_pix_val_V_3_phi_fu_361_p12 <= pixOut_val_V_8_fu_697_p3;
        elsif ((((icmp_ln729_reg_912 = ap_const_lv1_0) and (or_ln1918_reg_944 = ap_const_lv1_0) and (ovrlayId_load_read_reg_839 = ap_const_lv8_2)) or ((ap_const_lv1_0 = and_ln1897_fu_687_p2) and (icmp_ln729_reg_912 = ap_const_lv1_0) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1)) or (not((ovrlayId_load_read_reg_839 = ap_const_lv8_2)) and not((ovrlayId_load_read_reg_839 = ap_const_lv8_1)) and (icmp_ln729_reg_912 = ap_const_lv1_0)))) then 
            ap_phi_mux_pix_val_V_3_phi_fu_361_p12 <= bckgndYUV_dout(15 downto 8);
        else 
            ap_phi_mux_pix_val_V_3_phi_fu_361_p12 <= ap_phi_reg_pp0_iter2_pix_val_V_3_reg_357;
        end if; 
    end process;


    ap_phi_mux_pix_val_V_4_phi_fu_343_p12_assign_proc : process(bckgndYUV_dout, icmp_ln729_reg_912, color_read_reg_792, ovrlayId_load_read_reg_839, pixOut_val_V_read_reg_870, pixOut_val_V_9_read_reg_876, or_ln1918_reg_944, ap_phi_reg_pp0_iter2_pix_val_V_4_reg_340, and_ln1897_fu_687_p2)
    begin
        if ((not((color_read_reg_792 = ap_const_lv8_0)) and (icmp_ln729_reg_912 = ap_const_lv1_0) and (or_ln1918_reg_944 = ap_const_lv1_1) and (ovrlayId_load_read_reg_839 = ap_const_lv8_2))) then 
            ap_phi_mux_pix_val_V_4_phi_fu_343_p12 <= pixOut_val_V_read_reg_870;
        elsif (((ap_const_lv1_1 = and_ln1897_fu_687_p2) and (icmp_ln729_reg_912 = ap_const_lv1_0) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1))) then 
            ap_phi_mux_pix_val_V_4_phi_fu_343_p12 <= pixOut_val_V_9_read_reg_876;
        elsif ((((icmp_ln729_reg_912 = ap_const_lv1_0) and (or_ln1918_reg_944 = ap_const_lv1_0) and (ovrlayId_load_read_reg_839 = ap_const_lv8_2)) or ((ap_const_lv1_0 = and_ln1897_fu_687_p2) and (icmp_ln729_reg_912 = ap_const_lv1_0) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1)) or (not((ovrlayId_load_read_reg_839 = ap_const_lv8_2)) and not((ovrlayId_load_read_reg_839 = ap_const_lv8_1)) and (icmp_ln729_reg_912 = ap_const_lv1_0)))) then 
            ap_phi_mux_pix_val_V_4_phi_fu_343_p12 <= bckgndYUV_dout(23 downto 16);
        else 
            ap_phi_mux_pix_val_V_4_phi_fu_343_p12 <= ap_phi_reg_pp0_iter2_pix_val_V_4_reg_340;
        end if; 
    end process;


    ap_phi_mux_pix_val_V_phi_fu_381_p12_assign_proc : process(icmp_ln729_reg_912, color_read_reg_792, ovrlayId_load_read_reg_839, pixOut_val_V_7_read_reg_865, or_ln1918_reg_944, and_ln1897_fu_687_p2, pixIn_val_V_fu_594_p1, ap_phi_reg_pp0_iter2_pix_val_V_reg_377)
    begin
        if ((not((color_read_reg_792 = ap_const_lv8_0)) and (icmp_ln729_reg_912 = ap_const_lv1_0) and (or_ln1918_reg_944 = ap_const_lv1_1) and (ovrlayId_load_read_reg_839 = ap_const_lv8_2))) then 
            ap_phi_mux_pix_val_V_phi_fu_381_p12 <= ap_const_lv8_F0;
        elsif (((ap_const_lv1_1 = and_ln1897_fu_687_p2) and (icmp_ln729_reg_912 = ap_const_lv1_0) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1))) then 
            ap_phi_mux_pix_val_V_phi_fu_381_p12 <= pixOut_val_V_7_read_reg_865;
        elsif ((((icmp_ln729_reg_912 = ap_const_lv1_0) and (or_ln1918_reg_944 = ap_const_lv1_0) and (ovrlayId_load_read_reg_839 = ap_const_lv8_2)) or ((ap_const_lv1_0 = and_ln1897_fu_687_p2) and (icmp_ln729_reg_912 = ap_const_lv1_0) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1)) or (not((ovrlayId_load_read_reg_839 = ap_const_lv8_2)) and not((ovrlayId_load_read_reg_839 = ap_const_lv8_1)) and (icmp_ln729_reg_912 = ap_const_lv1_0)))) then 
            ap_phi_mux_pix_val_V_phi_fu_381_p12 <= pixIn_val_V_fu_594_p1;
        else 
            ap_phi_mux_pix_val_V_phi_fu_381_p12 <= ap_phi_reg_pp0_iter2_pix_val_V_reg_377;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_pix_val_V_3_reg_357 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_val_V_4_reg_340 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_val_V_reg_377 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter1_empty_75_reg_313 <= "X";
    ap_phi_reg_pp0_iter1_empty_76_reg_296 <= "X";
    ap_phi_reg_pp0_iter1_phi_ln1930_reg_330 <= "XX";

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    bckgndYUV_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, bckgndYUV_empty_n, icmp_ln729_reg_912, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln729_reg_912 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            bckgndYUV_blk_n <= bckgndYUV_empty_n;
        else 
            bckgndYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bckgndYUV_read_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln729_reg_912, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_912 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            bckgndYUV_read <= ap_const_logic_1;
        else 
            bckgndYUV_read <= ap_const_logic_0;
        end if; 
    end process;

    boxBottom_fu_638_p2 <= std_logic_vector(unsigned(boxSize_1_read_reg_833) + unsigned(boxTop_fu_130));
    boxHCoord <= 
        sub_ln1869_fu_507_p2 when (ap_phi_mux_empty_76_phi_fu_299_p8(0) = '1') else 
        add_ln1867_fu_512_p2;

    boxHCoord_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln729_fu_433_p2, ap_block_pp0_stage0_11001, ovrlayId_load_read_reg_839, icmp_ln1839_fu_449_p2)
    begin
        if (((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln1839_fu_449_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1))) then 
            boxHCoord_ap_vld <= ap_const_logic_1;
        else 
            boxHCoord_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    boxHCoord_loc_1_out <= boxLeft_fu_134;

    boxHCoord_loc_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln729_fu_433_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln729_fu_433_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            boxHCoord_loc_1_out_ap_vld <= ap_const_logic_1;
        else 
            boxHCoord_loc_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    boxRight_fu_633_p2 <= std_logic_vector(unsigned(boxSize_1_read_reg_833) + unsigned(boxLeft_fu_134));
    boxVCoord <= 
        sub_ln1873_fu_531_p2 when (ap_phi_mux_empty_75_phi_fu_316_p8(0) = '1') else 
        add_ln1871_fu_536_p2;

    boxVCoord_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln729_fu_433_p2, ap_block_pp0_stage0_11001, ovrlayId_load_read_reg_839, icmp_ln1839_fu_449_p2)
    begin
        if (((icmp_ln729_fu_433_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln1839_fu_449_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ovrlayId_load_read_reg_839 = ap_const_lv8_1))) then 
            boxVCoord_ap_vld <= ap_const_logic_1;
        else 
            boxVCoord_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    boxVCoord_loc_1_out <= boxTop_fu_130;

    boxVCoord_loc_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln729_fu_433_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln729_fu_433_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            boxVCoord_loc_1_out_ap_vld <= ap_const_logic_1;
        else 
            boxVCoord_loc_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_739_p3 <= 
        ap_phi_mux_pix_val_V_3_phi_fu_361_p12 when (tobool_read_reg_848(0) = '1') else 
        select_ln1946_fu_732_p3;
    hDir_load_load_fu_455_p1 <= hDir;
    icmp_ln1839_fu_449_p2 <= "1" when (or_ln1839_fu_444_p2 = ap_const_lv16_0) else "0";
    icmp_ln1844_fu_459_p2 <= "1" when (unsigned(boxLeft_fu_134) > unsigned(hMax_read_reg_816)) else "0";
    icmp_ln1849_fu_470_p2 <= "1" when (unsigned(zext_ln1869_1_cast_reg_887) > unsigned(boxLeft_fu_134)) else "0";
    icmp_ln1856_fu_485_p2 <= "1" when (unsigned(boxTop_fu_130) > unsigned(vMax_read_reg_821)) else "0";
    icmp_ln1861_fu_496_p2 <= "1" when (unsigned(zext_ln1869_1_cast_reg_887) > unsigned(boxTop_fu_130)) else "0";
    icmp_ln1887_1_fu_654_p2 <= "1" when (unsigned(y) < unsigned(boxBottom_fu_638_p2)) else "0";
    icmp_ln1887_fu_643_p2 <= "1" when (unsigned(y) < unsigned(boxTop_fu_130)) else "0";
    icmp_ln1892_1_fu_670_p2 <= "1" when (unsigned(x_1_reg_901) < unsigned(boxRight_fu_633_p2)) else "0";
    icmp_ln1892_fu_659_p2 <= "1" when (unsigned(x_1_reg_901) < unsigned(boxLeft_fu_134)) else "0";
    icmp_ln1918_fu_565_p2 <= "1" when (x_fu_126 = crossHairX_1_read_reg_801) else "0";
    icmp_ln729_fu_433_p2 <= "1" when (x_fu_126 = loopWidth_read_reg_882) else "0";
    or_ln1839_fu_444_p2 <= (y or x_fu_126);
    or_ln1918_fu_570_p2 <= (icmp_ln1918_fu_565_p2 or cmp2_i);

    ovrlayYUV_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, ovrlayYUV_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ovrlayYUV_blk_n <= ovrlayYUV_full_n;
        else 
            ovrlayYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ovrlayYUV_din <= ((pixOut_val_V_15_fu_718_p3 & empty_fu_739_p3) & pixOut_val_V_16_fu_725_p3);

    ovrlayYUV_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ovrlayYUV_write <= ap_const_logic_1;
        else 
            ovrlayYUV_write <= ap_const_logic_0;
        end if; 
    end process;

    pixIn_val_V_fu_594_p1 <= bckgndYUV_dout(8 - 1 downto 0);
    pixOut_val_V_13_fu_704_p3 <= 
        ap_const_lv8_0 when (and4_i_read_reg_860(0) = '1') else 
        ap_phi_mux_pix_val_V_phi_fu_381_p12;
    pixOut_val_V_14_fu_711_p3 <= 
        ap_const_lv8_0 when (and26_i_read_reg_855(0) = '1') else 
        ap_phi_mux_pix_val_V_4_phi_fu_343_p12;
    pixOut_val_V_15_fu_718_p3 <= 
        ap_phi_mux_pix_val_V_4_phi_fu_343_p12 when (tobool_read_reg_848(0) = '1') else 
        pixOut_val_V_14_fu_711_p3;
    pixOut_val_V_16_fu_725_p3 <= 
        ap_phi_mux_pix_val_V_phi_fu_381_p12 when (tobool_read_reg_848(0) = '1') else 
        pixOut_val_V_13_fu_704_p3;
    pixOut_val_V_8_fu_697_p3 <= 
        pixOut_val_V_9_read_reg_876 when (and_ln1902_fu_693_p2(0) = '1') else 
        boxColorG_1_read_reg_806;
    select_ln1866_fu_517_p3 <= 
        sub_ln1869_fu_507_p2 when (ap_phi_mux_empty_76_phi_fu_299_p8(0) = '1') else 
        add_ln1867_fu_512_p2;
    select_ln1870_fu_541_p3 <= 
        sub_ln1873_fu_531_p2 when (ap_phi_mux_empty_75_phi_fu_316_p8(0) = '1') else 
        add_ln1871_fu_536_p2;
    select_ln1930_fu_575_p3 <= 
        ap_const_lv2_2 when (trunc_ln729_fu_429_p1(0) = '1') else 
        ap_const_lv2_1;
    select_ln1946_fu_732_p3 <= 
        ap_const_lv8_0 when (and10_i_read_reg_843(0) = '1') else 
        ap_phi_mux_pix_val_V_3_phi_fu_361_p12;
    sub_ln1869_fu_507_p2 <= std_logic_vector(unsigned(boxLeft_fu_134) - unsigned(zext_ln1869_cast_reg_893));
    sub_ln1873_fu_531_p2 <= std_logic_vector(unsigned(boxTop_fu_130) - unsigned(zext_ln1869_cast_reg_893));
    trunc_ln729_fu_429_p1 <= x_fu_126(1 - 1 downto 0);
    vDir_load_load_fu_481_p1 <= vDir;
    whiYuv_2_address0 <= zext_ln1930_fu_584_p1(2 - 1 downto 0);

    whiYuv_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            whiYuv_2_ce0 <= ap_const_logic_1;
        else 
            whiYuv_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_2_fu_438_p2 <= std_logic_vector(unsigned(x_fu_126) + unsigned(ap_const_lv16_1));
    xor_ln1887_fu_648_p2 <= (icmp_ln1887_fu_643_p2 xor ap_const_lv1_1);
    xor_ln1892_fu_664_p2 <= (icmp_ln1892_fu_659_p2 xor ap_const_lv1_1);
    zext_ln1869_1_cast_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln1869_1),16));
    zext_ln1869_cast_fu_401_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln1869),16));
    zext_ln1930_fu_584_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_phi_ln1930_phi_fu_333_p4),64));
end behav;
