# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sundance/Emilie_Projects/git/EMC2/BSP_HDMI_out_TE0820_4EV/2022.2/firmware/EMC2_HDMI_out.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0.xci
# IP: The module: 'design_1_auto_cc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sundance/Emilie_Projects/git/EMC2/BSP_HDMI_out_TE0820_4EV/2022.2/firmware/EMC2_HDMI_out.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0_1/design_1_auto_cc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_cc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/sundance/Emilie_Projects/git/EMC2/BSP_HDMI_out_TE0820_4EV/2022.2/firmware/EMC2_HDMI_out.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0_1/design_1_auto_cc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/sundance/Emilie_Projects/git/EMC2/BSP_HDMI_out_TE0820_4EV/2022.2/firmware/EMC2_HDMI_out.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0.xci
# IP: The module: 'design_1_auto_cc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sundance/Emilie_Projects/git/EMC2/BSP_HDMI_out_TE0820_4EV/2022.2/firmware/EMC2_HDMI_out.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0_1/design_1_auto_cc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/sundance/Emilie_Projects/git/EMC2/BSP_HDMI_out_TE0820_4EV/2022.2/firmware/EMC2_HDMI_out.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0_1/design_1_auto_cc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
