// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_v_tpgHlsDataFlow (
        s_axis_video_TDATA,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        height_val5,
        width_val10,
        field_id_val11,
        fid_in_val12,
        passthruStartX_val13,
        passthruStartY_val14,
        passthruEndX_val15,
        passthruEndY_val16,
        enableInput_val18,
        bckgndId_val19,
        ovrlayId_val20,
        maskId_val21,
        motionSpeed_val23,
        colorFormat_val27,
        crossHairX_val28,
        crossHairY_val29,
        ZplateHorContStart_val30,
        ZplateHorContDelta_val31,
        ZplateVerContStart_val32,
        ZplateVerContDelta_val33,
        boxSize_val34,
        boxColorR_val35,
        boxColorG_val36,
        boxColorB_val37,
        dpDynamicRange_val38,
        dpYUVCoef_val39,
        m_axis_video_TDATA,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        fid,
        s,
        ap_clk,
        ap_rst,
        field_id_val11_ap_vld,
        fid_in_val12_ap_vld,
        passthruStartX_val13_ap_vld,
        passthruStartY_val14_ap_vld,
        passthruEndX_val15_ap_vld,
        passthruEndY_val16_ap_vld,
        bckgndId_val19_ap_vld,
        ovrlayId_val20_ap_vld,
        maskId_val21_ap_vld,
        motionSpeed_val23_ap_vld,
        crossHairX_val28_ap_vld,
        crossHairY_val29_ap_vld,
        ZplateHorContStart_val30_ap_vld,
        ZplateHorContDelta_val31_ap_vld,
        ZplateVerContStart_val32_ap_vld,
        ZplateVerContDelta_val33_ap_vld,
        boxSize_val34_ap_vld,
        boxColorR_val35_ap_vld,
        boxColorG_val36_ap_vld,
        boxColorB_val37_ap_vld,
        dpDynamicRange_val38_ap_vld,
        dpYUVCoef_val39_ap_vld,
        ap_start,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        enableInput_val18_ap_vld,
        height_val5_ap_vld,
        width_val10_ap_vld,
        colorFormat_val27_ap_vld,
        s_ap_vld,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        fid_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [23:0] s_axis_video_TDATA;
input  [2:0] s_axis_video_TKEEP;
input  [2:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
input  [15:0] height_val5;
input  [15:0] width_val10;
input  [15:0] field_id_val11;
input  [0:0] fid_in_val12;
input  [15:0] passthruStartX_val13;
input  [15:0] passthruStartY_val14;
input  [15:0] passthruEndX_val15;
input  [15:0] passthruEndY_val16;
input  [7:0] enableInput_val18;
input  [7:0] bckgndId_val19;
input  [7:0] ovrlayId_val20;
input  [7:0] maskId_val21;
input  [7:0] motionSpeed_val23;
input  [7:0] colorFormat_val27;
input  [15:0] crossHairX_val28;
input  [15:0] crossHairY_val29;
input  [15:0] ZplateHorContStart_val30;
input  [15:0] ZplateHorContDelta_val31;
input  [15:0] ZplateVerContStart_val32;
input  [15:0] ZplateVerContDelta_val33;
input  [15:0] boxSize_val34;
input  [7:0] boxColorR_val35;
input  [7:0] boxColorG_val36;
input  [7:0] boxColorB_val37;
input  [7:0] dpDynamicRange_val38;
input  [7:0] dpYUVCoef_val39;
output  [23:0] m_axis_video_TDATA;
output  [2:0] m_axis_video_TKEEP;
output  [2:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
output  [0:0] fid;
input  [31:0] s;
input   ap_clk;
input   ap_rst;
input   field_id_val11_ap_vld;
input   fid_in_val12_ap_vld;
input   passthruStartX_val13_ap_vld;
input   passthruStartY_val14_ap_vld;
input   passthruEndX_val15_ap_vld;
input   passthruEndY_val16_ap_vld;
input   bckgndId_val19_ap_vld;
input   ovrlayId_val20_ap_vld;
input   maskId_val21_ap_vld;
input   motionSpeed_val23_ap_vld;
input   crossHairX_val28_ap_vld;
input   crossHairY_val29_ap_vld;
input   ZplateHorContStart_val30_ap_vld;
input   ZplateHorContDelta_val31_ap_vld;
input   ZplateVerContStart_val32_ap_vld;
input   ZplateVerContDelta_val33_ap_vld;
input   boxSize_val34_ap_vld;
input   boxColorR_val35_ap_vld;
input   boxColorG_val36_ap_vld;
input   boxColorB_val37_ap_vld;
input   dpDynamicRange_val38_ap_vld;
input   dpYUVCoef_val39_ap_vld;
input   ap_start;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input   enableInput_val18_ap_vld;
input   height_val5_ap_vld;
input   width_val10_ap_vld;
input   colorFormat_val27_ap_vld;
input   s_ap_vld;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output   fid_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_start_full_n;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [15:0] entry_proc_U0_field_id_val11_c_din;
wire    entry_proc_U0_field_id_val11_c_write;
wire   [0:0] entry_proc_U0_fid_in_val12_c_din;
wire    entry_proc_U0_fid_in_val12_c_write;
wire   [15:0] entry_proc_U0_passthruStartX_val13_c_din;
wire    entry_proc_U0_passthruStartX_val13_c_write;
wire   [15:0] entry_proc_U0_passthruStartY_val14_c_din;
wire    entry_proc_U0_passthruStartY_val14_c_write;
wire   [15:0] entry_proc_U0_passthruEndX_val15_c_din;
wire    entry_proc_U0_passthruEndX_val15_c_write;
wire   [15:0] entry_proc_U0_passthruEndY_val16_c_din;
wire    entry_proc_U0_passthruEndY_val16_c_write;
wire   [7:0] entry_proc_U0_bckgndId_val19_c_din;
wire    entry_proc_U0_bckgndId_val19_c_write;
wire   [7:0] entry_proc_U0_ovrlayId_val20_c_din;
wire    entry_proc_U0_ovrlayId_val20_c_write;
wire   [7:0] entry_proc_U0_maskId_val21_c_din;
wire    entry_proc_U0_maskId_val21_c_write;
wire   [7:0] entry_proc_U0_motionSpeed_val23_c18_din;
wire    entry_proc_U0_motionSpeed_val23_c18_write;
wire   [15:0] entry_proc_U0_crossHairX_val28_c_din;
wire    entry_proc_U0_crossHairX_val28_c_write;
wire   [15:0] entry_proc_U0_crossHairY_val29_c_din;
wire    entry_proc_U0_crossHairY_val29_c_write;
wire   [15:0] entry_proc_U0_ZplateHorContStart_val30_c_din;
wire    entry_proc_U0_ZplateHorContStart_val30_c_write;
wire   [15:0] entry_proc_U0_ZplateHorContDelta_val31_c_din;
wire    entry_proc_U0_ZplateHorContDelta_val31_c_write;
wire   [15:0] entry_proc_U0_ZplateVerContStart_val32_c_din;
wire    entry_proc_U0_ZplateVerContStart_val32_c_write;
wire   [15:0] entry_proc_U0_ZplateVerContDelta_val33_c_din;
wire    entry_proc_U0_ZplateVerContDelta_val33_c_write;
wire   [15:0] entry_proc_U0_boxSize_val34_c_din;
wire    entry_proc_U0_boxSize_val34_c_write;
wire   [7:0] entry_proc_U0_boxColorR_val35_c_din;
wire    entry_proc_U0_boxColorR_val35_c_write;
wire   [7:0] entry_proc_U0_boxColorG_val36_c_din;
wire    entry_proc_U0_boxColorG_val36_c_write;
wire   [7:0] entry_proc_U0_boxColorB_val37_c_din;
wire    entry_proc_U0_boxColorB_val37_c_write;
wire   [7:0] entry_proc_U0_dpDynamicRange_val38_c_din;
wire    entry_proc_U0_dpDynamicRange_val38_c_write;
wire   [7:0] entry_proc_U0_dpYUVCoef_val39_c_din;
wire    entry_proc_U0_dpYUVCoef_val39_c_write;
wire    AXIvideo2MultiPixStream_U0_ap_start;
wire    AXIvideo2MultiPixStream_U0_ap_done;
wire    AXIvideo2MultiPixStream_U0_ap_continue;
wire    AXIvideo2MultiPixStream_U0_ap_idle;
wire    AXIvideo2MultiPixStream_U0_ap_ready;
wire    AXIvideo2MultiPixStream_U0_s_axis_video_TREADY;
wire   [23:0] AXIvideo2MultiPixStream_U0_srcYUV_din;
wire    AXIvideo2MultiPixStream_U0_srcYUV_write;
wire   [15:0] AXIvideo2MultiPixStream_U0_height_val5_c15_din;
wire    AXIvideo2MultiPixStream_U0_height_val5_c15_write;
wire   [15:0] AXIvideo2MultiPixStream_U0_width_val10_c17_din;
wire    AXIvideo2MultiPixStream_U0_width_val10_c17_write;
wire   [7:0] AXIvideo2MultiPixStream_U0_enableInput_val18_c_din;
wire    AXIvideo2MultiPixStream_U0_enableInput_val18_c_write;
wire   [7:0] AXIvideo2MultiPixStream_U0_colorFormat_val27_c20_din;
wire    AXIvideo2MultiPixStream_U0_colorFormat_val27_c20_write;
wire    tpgBackground_U0_ap_start;
wire    tpgBackground_U0_ap_done;
wire    tpgBackground_U0_ap_continue;
wire    tpgBackground_U0_ap_idle;
wire    tpgBackground_U0_ap_ready;
wire    tpgBackground_U0_srcYUV_read;
wire    tpgBackground_U0_height_val_read;
wire    tpgBackground_U0_width_val_read;
wire    tpgBackground_U0_passthruStartX_val_read;
wire    tpgBackground_U0_passthruStartY_val_read;
wire    tpgBackground_U0_passthruEndX_val_read;
wire    tpgBackground_U0_passthruEndY_val_read;
wire    tpgBackground_U0_enableInput_val_read;
wire    tpgBackground_U0_patternId_val_read;
wire    tpgBackground_U0_ZplateHorContStart_val_read;
wire    tpgBackground_U0_ZplateHorContDelta_val_read;
wire    tpgBackground_U0_ZplateVerContStart_val_read;
wire    tpgBackground_U0_ZplateVerContDelta_val_read;
wire    tpgBackground_U0_dpDynamicRange_val_read;
wire    tpgBackground_U0_dpYUVCoef_val_read;
wire    tpgBackground_U0_motionSpeed_val_read;
wire    tpgBackground_U0_colorFormat_val_read;
wire   [23:0] tpgBackground_U0_bckgndYUV_din;
wire    tpgBackground_U0_bckgndYUV_write;
wire   [15:0] tpgBackground_U0_height_val5_c14_din;
wire    tpgBackground_U0_height_val5_c14_write;
wire   [15:0] tpgBackground_U0_width_val10_c16_din;
wire    tpgBackground_U0_width_val10_c16_write;
wire   [7:0] tpgBackground_U0_motionSpeed_val23_c_din;
wire    tpgBackground_U0_motionSpeed_val23_c_write;
wire   [7:0] tpgBackground_U0_colorFormat_val27_c19_din;
wire    tpgBackground_U0_colorFormat_val27_c19_write;
wire    tpgForeground_U0_ap_start;
wire    tpgForeground_U0_ap_done;
wire    tpgForeground_U0_ap_continue;
wire    tpgForeground_U0_ap_idle;
wire    tpgForeground_U0_ap_ready;
wire    tpgForeground_U0_bckgndYUV_read;
wire    tpgForeground_U0_height_val_read;
wire    tpgForeground_U0_width_val_read;
wire    tpgForeground_U0_patternId_val_read;
wire    tpgForeground_U0_maskId_val_read;
wire    tpgForeground_U0_colorFormat_val_read;
wire    tpgForeground_U0_crossHairX_val_read;
wire    tpgForeground_U0_crossHairY_val_read;
wire    tpgForeground_U0_boxSize_val_read;
wire    tpgForeground_U0_boxColorR_val_read;
wire    tpgForeground_U0_boxColorG_val_read;
wire    tpgForeground_U0_boxColorB_val_read;
wire    tpgForeground_U0_motionSpeed_val_read;
wire   [23:0] tpgForeground_U0_ovrlayYUV_din;
wire    tpgForeground_U0_ovrlayYUV_write;
wire   [9:0] tpgForeground_U0_height_val5_c_din;
wire    tpgForeground_U0_height_val5_c_write;
wire   [10:0] tpgForeground_U0_width_val10_c_din;
wire    tpgForeground_U0_width_val10_c_write;
wire   [7:0] tpgForeground_U0_colorFormat_val27_c_din;
wire    tpgForeground_U0_colorFormat_val27_c_write;
wire    MultiPixStream2AXIvideo_U0_ap_start;
wire    MultiPixStream2AXIvideo_U0_ap_done;
wire    MultiPixStream2AXIvideo_U0_ap_continue;
wire    MultiPixStream2AXIvideo_U0_ap_idle;
wire    MultiPixStream2AXIvideo_U0_ap_ready;
wire    MultiPixStream2AXIvideo_U0_ovrlayYUV_read;
wire   [23:0] MultiPixStream2AXIvideo_U0_m_axis_video_TDATA;
wire    MultiPixStream2AXIvideo_U0_m_axis_video_TVALID;
wire   [2:0] MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP;
wire   [2:0] MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TUSER;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TLAST;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TID;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TDEST;
wire    MultiPixStream2AXIvideo_U0_height_val5_read;
wire    MultiPixStream2AXIvideo_U0_width_val10_read;
wire    MultiPixStream2AXIvideo_U0_colorFormat_val27_read;
wire    MultiPixStream2AXIvideo_U0_fid_in_val12_read;
wire   [0:0] MultiPixStream2AXIvideo_U0_fid;
wire    MultiPixStream2AXIvideo_U0_fid_ap_vld;
wire    MultiPixStream2AXIvideo_U0_field_id_val11_read;
wire    field_id_val11_c_full_n;
wire   [15:0] field_id_val11_c_dout;
wire   [3:0] field_id_val11_c_num_data_valid;
wire   [3:0] field_id_val11_c_fifo_cap;
wire    field_id_val11_c_empty_n;
wire    fid_in_val12_c_full_n;
wire   [0:0] fid_in_val12_c_dout;
wire   [3:0] fid_in_val12_c_num_data_valid;
wire   [3:0] fid_in_val12_c_fifo_cap;
wire    fid_in_val12_c_empty_n;
wire    passthruStartX_val13_c_full_n;
wire   [15:0] passthruStartX_val13_c_dout;
wire   [2:0] passthruStartX_val13_c_num_data_valid;
wire   [2:0] passthruStartX_val13_c_fifo_cap;
wire    passthruStartX_val13_c_empty_n;
wire    passthruStartY_val14_c_full_n;
wire   [15:0] passthruStartY_val14_c_dout;
wire   [2:0] passthruStartY_val14_c_num_data_valid;
wire   [2:0] passthruStartY_val14_c_fifo_cap;
wire    passthruStartY_val14_c_empty_n;
wire    passthruEndX_val15_c_full_n;
wire   [15:0] passthruEndX_val15_c_dout;
wire   [2:0] passthruEndX_val15_c_num_data_valid;
wire   [2:0] passthruEndX_val15_c_fifo_cap;
wire    passthruEndX_val15_c_empty_n;
wire    passthruEndY_val16_c_full_n;
wire   [15:0] passthruEndY_val16_c_dout;
wire   [2:0] passthruEndY_val16_c_num_data_valid;
wire   [2:0] passthruEndY_val16_c_fifo_cap;
wire    passthruEndY_val16_c_empty_n;
wire    bckgndId_val19_c_full_n;
wire   [7:0] bckgndId_val19_c_dout;
wire   [2:0] bckgndId_val19_c_num_data_valid;
wire   [2:0] bckgndId_val19_c_fifo_cap;
wire    bckgndId_val19_c_empty_n;
wire    ovrlayId_val20_c_full_n;
wire   [7:0] ovrlayId_val20_c_dout;
wire   [2:0] ovrlayId_val20_c_num_data_valid;
wire   [2:0] ovrlayId_val20_c_fifo_cap;
wire    ovrlayId_val20_c_empty_n;
wire    maskId_val21_c_full_n;
wire   [7:0] maskId_val21_c_dout;
wire   [2:0] maskId_val21_c_num_data_valid;
wire   [2:0] maskId_val21_c_fifo_cap;
wire    maskId_val21_c_empty_n;
wire    motionSpeed_val23_c18_full_n;
wire   [7:0] motionSpeed_val23_c18_dout;
wire   [2:0] motionSpeed_val23_c18_num_data_valid;
wire   [2:0] motionSpeed_val23_c18_fifo_cap;
wire    motionSpeed_val23_c18_empty_n;
wire    crossHairX_val28_c_full_n;
wire   [15:0] crossHairX_val28_c_dout;
wire   [2:0] crossHairX_val28_c_num_data_valid;
wire   [2:0] crossHairX_val28_c_fifo_cap;
wire    crossHairX_val28_c_empty_n;
wire    crossHairY_val29_c_full_n;
wire   [15:0] crossHairY_val29_c_dout;
wire   [2:0] crossHairY_val29_c_num_data_valid;
wire   [2:0] crossHairY_val29_c_fifo_cap;
wire    crossHairY_val29_c_empty_n;
wire    ZplateHorContStart_val30_c_full_n;
wire   [15:0] ZplateHorContStart_val30_c_dout;
wire   [2:0] ZplateHorContStart_val30_c_num_data_valid;
wire   [2:0] ZplateHorContStart_val30_c_fifo_cap;
wire    ZplateHorContStart_val30_c_empty_n;
wire    ZplateHorContDelta_val31_c_full_n;
wire   [15:0] ZplateHorContDelta_val31_c_dout;
wire   [2:0] ZplateHorContDelta_val31_c_num_data_valid;
wire   [2:0] ZplateHorContDelta_val31_c_fifo_cap;
wire    ZplateHorContDelta_val31_c_empty_n;
wire    ZplateVerContStart_val32_c_full_n;
wire   [15:0] ZplateVerContStart_val32_c_dout;
wire   [2:0] ZplateVerContStart_val32_c_num_data_valid;
wire   [2:0] ZplateVerContStart_val32_c_fifo_cap;
wire    ZplateVerContStart_val32_c_empty_n;
wire    ZplateVerContDelta_val33_c_full_n;
wire   [15:0] ZplateVerContDelta_val33_c_dout;
wire   [2:0] ZplateVerContDelta_val33_c_num_data_valid;
wire   [2:0] ZplateVerContDelta_val33_c_fifo_cap;
wire    ZplateVerContDelta_val33_c_empty_n;
wire    boxSize_val34_c_full_n;
wire   [15:0] boxSize_val34_c_dout;
wire   [2:0] boxSize_val34_c_num_data_valid;
wire   [2:0] boxSize_val34_c_fifo_cap;
wire    boxSize_val34_c_empty_n;
wire    boxColorR_val35_c_full_n;
wire   [7:0] boxColorR_val35_c_dout;
wire   [2:0] boxColorR_val35_c_num_data_valid;
wire   [2:0] boxColorR_val35_c_fifo_cap;
wire    boxColorR_val35_c_empty_n;
wire    boxColorG_val36_c_full_n;
wire   [7:0] boxColorG_val36_c_dout;
wire   [2:0] boxColorG_val36_c_num_data_valid;
wire   [2:0] boxColorG_val36_c_fifo_cap;
wire    boxColorG_val36_c_empty_n;
wire    boxColorB_val37_c_full_n;
wire   [7:0] boxColorB_val37_c_dout;
wire   [2:0] boxColorB_val37_c_num_data_valid;
wire   [2:0] boxColorB_val37_c_fifo_cap;
wire    boxColorB_val37_c_empty_n;
wire    dpDynamicRange_val38_c_full_n;
wire   [7:0] dpDynamicRange_val38_c_dout;
wire   [2:0] dpDynamicRange_val38_c_num_data_valid;
wire   [2:0] dpDynamicRange_val38_c_fifo_cap;
wire    dpDynamicRange_val38_c_empty_n;
wire    dpYUVCoef_val39_c_full_n;
wire   [7:0] dpYUVCoef_val39_c_dout;
wire   [2:0] dpYUVCoef_val39_c_num_data_valid;
wire   [2:0] dpYUVCoef_val39_c_fifo_cap;
wire    dpYUVCoef_val39_c_empty_n;
wire    srcYUV_full_n;
wire   [23:0] srcYUV_dout;
wire   [4:0] srcYUV_num_data_valid;
wire   [4:0] srcYUV_fifo_cap;
wire    srcYUV_empty_n;
wire    height_val5_c15_full_n;
wire   [15:0] height_val5_c15_dout;
wire   [2:0] height_val5_c15_num_data_valid;
wire   [2:0] height_val5_c15_fifo_cap;
wire    height_val5_c15_empty_n;
wire    width_val10_c17_full_n;
wire   [15:0] width_val10_c17_dout;
wire   [2:0] width_val10_c17_num_data_valid;
wire   [2:0] width_val10_c17_fifo_cap;
wire    width_val10_c17_empty_n;
wire    enableInput_val18_c_full_n;
wire   [7:0] enableInput_val18_c_dout;
wire   [2:0] enableInput_val18_c_num_data_valid;
wire   [2:0] enableInput_val18_c_fifo_cap;
wire    enableInput_val18_c_empty_n;
wire    colorFormat_val27_c20_full_n;
wire   [7:0] colorFormat_val27_c20_dout;
wire   [2:0] colorFormat_val27_c20_num_data_valid;
wire   [2:0] colorFormat_val27_c20_fifo_cap;
wire    colorFormat_val27_c20_empty_n;
wire    bckgndYUV_full_n;
wire   [23:0] bckgndYUV_dout;
wire   [4:0] bckgndYUV_num_data_valid;
wire   [4:0] bckgndYUV_fifo_cap;
wire    bckgndYUV_empty_n;
wire    height_val5_c14_full_n;
wire   [15:0] height_val5_c14_dout;
wire   [2:0] height_val5_c14_num_data_valid;
wire   [2:0] height_val5_c14_fifo_cap;
wire    height_val5_c14_empty_n;
wire    width_val10_c16_full_n;
wire   [15:0] width_val10_c16_dout;
wire   [2:0] width_val10_c16_num_data_valid;
wire   [2:0] width_val10_c16_fifo_cap;
wire    width_val10_c16_empty_n;
wire    motionSpeed_val23_c_full_n;
wire   [7:0] motionSpeed_val23_c_dout;
wire   [2:0] motionSpeed_val23_c_num_data_valid;
wire   [2:0] motionSpeed_val23_c_fifo_cap;
wire    motionSpeed_val23_c_empty_n;
wire    colorFormat_val27_c19_full_n;
wire   [7:0] colorFormat_val27_c19_dout;
wire   [2:0] colorFormat_val27_c19_num_data_valid;
wire   [2:0] colorFormat_val27_c19_fifo_cap;
wire    colorFormat_val27_c19_empty_n;
wire    ovrlayYUV_full_n;
wire   [23:0] ovrlayYUV_dout;
wire   [4:0] ovrlayYUV_num_data_valid;
wire   [4:0] ovrlayYUV_fifo_cap;
wire    ovrlayYUV_empty_n;
wire    height_val5_c_full_n;
wire   [9:0] height_val5_c_dout;
wire   [2:0] height_val5_c_num_data_valid;
wire   [2:0] height_val5_c_fifo_cap;
wire    height_val5_c_empty_n;
wire    width_val10_c_full_n;
wire   [10:0] width_val10_c_dout;
wire   [2:0] width_val10_c_num_data_valid;
wire   [2:0] width_val10_c_fifo_cap;
wire    width_val10_c_empty_n;
wire    colorFormat_val27_c_full_n;
wire   [7:0] colorFormat_val27_c_dout;
wire   [2:0] colorFormat_val27_c_num_data_valid;
wire   [2:0] colorFormat_val27_c_fifo_cap;
wire    colorFormat_val27_c_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready;
wire    ap_sync_AXIvideo2MultiPixStream_U0_ap_ready;
reg    ap_sync_reg_tpgBackground_U0_ap_ready;
wire    ap_sync_tpgBackground_U0_ap_ready;
wire   [0:0] start_for_tpgForeground_U0_din;
wire    start_for_tpgForeground_U0_full_n;
wire   [0:0] start_for_tpgForeground_U0_dout;
wire    start_for_tpgForeground_U0_empty_n;
wire   [0:0] start_for_MultiPixStream2AXIvideo_U0_din;
wire    start_for_MultiPixStream2AXIvideo_U0_full_n;
wire   [0:0] start_for_MultiPixStream2AXIvideo_U0_dout;
wire    start_for_MultiPixStream2AXIvideo_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready = 1'b0;
#0 ap_sync_reg_tpgBackground_U0_ap_ready = 1'b0;
end

design_1_v_tpg_0_0_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(entry_proc_U0_start_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .field_id_val11(field_id_val11),
    .field_id_val11_c_din(entry_proc_U0_field_id_val11_c_din),
    .field_id_val11_c_num_data_valid(field_id_val11_c_num_data_valid),
    .field_id_val11_c_fifo_cap(field_id_val11_c_fifo_cap),
    .field_id_val11_c_full_n(field_id_val11_c_full_n),
    .field_id_val11_c_write(entry_proc_U0_field_id_val11_c_write),
    .fid_in_val12(fid_in_val12),
    .fid_in_val12_c_din(entry_proc_U0_fid_in_val12_c_din),
    .fid_in_val12_c_num_data_valid(fid_in_val12_c_num_data_valid),
    .fid_in_val12_c_fifo_cap(fid_in_val12_c_fifo_cap),
    .fid_in_val12_c_full_n(fid_in_val12_c_full_n),
    .fid_in_val12_c_write(entry_proc_U0_fid_in_val12_c_write),
    .passthruStartX_val13(passthruStartX_val13),
    .passthruStartX_val13_c_din(entry_proc_U0_passthruStartX_val13_c_din),
    .passthruStartX_val13_c_num_data_valid(passthruStartX_val13_c_num_data_valid),
    .passthruStartX_val13_c_fifo_cap(passthruStartX_val13_c_fifo_cap),
    .passthruStartX_val13_c_full_n(passthruStartX_val13_c_full_n),
    .passthruStartX_val13_c_write(entry_proc_U0_passthruStartX_val13_c_write),
    .passthruStartY_val14(passthruStartY_val14),
    .passthruStartY_val14_c_din(entry_proc_U0_passthruStartY_val14_c_din),
    .passthruStartY_val14_c_num_data_valid(passthruStartY_val14_c_num_data_valid),
    .passthruStartY_val14_c_fifo_cap(passthruStartY_val14_c_fifo_cap),
    .passthruStartY_val14_c_full_n(passthruStartY_val14_c_full_n),
    .passthruStartY_val14_c_write(entry_proc_U0_passthruStartY_val14_c_write),
    .passthruEndX_val15(passthruEndX_val15),
    .passthruEndX_val15_c_din(entry_proc_U0_passthruEndX_val15_c_din),
    .passthruEndX_val15_c_num_data_valid(passthruEndX_val15_c_num_data_valid),
    .passthruEndX_val15_c_fifo_cap(passthruEndX_val15_c_fifo_cap),
    .passthruEndX_val15_c_full_n(passthruEndX_val15_c_full_n),
    .passthruEndX_val15_c_write(entry_proc_U0_passthruEndX_val15_c_write),
    .passthruEndY_val16(passthruEndY_val16),
    .passthruEndY_val16_c_din(entry_proc_U0_passthruEndY_val16_c_din),
    .passthruEndY_val16_c_num_data_valid(passthruEndY_val16_c_num_data_valid),
    .passthruEndY_val16_c_fifo_cap(passthruEndY_val16_c_fifo_cap),
    .passthruEndY_val16_c_full_n(passthruEndY_val16_c_full_n),
    .passthruEndY_val16_c_write(entry_proc_U0_passthruEndY_val16_c_write),
    .bckgndId_val19(bckgndId_val19),
    .bckgndId_val19_c_din(entry_proc_U0_bckgndId_val19_c_din),
    .bckgndId_val19_c_num_data_valid(bckgndId_val19_c_num_data_valid),
    .bckgndId_val19_c_fifo_cap(bckgndId_val19_c_fifo_cap),
    .bckgndId_val19_c_full_n(bckgndId_val19_c_full_n),
    .bckgndId_val19_c_write(entry_proc_U0_bckgndId_val19_c_write),
    .ovrlayId_val20(ovrlayId_val20),
    .ovrlayId_val20_c_din(entry_proc_U0_ovrlayId_val20_c_din),
    .ovrlayId_val20_c_num_data_valid(ovrlayId_val20_c_num_data_valid),
    .ovrlayId_val20_c_fifo_cap(ovrlayId_val20_c_fifo_cap),
    .ovrlayId_val20_c_full_n(ovrlayId_val20_c_full_n),
    .ovrlayId_val20_c_write(entry_proc_U0_ovrlayId_val20_c_write),
    .maskId_val21(maskId_val21),
    .maskId_val21_c_din(entry_proc_U0_maskId_val21_c_din),
    .maskId_val21_c_num_data_valid(maskId_val21_c_num_data_valid),
    .maskId_val21_c_fifo_cap(maskId_val21_c_fifo_cap),
    .maskId_val21_c_full_n(maskId_val21_c_full_n),
    .maskId_val21_c_write(entry_proc_U0_maskId_val21_c_write),
    .motionSpeed_val23(motionSpeed_val23),
    .motionSpeed_val23_c18_din(entry_proc_U0_motionSpeed_val23_c18_din),
    .motionSpeed_val23_c18_num_data_valid(motionSpeed_val23_c18_num_data_valid),
    .motionSpeed_val23_c18_fifo_cap(motionSpeed_val23_c18_fifo_cap),
    .motionSpeed_val23_c18_full_n(motionSpeed_val23_c18_full_n),
    .motionSpeed_val23_c18_write(entry_proc_U0_motionSpeed_val23_c18_write),
    .crossHairX_val28(crossHairX_val28),
    .crossHairX_val28_c_din(entry_proc_U0_crossHairX_val28_c_din),
    .crossHairX_val28_c_num_data_valid(crossHairX_val28_c_num_data_valid),
    .crossHairX_val28_c_fifo_cap(crossHairX_val28_c_fifo_cap),
    .crossHairX_val28_c_full_n(crossHairX_val28_c_full_n),
    .crossHairX_val28_c_write(entry_proc_U0_crossHairX_val28_c_write),
    .crossHairY_val29(crossHairY_val29),
    .crossHairY_val29_c_din(entry_proc_U0_crossHairY_val29_c_din),
    .crossHairY_val29_c_num_data_valid(crossHairY_val29_c_num_data_valid),
    .crossHairY_val29_c_fifo_cap(crossHairY_val29_c_fifo_cap),
    .crossHairY_val29_c_full_n(crossHairY_val29_c_full_n),
    .crossHairY_val29_c_write(entry_proc_U0_crossHairY_val29_c_write),
    .ZplateHorContStart_val30(ZplateHorContStart_val30),
    .ZplateHorContStart_val30_c_din(entry_proc_U0_ZplateHorContStart_val30_c_din),
    .ZplateHorContStart_val30_c_num_data_valid(ZplateHorContStart_val30_c_num_data_valid),
    .ZplateHorContStart_val30_c_fifo_cap(ZplateHorContStart_val30_c_fifo_cap),
    .ZplateHorContStart_val30_c_full_n(ZplateHorContStart_val30_c_full_n),
    .ZplateHorContStart_val30_c_write(entry_proc_U0_ZplateHorContStart_val30_c_write),
    .ZplateHorContDelta_val31(ZplateHorContDelta_val31),
    .ZplateHorContDelta_val31_c_din(entry_proc_U0_ZplateHorContDelta_val31_c_din),
    .ZplateHorContDelta_val31_c_num_data_valid(ZplateHorContDelta_val31_c_num_data_valid),
    .ZplateHorContDelta_val31_c_fifo_cap(ZplateHorContDelta_val31_c_fifo_cap),
    .ZplateHorContDelta_val31_c_full_n(ZplateHorContDelta_val31_c_full_n),
    .ZplateHorContDelta_val31_c_write(entry_proc_U0_ZplateHorContDelta_val31_c_write),
    .ZplateVerContStart_val32(ZplateVerContStart_val32),
    .ZplateVerContStart_val32_c_din(entry_proc_U0_ZplateVerContStart_val32_c_din),
    .ZplateVerContStart_val32_c_num_data_valid(ZplateVerContStart_val32_c_num_data_valid),
    .ZplateVerContStart_val32_c_fifo_cap(ZplateVerContStart_val32_c_fifo_cap),
    .ZplateVerContStart_val32_c_full_n(ZplateVerContStart_val32_c_full_n),
    .ZplateVerContStart_val32_c_write(entry_proc_U0_ZplateVerContStart_val32_c_write),
    .ZplateVerContDelta_val33(ZplateVerContDelta_val33),
    .ZplateVerContDelta_val33_c_din(entry_proc_U0_ZplateVerContDelta_val33_c_din),
    .ZplateVerContDelta_val33_c_num_data_valid(ZplateVerContDelta_val33_c_num_data_valid),
    .ZplateVerContDelta_val33_c_fifo_cap(ZplateVerContDelta_val33_c_fifo_cap),
    .ZplateVerContDelta_val33_c_full_n(ZplateVerContDelta_val33_c_full_n),
    .ZplateVerContDelta_val33_c_write(entry_proc_U0_ZplateVerContDelta_val33_c_write),
    .boxSize_val34(boxSize_val34),
    .boxSize_val34_c_din(entry_proc_U0_boxSize_val34_c_din),
    .boxSize_val34_c_num_data_valid(boxSize_val34_c_num_data_valid),
    .boxSize_val34_c_fifo_cap(boxSize_val34_c_fifo_cap),
    .boxSize_val34_c_full_n(boxSize_val34_c_full_n),
    .boxSize_val34_c_write(entry_proc_U0_boxSize_val34_c_write),
    .boxColorR_val35(boxColorR_val35),
    .boxColorR_val35_c_din(entry_proc_U0_boxColorR_val35_c_din),
    .boxColorR_val35_c_num_data_valid(boxColorR_val35_c_num_data_valid),
    .boxColorR_val35_c_fifo_cap(boxColorR_val35_c_fifo_cap),
    .boxColorR_val35_c_full_n(boxColorR_val35_c_full_n),
    .boxColorR_val35_c_write(entry_proc_U0_boxColorR_val35_c_write),
    .boxColorG_val36(boxColorG_val36),
    .boxColorG_val36_c_din(entry_proc_U0_boxColorG_val36_c_din),
    .boxColorG_val36_c_num_data_valid(boxColorG_val36_c_num_data_valid),
    .boxColorG_val36_c_fifo_cap(boxColorG_val36_c_fifo_cap),
    .boxColorG_val36_c_full_n(boxColorG_val36_c_full_n),
    .boxColorG_val36_c_write(entry_proc_U0_boxColorG_val36_c_write),
    .boxColorB_val37(boxColorB_val37),
    .boxColorB_val37_c_din(entry_proc_U0_boxColorB_val37_c_din),
    .boxColorB_val37_c_num_data_valid(boxColorB_val37_c_num_data_valid),
    .boxColorB_val37_c_fifo_cap(boxColorB_val37_c_fifo_cap),
    .boxColorB_val37_c_full_n(boxColorB_val37_c_full_n),
    .boxColorB_val37_c_write(entry_proc_U0_boxColorB_val37_c_write),
    .dpDynamicRange_val38(dpDynamicRange_val38),
    .dpDynamicRange_val38_c_din(entry_proc_U0_dpDynamicRange_val38_c_din),
    .dpDynamicRange_val38_c_num_data_valid(dpDynamicRange_val38_c_num_data_valid),
    .dpDynamicRange_val38_c_fifo_cap(dpDynamicRange_val38_c_fifo_cap),
    .dpDynamicRange_val38_c_full_n(dpDynamicRange_val38_c_full_n),
    .dpDynamicRange_val38_c_write(entry_proc_U0_dpDynamicRange_val38_c_write),
    .dpYUVCoef_val39(dpYUVCoef_val39),
    .dpYUVCoef_val39_c_din(entry_proc_U0_dpYUVCoef_val39_c_din),
    .dpYUVCoef_val39_c_num_data_valid(dpYUVCoef_val39_c_num_data_valid),
    .dpYUVCoef_val39_c_fifo_cap(dpYUVCoef_val39_c_fifo_cap),
    .dpYUVCoef_val39_c_full_n(dpYUVCoef_val39_c_full_n),
    .dpYUVCoef_val39_c_write(entry_proc_U0_dpYUVCoef_val39_c_write)
);

design_1_v_tpg_0_0_AXIvideo2MultiPixStream AXIvideo2MultiPixStream_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(AXIvideo2MultiPixStream_U0_ap_start),
    .ap_done(AXIvideo2MultiPixStream_U0_ap_done),
    .ap_continue(AXIvideo2MultiPixStream_U0_ap_continue),
    .ap_idle(AXIvideo2MultiPixStream_U0_ap_idle),
    .ap_ready(AXIvideo2MultiPixStream_U0_ap_ready),
    .s_axis_video_TDATA(s_axis_video_TDATA),
    .s_axis_video_TVALID(s_axis_video_TVALID),
    .s_axis_video_TREADY(AXIvideo2MultiPixStream_U0_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP),
    .s_axis_video_TSTRB(s_axis_video_TSTRB),
    .s_axis_video_TUSER(s_axis_video_TUSER),
    .s_axis_video_TLAST(s_axis_video_TLAST),
    .s_axis_video_TID(s_axis_video_TID),
    .s_axis_video_TDEST(s_axis_video_TDEST),
    .srcYUV_din(AXIvideo2MultiPixStream_U0_srcYUV_din),
    .srcYUV_num_data_valid(srcYUV_num_data_valid),
    .srcYUV_fifo_cap(srcYUV_fifo_cap),
    .srcYUV_full_n(srcYUV_full_n),
    .srcYUV_write(AXIvideo2MultiPixStream_U0_srcYUV_write),
    .enableInput_val(enableInput_val18),
    .Height_val(height_val5),
    .WidthIn_val(width_val10),
    .colorFormat_val(colorFormat_val27),
    .height_val5_c15_din(AXIvideo2MultiPixStream_U0_height_val5_c15_din),
    .height_val5_c15_num_data_valid(height_val5_c15_num_data_valid),
    .height_val5_c15_fifo_cap(height_val5_c15_fifo_cap),
    .height_val5_c15_full_n(height_val5_c15_full_n),
    .height_val5_c15_write(AXIvideo2MultiPixStream_U0_height_val5_c15_write),
    .width_val10_c17_din(AXIvideo2MultiPixStream_U0_width_val10_c17_din),
    .width_val10_c17_num_data_valid(width_val10_c17_num_data_valid),
    .width_val10_c17_fifo_cap(width_val10_c17_fifo_cap),
    .width_val10_c17_full_n(width_val10_c17_full_n),
    .width_val10_c17_write(AXIvideo2MultiPixStream_U0_width_val10_c17_write),
    .enableInput_val18_c_din(AXIvideo2MultiPixStream_U0_enableInput_val18_c_din),
    .enableInput_val18_c_num_data_valid(enableInput_val18_c_num_data_valid),
    .enableInput_val18_c_fifo_cap(enableInput_val18_c_fifo_cap),
    .enableInput_val18_c_full_n(enableInput_val18_c_full_n),
    .enableInput_val18_c_write(AXIvideo2MultiPixStream_U0_enableInput_val18_c_write),
    .colorFormat_val27_c20_din(AXIvideo2MultiPixStream_U0_colorFormat_val27_c20_din),
    .colorFormat_val27_c20_num_data_valid(colorFormat_val27_c20_num_data_valid),
    .colorFormat_val27_c20_fifo_cap(colorFormat_val27_c20_fifo_cap),
    .colorFormat_val27_c20_full_n(colorFormat_val27_c20_full_n),
    .colorFormat_val27_c20_write(AXIvideo2MultiPixStream_U0_colorFormat_val27_c20_write)
);

design_1_v_tpg_0_0_tpgBackground tpgBackground_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(tpgBackground_U0_ap_start),
    .ap_done(tpgBackground_U0_ap_done),
    .ap_continue(tpgBackground_U0_ap_continue),
    .ap_idle(tpgBackground_U0_ap_idle),
    .ap_ready(tpgBackground_U0_ap_ready),
    .srcYUV_dout(srcYUV_dout),
    .srcYUV_num_data_valid(srcYUV_num_data_valid),
    .srcYUV_fifo_cap(srcYUV_fifo_cap),
    .srcYUV_empty_n(srcYUV_empty_n),
    .srcYUV_read(tpgBackground_U0_srcYUV_read),
    .height_val_dout(height_val5_c15_dout),
    .height_val_num_data_valid(height_val5_c15_num_data_valid),
    .height_val_fifo_cap(height_val5_c15_fifo_cap),
    .height_val_empty_n(height_val5_c15_empty_n),
    .height_val_read(tpgBackground_U0_height_val_read),
    .width_val_dout(width_val10_c17_dout),
    .width_val_num_data_valid(width_val10_c17_num_data_valid),
    .width_val_fifo_cap(width_val10_c17_fifo_cap),
    .width_val_empty_n(width_val10_c17_empty_n),
    .width_val_read(tpgBackground_U0_width_val_read),
    .passthruStartX_val_dout(passthruStartX_val13_c_dout),
    .passthruStartX_val_num_data_valid(passthruStartX_val13_c_num_data_valid),
    .passthruStartX_val_fifo_cap(passthruStartX_val13_c_fifo_cap),
    .passthruStartX_val_empty_n(passthruStartX_val13_c_empty_n),
    .passthruStartX_val_read(tpgBackground_U0_passthruStartX_val_read),
    .passthruStartY_val_dout(passthruStartY_val14_c_dout),
    .passthruStartY_val_num_data_valid(passthruStartY_val14_c_num_data_valid),
    .passthruStartY_val_fifo_cap(passthruStartY_val14_c_fifo_cap),
    .passthruStartY_val_empty_n(passthruStartY_val14_c_empty_n),
    .passthruStartY_val_read(tpgBackground_U0_passthruStartY_val_read),
    .passthruEndX_val_dout(passthruEndX_val15_c_dout),
    .passthruEndX_val_num_data_valid(passthruEndX_val15_c_num_data_valid),
    .passthruEndX_val_fifo_cap(passthruEndX_val15_c_fifo_cap),
    .passthruEndX_val_empty_n(passthruEndX_val15_c_empty_n),
    .passthruEndX_val_read(tpgBackground_U0_passthruEndX_val_read),
    .passthruEndY_val_dout(passthruEndY_val16_c_dout),
    .passthruEndY_val_num_data_valid(passthruEndY_val16_c_num_data_valid),
    .passthruEndY_val_fifo_cap(passthruEndY_val16_c_fifo_cap),
    .passthruEndY_val_empty_n(passthruEndY_val16_c_empty_n),
    .passthruEndY_val_read(tpgBackground_U0_passthruEndY_val_read),
    .enableInput_val_dout(enableInput_val18_c_dout),
    .enableInput_val_num_data_valid(enableInput_val18_c_num_data_valid),
    .enableInput_val_fifo_cap(enableInput_val18_c_fifo_cap),
    .enableInput_val_empty_n(enableInput_val18_c_empty_n),
    .enableInput_val_read(tpgBackground_U0_enableInput_val_read),
    .patternId_val_dout(bckgndId_val19_c_dout),
    .patternId_val_num_data_valid(bckgndId_val19_c_num_data_valid),
    .patternId_val_fifo_cap(bckgndId_val19_c_fifo_cap),
    .patternId_val_empty_n(bckgndId_val19_c_empty_n),
    .patternId_val_read(tpgBackground_U0_patternId_val_read),
    .ZplateHorContStart_val_dout(ZplateHorContStart_val30_c_dout),
    .ZplateHorContStart_val_num_data_valid(ZplateHorContStart_val30_c_num_data_valid),
    .ZplateHorContStart_val_fifo_cap(ZplateHorContStart_val30_c_fifo_cap),
    .ZplateHorContStart_val_empty_n(ZplateHorContStart_val30_c_empty_n),
    .ZplateHorContStart_val_read(tpgBackground_U0_ZplateHorContStart_val_read),
    .ZplateHorContDelta_val_dout(ZplateHorContDelta_val31_c_dout),
    .ZplateHorContDelta_val_num_data_valid(ZplateHorContDelta_val31_c_num_data_valid),
    .ZplateHorContDelta_val_fifo_cap(ZplateHorContDelta_val31_c_fifo_cap),
    .ZplateHorContDelta_val_empty_n(ZplateHorContDelta_val31_c_empty_n),
    .ZplateHorContDelta_val_read(tpgBackground_U0_ZplateHorContDelta_val_read),
    .ZplateVerContStart_val_dout(ZplateVerContStart_val32_c_dout),
    .ZplateVerContStart_val_num_data_valid(ZplateVerContStart_val32_c_num_data_valid),
    .ZplateVerContStart_val_fifo_cap(ZplateVerContStart_val32_c_fifo_cap),
    .ZplateVerContStart_val_empty_n(ZplateVerContStart_val32_c_empty_n),
    .ZplateVerContStart_val_read(tpgBackground_U0_ZplateVerContStart_val_read),
    .ZplateVerContDelta_val_dout(ZplateVerContDelta_val33_c_dout),
    .ZplateVerContDelta_val_num_data_valid(ZplateVerContDelta_val33_c_num_data_valid),
    .ZplateVerContDelta_val_fifo_cap(ZplateVerContDelta_val33_c_fifo_cap),
    .ZplateVerContDelta_val_empty_n(ZplateVerContDelta_val33_c_empty_n),
    .ZplateVerContDelta_val_read(tpgBackground_U0_ZplateVerContDelta_val_read),
    .dpDynamicRange_val_dout(dpDynamicRange_val38_c_dout),
    .dpDynamicRange_val_num_data_valid(dpDynamicRange_val38_c_num_data_valid),
    .dpDynamicRange_val_fifo_cap(dpDynamicRange_val38_c_fifo_cap),
    .dpDynamicRange_val_empty_n(dpDynamicRange_val38_c_empty_n),
    .dpDynamicRange_val_read(tpgBackground_U0_dpDynamicRange_val_read),
    .dpYUVCoef_val_dout(dpYUVCoef_val39_c_dout),
    .dpYUVCoef_val_num_data_valid(dpYUVCoef_val39_c_num_data_valid),
    .dpYUVCoef_val_fifo_cap(dpYUVCoef_val39_c_fifo_cap),
    .dpYUVCoef_val_empty_n(dpYUVCoef_val39_c_empty_n),
    .dpYUVCoef_val_read(tpgBackground_U0_dpYUVCoef_val_read),
    .motionSpeed_val_dout(motionSpeed_val23_c18_dout),
    .motionSpeed_val_num_data_valid(motionSpeed_val23_c18_num_data_valid),
    .motionSpeed_val_fifo_cap(motionSpeed_val23_c18_fifo_cap),
    .motionSpeed_val_empty_n(motionSpeed_val23_c18_empty_n),
    .motionSpeed_val_read(tpgBackground_U0_motionSpeed_val_read),
    .colorFormat_val_dout(colorFormat_val27_c20_dout),
    .colorFormat_val_num_data_valid(colorFormat_val27_c20_num_data_valid),
    .colorFormat_val_fifo_cap(colorFormat_val27_c20_fifo_cap),
    .colorFormat_val_empty_n(colorFormat_val27_c20_empty_n),
    .colorFormat_val_read(tpgBackground_U0_colorFormat_val_read),
    .bckgndYUV_din(tpgBackground_U0_bckgndYUV_din),
    .bckgndYUV_num_data_valid(bckgndYUV_num_data_valid),
    .bckgndYUV_fifo_cap(bckgndYUV_fifo_cap),
    .bckgndYUV_full_n(bckgndYUV_full_n),
    .bckgndYUV_write(tpgBackground_U0_bckgndYUV_write),
    .height_val5_c14_din(tpgBackground_U0_height_val5_c14_din),
    .height_val5_c14_num_data_valid(height_val5_c14_num_data_valid),
    .height_val5_c14_fifo_cap(height_val5_c14_fifo_cap),
    .height_val5_c14_full_n(height_val5_c14_full_n),
    .height_val5_c14_write(tpgBackground_U0_height_val5_c14_write),
    .width_val10_c16_din(tpgBackground_U0_width_val10_c16_din),
    .width_val10_c16_num_data_valid(width_val10_c16_num_data_valid),
    .width_val10_c16_fifo_cap(width_val10_c16_fifo_cap),
    .width_val10_c16_full_n(width_val10_c16_full_n),
    .width_val10_c16_write(tpgBackground_U0_width_val10_c16_write),
    .motionSpeed_val23_c_din(tpgBackground_U0_motionSpeed_val23_c_din),
    .motionSpeed_val23_c_num_data_valid(motionSpeed_val23_c_num_data_valid),
    .motionSpeed_val23_c_fifo_cap(motionSpeed_val23_c_fifo_cap),
    .motionSpeed_val23_c_full_n(motionSpeed_val23_c_full_n),
    .motionSpeed_val23_c_write(tpgBackground_U0_motionSpeed_val23_c_write),
    .colorFormat_val27_c19_din(tpgBackground_U0_colorFormat_val27_c19_din),
    .colorFormat_val27_c19_num_data_valid(colorFormat_val27_c19_num_data_valid),
    .colorFormat_val27_c19_fifo_cap(colorFormat_val27_c19_fifo_cap),
    .colorFormat_val27_c19_full_n(colorFormat_val27_c19_full_n),
    .colorFormat_val27_c19_write(tpgBackground_U0_colorFormat_val27_c19_write),
    .s(s)
);

design_1_v_tpg_0_0_tpgForeground tpgForeground_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(tpgForeground_U0_ap_start),
    .ap_done(tpgForeground_U0_ap_done),
    .ap_continue(tpgForeground_U0_ap_continue),
    .ap_idle(tpgForeground_U0_ap_idle),
    .ap_ready(tpgForeground_U0_ap_ready),
    .bckgndYUV_dout(bckgndYUV_dout),
    .bckgndYUV_num_data_valid(bckgndYUV_num_data_valid),
    .bckgndYUV_fifo_cap(bckgndYUV_fifo_cap),
    .bckgndYUV_empty_n(bckgndYUV_empty_n),
    .bckgndYUV_read(tpgForeground_U0_bckgndYUV_read),
    .height_val_dout(height_val5_c14_dout),
    .height_val_num_data_valid(height_val5_c14_num_data_valid),
    .height_val_fifo_cap(height_val5_c14_fifo_cap),
    .height_val_empty_n(height_val5_c14_empty_n),
    .height_val_read(tpgForeground_U0_height_val_read),
    .width_val_dout(width_val10_c16_dout),
    .width_val_num_data_valid(width_val10_c16_num_data_valid),
    .width_val_fifo_cap(width_val10_c16_fifo_cap),
    .width_val_empty_n(width_val10_c16_empty_n),
    .width_val_read(tpgForeground_U0_width_val_read),
    .patternId_val_dout(ovrlayId_val20_c_dout),
    .patternId_val_num_data_valid(ovrlayId_val20_c_num_data_valid),
    .patternId_val_fifo_cap(ovrlayId_val20_c_fifo_cap),
    .patternId_val_empty_n(ovrlayId_val20_c_empty_n),
    .patternId_val_read(tpgForeground_U0_patternId_val_read),
    .maskId_val_dout(maskId_val21_c_dout),
    .maskId_val_num_data_valid(maskId_val21_c_num_data_valid),
    .maskId_val_fifo_cap(maskId_val21_c_fifo_cap),
    .maskId_val_empty_n(maskId_val21_c_empty_n),
    .maskId_val_read(tpgForeground_U0_maskId_val_read),
    .colorFormat_val_dout(colorFormat_val27_c19_dout),
    .colorFormat_val_num_data_valid(colorFormat_val27_c19_num_data_valid),
    .colorFormat_val_fifo_cap(colorFormat_val27_c19_fifo_cap),
    .colorFormat_val_empty_n(colorFormat_val27_c19_empty_n),
    .colorFormat_val_read(tpgForeground_U0_colorFormat_val_read),
    .crossHairX_val_dout(crossHairX_val28_c_dout),
    .crossHairX_val_num_data_valid(crossHairX_val28_c_num_data_valid),
    .crossHairX_val_fifo_cap(crossHairX_val28_c_fifo_cap),
    .crossHairX_val_empty_n(crossHairX_val28_c_empty_n),
    .crossHairX_val_read(tpgForeground_U0_crossHairX_val_read),
    .crossHairY_val_dout(crossHairY_val29_c_dout),
    .crossHairY_val_num_data_valid(crossHairY_val29_c_num_data_valid),
    .crossHairY_val_fifo_cap(crossHairY_val29_c_fifo_cap),
    .crossHairY_val_empty_n(crossHairY_val29_c_empty_n),
    .crossHairY_val_read(tpgForeground_U0_crossHairY_val_read),
    .boxSize_val_dout(boxSize_val34_c_dout),
    .boxSize_val_num_data_valid(boxSize_val34_c_num_data_valid),
    .boxSize_val_fifo_cap(boxSize_val34_c_fifo_cap),
    .boxSize_val_empty_n(boxSize_val34_c_empty_n),
    .boxSize_val_read(tpgForeground_U0_boxSize_val_read),
    .boxColorR_val_dout(boxColorR_val35_c_dout),
    .boxColorR_val_num_data_valid(boxColorR_val35_c_num_data_valid),
    .boxColorR_val_fifo_cap(boxColorR_val35_c_fifo_cap),
    .boxColorR_val_empty_n(boxColorR_val35_c_empty_n),
    .boxColorR_val_read(tpgForeground_U0_boxColorR_val_read),
    .boxColorG_val_dout(boxColorG_val36_c_dout),
    .boxColorG_val_num_data_valid(boxColorG_val36_c_num_data_valid),
    .boxColorG_val_fifo_cap(boxColorG_val36_c_fifo_cap),
    .boxColorG_val_empty_n(boxColorG_val36_c_empty_n),
    .boxColorG_val_read(tpgForeground_U0_boxColorG_val_read),
    .boxColorB_val_dout(boxColorB_val37_c_dout),
    .boxColorB_val_num_data_valid(boxColorB_val37_c_num_data_valid),
    .boxColorB_val_fifo_cap(boxColorB_val37_c_fifo_cap),
    .boxColorB_val_empty_n(boxColorB_val37_c_empty_n),
    .boxColorB_val_read(tpgForeground_U0_boxColorB_val_read),
    .motionSpeed_val_dout(motionSpeed_val23_c_dout),
    .motionSpeed_val_num_data_valid(motionSpeed_val23_c_num_data_valid),
    .motionSpeed_val_fifo_cap(motionSpeed_val23_c_fifo_cap),
    .motionSpeed_val_empty_n(motionSpeed_val23_c_empty_n),
    .motionSpeed_val_read(tpgForeground_U0_motionSpeed_val_read),
    .ovrlayYUV_din(tpgForeground_U0_ovrlayYUV_din),
    .ovrlayYUV_num_data_valid(ovrlayYUV_num_data_valid),
    .ovrlayYUV_fifo_cap(ovrlayYUV_fifo_cap),
    .ovrlayYUV_full_n(ovrlayYUV_full_n),
    .ovrlayYUV_write(tpgForeground_U0_ovrlayYUV_write),
    .height_val5_c_din(tpgForeground_U0_height_val5_c_din),
    .height_val5_c_num_data_valid(height_val5_c_num_data_valid),
    .height_val5_c_fifo_cap(height_val5_c_fifo_cap),
    .height_val5_c_full_n(height_val5_c_full_n),
    .height_val5_c_write(tpgForeground_U0_height_val5_c_write),
    .width_val10_c_din(tpgForeground_U0_width_val10_c_din),
    .width_val10_c_num_data_valid(width_val10_c_num_data_valid),
    .width_val10_c_fifo_cap(width_val10_c_fifo_cap),
    .width_val10_c_full_n(width_val10_c_full_n),
    .width_val10_c_write(tpgForeground_U0_width_val10_c_write),
    .colorFormat_val27_c_din(tpgForeground_U0_colorFormat_val27_c_din),
    .colorFormat_val27_c_num_data_valid(colorFormat_val27_c_num_data_valid),
    .colorFormat_val27_c_fifo_cap(colorFormat_val27_c_fifo_cap),
    .colorFormat_val27_c_full_n(colorFormat_val27_c_full_n),
    .colorFormat_val27_c_write(tpgForeground_U0_colorFormat_val27_c_write)
);

design_1_v_tpg_0_0_MultiPixStream2AXIvideo MultiPixStream2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(MultiPixStream2AXIvideo_U0_ap_start),
    .ap_done(MultiPixStream2AXIvideo_U0_ap_done),
    .ap_continue(MultiPixStream2AXIvideo_U0_ap_continue),
    .ap_idle(MultiPixStream2AXIvideo_U0_ap_idle),
    .ap_ready(MultiPixStream2AXIvideo_U0_ap_ready),
    .ovrlayYUV_dout(ovrlayYUV_dout),
    .ovrlayYUV_num_data_valid(ovrlayYUV_num_data_valid),
    .ovrlayYUV_fifo_cap(ovrlayYUV_fifo_cap),
    .ovrlayYUV_empty_n(ovrlayYUV_empty_n),
    .ovrlayYUV_read(MultiPixStream2AXIvideo_U0_ovrlayYUV_read),
    .m_axis_video_TDATA(MultiPixStream2AXIvideo_U0_m_axis_video_TDATA),
    .m_axis_video_TVALID(MultiPixStream2AXIvideo_U0_m_axis_video_TVALID),
    .m_axis_video_TREADY(m_axis_video_TREADY),
    .m_axis_video_TKEEP(MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP),
    .m_axis_video_TSTRB(MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB),
    .m_axis_video_TUSER(MultiPixStream2AXIvideo_U0_m_axis_video_TUSER),
    .m_axis_video_TLAST(MultiPixStream2AXIvideo_U0_m_axis_video_TLAST),
    .m_axis_video_TID(MultiPixStream2AXIvideo_U0_m_axis_video_TID),
    .m_axis_video_TDEST(MultiPixStream2AXIvideo_U0_m_axis_video_TDEST),
    .height_val5_dout(height_val5_c_dout),
    .height_val5_num_data_valid(height_val5_c_num_data_valid),
    .height_val5_fifo_cap(height_val5_c_fifo_cap),
    .height_val5_empty_n(height_val5_c_empty_n),
    .height_val5_read(MultiPixStream2AXIvideo_U0_height_val5_read),
    .width_val10_dout(width_val10_c_dout),
    .width_val10_num_data_valid(width_val10_c_num_data_valid),
    .width_val10_fifo_cap(width_val10_c_fifo_cap),
    .width_val10_empty_n(width_val10_c_empty_n),
    .width_val10_read(MultiPixStream2AXIvideo_U0_width_val10_read),
    .colorFormat_val27_dout(colorFormat_val27_c_dout),
    .colorFormat_val27_num_data_valid(colorFormat_val27_c_num_data_valid),
    .colorFormat_val27_fifo_cap(colorFormat_val27_c_fifo_cap),
    .colorFormat_val27_empty_n(colorFormat_val27_c_empty_n),
    .colorFormat_val27_read(MultiPixStream2AXIvideo_U0_colorFormat_val27_read),
    .fid_in_val12_dout(fid_in_val12_c_dout),
    .fid_in_val12_num_data_valid(fid_in_val12_c_num_data_valid),
    .fid_in_val12_fifo_cap(fid_in_val12_c_fifo_cap),
    .fid_in_val12_empty_n(fid_in_val12_c_empty_n),
    .fid_in_val12_read(MultiPixStream2AXIvideo_U0_fid_in_val12_read),
    .fid(MultiPixStream2AXIvideo_U0_fid),
    .fid_ap_vld(MultiPixStream2AXIvideo_U0_fid_ap_vld),
    .field_id_val11_dout(field_id_val11_c_dout),
    .field_id_val11_num_data_valid(field_id_val11_c_num_data_valid),
    .field_id_val11_fifo_cap(field_id_val11_c_fifo_cap),
    .field_id_val11_empty_n(field_id_val11_c_empty_n),
    .field_id_val11_read(MultiPixStream2AXIvideo_U0_field_id_val11_read)
);

design_1_v_tpg_0_0_fifo_w16_d5_S field_id_val11_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_field_id_val11_c_din),
    .if_full_n(field_id_val11_c_full_n),
    .if_write(entry_proc_U0_field_id_val11_c_write),
    .if_dout(field_id_val11_c_dout),
    .if_num_data_valid(field_id_val11_c_num_data_valid),
    .if_fifo_cap(field_id_val11_c_fifo_cap),
    .if_empty_n(field_id_val11_c_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_field_id_val11_read)
);

design_1_v_tpg_0_0_fifo_w1_d5_S fid_in_val12_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_fid_in_val12_c_din),
    .if_full_n(fid_in_val12_c_full_n),
    .if_write(entry_proc_U0_fid_in_val12_c_write),
    .if_dout(fid_in_val12_c_dout),
    .if_num_data_valid(fid_in_val12_c_num_data_valid),
    .if_fifo_cap(fid_in_val12_c_fifo_cap),
    .if_empty_n(fid_in_val12_c_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_fid_in_val12_read)
);

design_1_v_tpg_0_0_fifo_w16_d3_S passthruStartX_val13_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_passthruStartX_val13_c_din),
    .if_full_n(passthruStartX_val13_c_full_n),
    .if_write(entry_proc_U0_passthruStartX_val13_c_write),
    .if_dout(passthruStartX_val13_c_dout),
    .if_num_data_valid(passthruStartX_val13_c_num_data_valid),
    .if_fifo_cap(passthruStartX_val13_c_fifo_cap),
    .if_empty_n(passthruStartX_val13_c_empty_n),
    .if_read(tpgBackground_U0_passthruStartX_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d3_S passthruStartY_val14_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_passthruStartY_val14_c_din),
    .if_full_n(passthruStartY_val14_c_full_n),
    .if_write(entry_proc_U0_passthruStartY_val14_c_write),
    .if_dout(passthruStartY_val14_c_dout),
    .if_num_data_valid(passthruStartY_val14_c_num_data_valid),
    .if_fifo_cap(passthruStartY_val14_c_fifo_cap),
    .if_empty_n(passthruStartY_val14_c_empty_n),
    .if_read(tpgBackground_U0_passthruStartY_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d3_S passthruEndX_val15_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_passthruEndX_val15_c_din),
    .if_full_n(passthruEndX_val15_c_full_n),
    .if_write(entry_proc_U0_passthruEndX_val15_c_write),
    .if_dout(passthruEndX_val15_c_dout),
    .if_num_data_valid(passthruEndX_val15_c_num_data_valid),
    .if_fifo_cap(passthruEndX_val15_c_fifo_cap),
    .if_empty_n(passthruEndX_val15_c_empty_n),
    .if_read(tpgBackground_U0_passthruEndX_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d3_S passthruEndY_val16_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_passthruEndY_val16_c_din),
    .if_full_n(passthruEndY_val16_c_full_n),
    .if_write(entry_proc_U0_passthruEndY_val16_c_write),
    .if_dout(passthruEndY_val16_c_dout),
    .if_num_data_valid(passthruEndY_val16_c_num_data_valid),
    .if_fifo_cap(passthruEndY_val16_c_fifo_cap),
    .if_empty_n(passthruEndY_val16_c_empty_n),
    .if_read(tpgBackground_U0_passthruEndY_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d3_S bckgndId_val19_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_bckgndId_val19_c_din),
    .if_full_n(bckgndId_val19_c_full_n),
    .if_write(entry_proc_U0_bckgndId_val19_c_write),
    .if_dout(bckgndId_val19_c_dout),
    .if_num_data_valid(bckgndId_val19_c_num_data_valid),
    .if_fifo_cap(bckgndId_val19_c_fifo_cap),
    .if_empty_n(bckgndId_val19_c_empty_n),
    .if_read(tpgBackground_U0_patternId_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d4_S ovrlayId_val20_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_ovrlayId_val20_c_din),
    .if_full_n(ovrlayId_val20_c_full_n),
    .if_write(entry_proc_U0_ovrlayId_val20_c_write),
    .if_dout(ovrlayId_val20_c_dout),
    .if_num_data_valid(ovrlayId_val20_c_num_data_valid),
    .if_fifo_cap(ovrlayId_val20_c_fifo_cap),
    .if_empty_n(ovrlayId_val20_c_empty_n),
    .if_read(tpgForeground_U0_patternId_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d4_S maskId_val21_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_maskId_val21_c_din),
    .if_full_n(maskId_val21_c_full_n),
    .if_write(entry_proc_U0_maskId_val21_c_write),
    .if_dout(maskId_val21_c_dout),
    .if_num_data_valid(maskId_val21_c_num_data_valid),
    .if_fifo_cap(maskId_val21_c_fifo_cap),
    .if_empty_n(maskId_val21_c_empty_n),
    .if_read(tpgForeground_U0_maskId_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d3_S motionSpeed_val23_c18_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_motionSpeed_val23_c18_din),
    .if_full_n(motionSpeed_val23_c18_full_n),
    .if_write(entry_proc_U0_motionSpeed_val23_c18_write),
    .if_dout(motionSpeed_val23_c18_dout),
    .if_num_data_valid(motionSpeed_val23_c18_num_data_valid),
    .if_fifo_cap(motionSpeed_val23_c18_fifo_cap),
    .if_empty_n(motionSpeed_val23_c18_empty_n),
    .if_read(tpgBackground_U0_motionSpeed_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d4_S crossHairX_val28_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_crossHairX_val28_c_din),
    .if_full_n(crossHairX_val28_c_full_n),
    .if_write(entry_proc_U0_crossHairX_val28_c_write),
    .if_dout(crossHairX_val28_c_dout),
    .if_num_data_valid(crossHairX_val28_c_num_data_valid),
    .if_fifo_cap(crossHairX_val28_c_fifo_cap),
    .if_empty_n(crossHairX_val28_c_empty_n),
    .if_read(tpgForeground_U0_crossHairX_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d4_S crossHairY_val29_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_crossHairY_val29_c_din),
    .if_full_n(crossHairY_val29_c_full_n),
    .if_write(entry_proc_U0_crossHairY_val29_c_write),
    .if_dout(crossHairY_val29_c_dout),
    .if_num_data_valid(crossHairY_val29_c_num_data_valid),
    .if_fifo_cap(crossHairY_val29_c_fifo_cap),
    .if_empty_n(crossHairY_val29_c_empty_n),
    .if_read(tpgForeground_U0_crossHairY_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d3_S ZplateHorContStart_val30_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_ZplateHorContStart_val30_c_din),
    .if_full_n(ZplateHorContStart_val30_c_full_n),
    .if_write(entry_proc_U0_ZplateHorContStart_val30_c_write),
    .if_dout(ZplateHorContStart_val30_c_dout),
    .if_num_data_valid(ZplateHorContStart_val30_c_num_data_valid),
    .if_fifo_cap(ZplateHorContStart_val30_c_fifo_cap),
    .if_empty_n(ZplateHorContStart_val30_c_empty_n),
    .if_read(tpgBackground_U0_ZplateHorContStart_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d3_S ZplateHorContDelta_val31_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_ZplateHorContDelta_val31_c_din),
    .if_full_n(ZplateHorContDelta_val31_c_full_n),
    .if_write(entry_proc_U0_ZplateHorContDelta_val31_c_write),
    .if_dout(ZplateHorContDelta_val31_c_dout),
    .if_num_data_valid(ZplateHorContDelta_val31_c_num_data_valid),
    .if_fifo_cap(ZplateHorContDelta_val31_c_fifo_cap),
    .if_empty_n(ZplateHorContDelta_val31_c_empty_n),
    .if_read(tpgBackground_U0_ZplateHorContDelta_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d3_S ZplateVerContStart_val32_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_ZplateVerContStart_val32_c_din),
    .if_full_n(ZplateVerContStart_val32_c_full_n),
    .if_write(entry_proc_U0_ZplateVerContStart_val32_c_write),
    .if_dout(ZplateVerContStart_val32_c_dout),
    .if_num_data_valid(ZplateVerContStart_val32_c_num_data_valid),
    .if_fifo_cap(ZplateVerContStart_val32_c_fifo_cap),
    .if_empty_n(ZplateVerContStart_val32_c_empty_n),
    .if_read(tpgBackground_U0_ZplateVerContStart_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d3_S ZplateVerContDelta_val33_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_ZplateVerContDelta_val33_c_din),
    .if_full_n(ZplateVerContDelta_val33_c_full_n),
    .if_write(entry_proc_U0_ZplateVerContDelta_val33_c_write),
    .if_dout(ZplateVerContDelta_val33_c_dout),
    .if_num_data_valid(ZplateVerContDelta_val33_c_num_data_valid),
    .if_fifo_cap(ZplateVerContDelta_val33_c_fifo_cap),
    .if_empty_n(ZplateVerContDelta_val33_c_empty_n),
    .if_read(tpgBackground_U0_ZplateVerContDelta_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d4_S boxSize_val34_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_boxSize_val34_c_din),
    .if_full_n(boxSize_val34_c_full_n),
    .if_write(entry_proc_U0_boxSize_val34_c_write),
    .if_dout(boxSize_val34_c_dout),
    .if_num_data_valid(boxSize_val34_c_num_data_valid),
    .if_fifo_cap(boxSize_val34_c_fifo_cap),
    .if_empty_n(boxSize_val34_c_empty_n),
    .if_read(tpgForeground_U0_boxSize_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d4_S boxColorR_val35_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_boxColorR_val35_c_din),
    .if_full_n(boxColorR_val35_c_full_n),
    .if_write(entry_proc_U0_boxColorR_val35_c_write),
    .if_dout(boxColorR_val35_c_dout),
    .if_num_data_valid(boxColorR_val35_c_num_data_valid),
    .if_fifo_cap(boxColorR_val35_c_fifo_cap),
    .if_empty_n(boxColorR_val35_c_empty_n),
    .if_read(tpgForeground_U0_boxColorR_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d4_S boxColorG_val36_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_boxColorG_val36_c_din),
    .if_full_n(boxColorG_val36_c_full_n),
    .if_write(entry_proc_U0_boxColorG_val36_c_write),
    .if_dout(boxColorG_val36_c_dout),
    .if_num_data_valid(boxColorG_val36_c_num_data_valid),
    .if_fifo_cap(boxColorG_val36_c_fifo_cap),
    .if_empty_n(boxColorG_val36_c_empty_n),
    .if_read(tpgForeground_U0_boxColorG_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d4_S boxColorB_val37_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_boxColorB_val37_c_din),
    .if_full_n(boxColorB_val37_c_full_n),
    .if_write(entry_proc_U0_boxColorB_val37_c_write),
    .if_dout(boxColorB_val37_c_dout),
    .if_num_data_valid(boxColorB_val37_c_num_data_valid),
    .if_fifo_cap(boxColorB_val37_c_fifo_cap),
    .if_empty_n(boxColorB_val37_c_empty_n),
    .if_read(tpgForeground_U0_boxColorB_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d3_S dpDynamicRange_val38_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_dpDynamicRange_val38_c_din),
    .if_full_n(dpDynamicRange_val38_c_full_n),
    .if_write(entry_proc_U0_dpDynamicRange_val38_c_write),
    .if_dout(dpDynamicRange_val38_c_dout),
    .if_num_data_valid(dpDynamicRange_val38_c_num_data_valid),
    .if_fifo_cap(dpDynamicRange_val38_c_fifo_cap),
    .if_empty_n(dpDynamicRange_val38_c_empty_n),
    .if_read(tpgBackground_U0_dpDynamicRange_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d3_S dpYUVCoef_val39_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_dpYUVCoef_val39_c_din),
    .if_full_n(dpYUVCoef_val39_c_full_n),
    .if_write(entry_proc_U0_dpYUVCoef_val39_c_write),
    .if_dout(dpYUVCoef_val39_c_dout),
    .if_num_data_valid(dpYUVCoef_val39_c_num_data_valid),
    .if_fifo_cap(dpYUVCoef_val39_c_fifo_cap),
    .if_empty_n(dpYUVCoef_val39_c_empty_n),
    .if_read(tpgBackground_U0_dpYUVCoef_val_read)
);

design_1_v_tpg_0_0_fifo_w24_d16_S srcYUV_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2MultiPixStream_U0_srcYUV_din),
    .if_full_n(srcYUV_full_n),
    .if_write(AXIvideo2MultiPixStream_U0_srcYUV_write),
    .if_dout(srcYUV_dout),
    .if_num_data_valid(srcYUV_num_data_valid),
    .if_fifo_cap(srcYUV_fifo_cap),
    .if_empty_n(srcYUV_empty_n),
    .if_read(tpgBackground_U0_srcYUV_read)
);

design_1_v_tpg_0_0_fifo_w16_d2_S height_val5_c15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2MultiPixStream_U0_height_val5_c15_din),
    .if_full_n(height_val5_c15_full_n),
    .if_write(AXIvideo2MultiPixStream_U0_height_val5_c15_write),
    .if_dout(height_val5_c15_dout),
    .if_num_data_valid(height_val5_c15_num_data_valid),
    .if_fifo_cap(height_val5_c15_fifo_cap),
    .if_empty_n(height_val5_c15_empty_n),
    .if_read(tpgBackground_U0_height_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d2_S width_val10_c17_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2MultiPixStream_U0_width_val10_c17_din),
    .if_full_n(width_val10_c17_full_n),
    .if_write(AXIvideo2MultiPixStream_U0_width_val10_c17_write),
    .if_dout(width_val10_c17_dout),
    .if_num_data_valid(width_val10_c17_num_data_valid),
    .if_fifo_cap(width_val10_c17_fifo_cap),
    .if_empty_n(width_val10_c17_empty_n),
    .if_read(tpgBackground_U0_width_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d2_S enableInput_val18_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2MultiPixStream_U0_enableInput_val18_c_din),
    .if_full_n(enableInput_val18_c_full_n),
    .if_write(AXIvideo2MultiPixStream_U0_enableInput_val18_c_write),
    .if_dout(enableInput_val18_c_dout),
    .if_num_data_valid(enableInput_val18_c_num_data_valid),
    .if_fifo_cap(enableInput_val18_c_fifo_cap),
    .if_empty_n(enableInput_val18_c_empty_n),
    .if_read(tpgBackground_U0_enableInput_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d2_S colorFormat_val27_c20_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2MultiPixStream_U0_colorFormat_val27_c20_din),
    .if_full_n(colorFormat_val27_c20_full_n),
    .if_write(AXIvideo2MultiPixStream_U0_colorFormat_val27_c20_write),
    .if_dout(colorFormat_val27_c20_dout),
    .if_num_data_valid(colorFormat_val27_c20_num_data_valid),
    .if_fifo_cap(colorFormat_val27_c20_fifo_cap),
    .if_empty_n(colorFormat_val27_c20_empty_n),
    .if_read(tpgBackground_U0_colorFormat_val_read)
);

design_1_v_tpg_0_0_fifo_w24_d16_S bckgndYUV_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgBackground_U0_bckgndYUV_din),
    .if_full_n(bckgndYUV_full_n),
    .if_write(tpgBackground_U0_bckgndYUV_write),
    .if_dout(bckgndYUV_dout),
    .if_num_data_valid(bckgndYUV_num_data_valid),
    .if_fifo_cap(bckgndYUV_fifo_cap),
    .if_empty_n(bckgndYUV_empty_n),
    .if_read(tpgForeground_U0_bckgndYUV_read)
);

design_1_v_tpg_0_0_fifo_w16_d2_S height_val5_c14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgBackground_U0_height_val5_c14_din),
    .if_full_n(height_val5_c14_full_n),
    .if_write(tpgBackground_U0_height_val5_c14_write),
    .if_dout(height_val5_c14_dout),
    .if_num_data_valid(height_val5_c14_num_data_valid),
    .if_fifo_cap(height_val5_c14_fifo_cap),
    .if_empty_n(height_val5_c14_empty_n),
    .if_read(tpgForeground_U0_height_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d2_S width_val10_c16_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgBackground_U0_width_val10_c16_din),
    .if_full_n(width_val10_c16_full_n),
    .if_write(tpgBackground_U0_width_val10_c16_write),
    .if_dout(width_val10_c16_dout),
    .if_num_data_valid(width_val10_c16_num_data_valid),
    .if_fifo_cap(width_val10_c16_fifo_cap),
    .if_empty_n(width_val10_c16_empty_n),
    .if_read(tpgForeground_U0_width_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d2_S motionSpeed_val23_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgBackground_U0_motionSpeed_val23_c_din),
    .if_full_n(motionSpeed_val23_c_full_n),
    .if_write(tpgBackground_U0_motionSpeed_val23_c_write),
    .if_dout(motionSpeed_val23_c_dout),
    .if_num_data_valid(motionSpeed_val23_c_num_data_valid),
    .if_fifo_cap(motionSpeed_val23_c_fifo_cap),
    .if_empty_n(motionSpeed_val23_c_empty_n),
    .if_read(tpgForeground_U0_motionSpeed_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d2_S colorFormat_val27_c19_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgBackground_U0_colorFormat_val27_c19_din),
    .if_full_n(colorFormat_val27_c19_full_n),
    .if_write(tpgBackground_U0_colorFormat_val27_c19_write),
    .if_dout(colorFormat_val27_c19_dout),
    .if_num_data_valid(colorFormat_val27_c19_num_data_valid),
    .if_fifo_cap(colorFormat_val27_c19_fifo_cap),
    .if_empty_n(colorFormat_val27_c19_empty_n),
    .if_read(tpgForeground_U0_colorFormat_val_read)
);

design_1_v_tpg_0_0_fifo_w24_d16_S ovrlayYUV_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgForeground_U0_ovrlayYUV_din),
    .if_full_n(ovrlayYUV_full_n),
    .if_write(tpgForeground_U0_ovrlayYUV_write),
    .if_dout(ovrlayYUV_dout),
    .if_num_data_valid(ovrlayYUV_num_data_valid),
    .if_fifo_cap(ovrlayYUV_fifo_cap),
    .if_empty_n(ovrlayYUV_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_ovrlayYUV_read)
);

design_1_v_tpg_0_0_fifo_w10_d2_S height_val5_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgForeground_U0_height_val5_c_din),
    .if_full_n(height_val5_c_full_n),
    .if_write(tpgForeground_U0_height_val5_c_write),
    .if_dout(height_val5_c_dout),
    .if_num_data_valid(height_val5_c_num_data_valid),
    .if_fifo_cap(height_val5_c_fifo_cap),
    .if_empty_n(height_val5_c_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_height_val5_read)
);

design_1_v_tpg_0_0_fifo_w11_d2_S width_val10_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgForeground_U0_width_val10_c_din),
    .if_full_n(width_val10_c_full_n),
    .if_write(tpgForeground_U0_width_val10_c_write),
    .if_dout(width_val10_c_dout),
    .if_num_data_valid(width_val10_c_num_data_valid),
    .if_fifo_cap(width_val10_c_fifo_cap),
    .if_empty_n(width_val10_c_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_width_val10_read)
);

design_1_v_tpg_0_0_fifo_w8_d2_S colorFormat_val27_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgForeground_U0_colorFormat_val27_c_din),
    .if_full_n(colorFormat_val27_c_full_n),
    .if_write(tpgForeground_U0_colorFormat_val27_c_write),
    .if_dout(colorFormat_val27_c_dout),
    .if_num_data_valid(colorFormat_val27_c_num_data_valid),
    .if_fifo_cap(colorFormat_val27_c_fifo_cap),
    .if_empty_n(colorFormat_val27_c_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_colorFormat_val27_read)
);

design_1_v_tpg_0_0_start_for_tpgForeground_U0 start_for_tpgForeground_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_tpgForeground_U0_din),
    .if_full_n(start_for_tpgForeground_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_tpgForeground_U0_dout),
    .if_empty_n(start_for_tpgForeground_U0_empty_n),
    .if_read(tpgForeground_U0_ap_ready)
);

design_1_v_tpg_0_0_start_for_MultiPixStream2AXIvideo_U0 start_for_MultiPixStream2AXIvideo_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_MultiPixStream2AXIvideo_U0_din),
    .if_full_n(start_for_MultiPixStream2AXIvideo_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_MultiPixStream2AXIvideo_U0_dout),
    .if_empty_n(start_for_MultiPixStream2AXIvideo_U0_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= ap_sync_AXIvideo2MultiPixStream_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_tpgBackground_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_tpgBackground_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_tpgBackground_U0_ap_ready <= ap_sync_tpgBackground_U0_ap_ready;
        end
    end
end

assign AXIvideo2MultiPixStream_U0_ap_continue = 1'b1;

assign AXIvideo2MultiPixStream_U0_ap_start = ((ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready ^ 1'b1) & ap_start);

assign MultiPixStream2AXIvideo_U0_ap_continue = ap_continue;

assign MultiPixStream2AXIvideo_U0_ap_start = start_for_MultiPixStream2AXIvideo_U0_empty_n;

assign ap_done = MultiPixStream2AXIvideo_U0_ap_done;

assign ap_idle = (tpgForeground_U0_ap_idle & tpgBackground_U0_ap_idle & entry_proc_U0_ap_idle & MultiPixStream2AXIvideo_U0_ap_idle & AXIvideo2MultiPixStream_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_AXIvideo2MultiPixStream_U0_ap_ready = (ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready | AXIvideo2MultiPixStream_U0_ap_ready);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_tpgBackground_U0_ap_ready & ap_sync_entry_proc_U0_ap_ready & ap_sync_AXIvideo2MultiPixStream_U0_ap_ready);

assign ap_sync_tpgBackground_U0_ap_ready = (tpgBackground_U0_ap_ready | ap_sync_reg_tpgBackground_U0_ap_ready);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign entry_proc_U0_start_full_n = (start_for_tpgForeground_U0_full_n & start_for_MultiPixStream2AXIvideo_U0_full_n);

assign fid = MultiPixStream2AXIvideo_U0_fid;

assign fid_ap_vld = MultiPixStream2AXIvideo_U0_fid_ap_vld;

assign m_axis_video_TDATA = MultiPixStream2AXIvideo_U0_m_axis_video_TDATA;

assign m_axis_video_TDEST = MultiPixStream2AXIvideo_U0_m_axis_video_TDEST;

assign m_axis_video_TID = MultiPixStream2AXIvideo_U0_m_axis_video_TID;

assign m_axis_video_TKEEP = MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP;

assign m_axis_video_TLAST = MultiPixStream2AXIvideo_U0_m_axis_video_TLAST;

assign m_axis_video_TSTRB = MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB;

assign m_axis_video_TUSER = MultiPixStream2AXIvideo_U0_m_axis_video_TUSER;

assign m_axis_video_TVALID = MultiPixStream2AXIvideo_U0_m_axis_video_TVALID;

assign s_axis_video_TREADY = AXIvideo2MultiPixStream_U0_s_axis_video_TREADY;

assign start_for_MultiPixStream2AXIvideo_U0_din = 1'b1;

assign start_for_tpgForeground_U0_din = 1'b1;

assign tpgBackground_U0_ap_continue = 1'b1;

assign tpgBackground_U0_ap_start = ((ap_sync_reg_tpgBackground_U0_ap_ready ^ 1'b1) & ap_start);

assign tpgForeground_U0_ap_continue = 1'b1;

assign tpgForeground_U0_ap_start = start_for_tpgForeground_U0_empty_n;

endmodule //design_1_v_tpg_0_0_v_tpgHlsDataFlow
