// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_AXIvideo2MultiPixStream (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_axis_video_TDATA,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        srcYUV_din,
        srcYUV_num_data_valid,
        srcYUV_fifo_cap,
        srcYUV_full_n,
        srcYUV_write,
        enableInput,
        height,
        width,
        colorFormat
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] s_axis_video_TDATA;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input  [2:0] s_axis_video_TKEEP;
input  [2:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output  [23:0] srcYUV_din;
input  [4:0] srcYUV_num_data_valid;
input  [4:0] srcYUV_fifo_cap;
input   srcYUV_full_n;
output   srcYUV_write;
input  [7:0] enableInput;
input  [15:0] height;
input  [15:0] width;
input  [7:0] colorFormat;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg s_axis_video_TREADY;
reg srcYUV_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [9:0] trunc_ln782_fu_267_p1;
reg   [9:0] trunc_ln782_reg_369;
wire    ap_CS_fsm_state2;
wire   [10:0] empty_fu_271_p1;
reg   [10:0] empty_reg_374;
wire   [0:0] icmp_ln789_fu_275_p2;
reg   [0:0] icmp_ln789_reg_380;
wire   [0:0] cmp9451_fu_294_p2;
reg   [0:0] cmp9451_reg_408;
wire    ap_CS_fsm_state4;
wire   [0:0] cond_fu_299_p2;
reg   [0:0] cond_reg_412;
wire   [9:0] i_4_fu_317_p2;
reg   [9:0] i_4_reg_423;
wire    ap_CS_fsm_state5;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_start;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_done;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_idle;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_ready;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_s_axis_video_TREADY;
wire   [23:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_axi_data_V_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_axi_data_V_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_axi_last_V_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_axi_last_V_out_ap_vld;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_start;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_done;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_idle;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_ready;
wire   [23:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_srcYUV_din;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_srcYUV_write;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_s_axis_video_TREADY;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_eol_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_eol_out_ap_vld;
wire   [23:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_axi_data_V_6_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_axi_data_V_6_out_ap_vld;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_start;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_done;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_idle;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_ready;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_s_axis_video_TREADY;
wire   [23:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_axi_data_V_8_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_axi_data_V_8_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_axi_last_V_4_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_axi_last_V_4_out_ap_vld;
wire   [15:0] grp_reg_unsigned_short_s_fu_255_ap_return;
reg    grp_reg_unsigned_short_s_fu_255_ap_ce;
reg    ap_block_state1;
reg    ap_block_state1_ignore_call12;
wire   [15:0] grp_reg_unsigned_short_s_fu_261_ap_return;
reg    grp_reg_unsigned_short_s_fu_261_ap_ce;
reg    ap_block_state1_ignore_call15;
reg   [0:0] axi_last_V_2_reg_138;
wire    ap_CS_fsm_state10;
reg   [23:0] axi_data_2_lcssa_reg_148;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln800_fu_312_p2;
reg   [0:0] axi_last_2_lcssa_reg_158;
reg   [0:0] eol_0_lcssa_reg_169;
reg    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [23:0] axi_data_V_5_fu_106;
reg    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [0:0] axi_last_V_4_loc_fu_86;
reg   [9:0] i_fu_102;
reg   [0:0] sof_fu_110;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_start_reg = 1'b0;
end

design_1_v_tpg_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID),
    .s_axis_video_TDATA(s_axis_video_TDATA),
    .s_axis_video_TREADY(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP),
    .s_axis_video_TSTRB(s_axis_video_TSTRB),
    .s_axis_video_TUSER(s_axis_video_TUSER),
    .s_axis_video_TLAST(s_axis_video_TLAST),
    .s_axis_video_TID(s_axis_video_TID),
    .s_axis_video_TDEST(s_axis_video_TDEST),
    .axi_data_V_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_axi_data_V_out),
    .axi_data_V_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_axi_data_V_out_ap_vld),
    .axi_last_V_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_axi_last_V_out),
    .axi_last_V_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_axi_last_V_out_ap_vld)
);

design_1_v_tpg_0_0_AXIvideo2MultiPixStream_Pipeline_loop_width grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID),
    .srcYUV_din(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_srcYUV_din),
    .srcYUV_num_data_valid(5'd0),
    .srcYUV_fifo_cap(5'd0),
    .srcYUV_full_n(srcYUV_full_n),
    .srcYUV_write(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_srcYUV_write),
    .sof_5(sof_fu_110),
    .axi_last_V_2(axi_last_V_2_reg_138),
    .axi_data_V_5(axi_data_V_5_fu_106),
    .tmp_cast(empty_reg_374),
    .cond(cond_reg_412),
    .s_axis_video_TDATA(s_axis_video_TDATA),
    .s_axis_video_TREADY(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP),
    .s_axis_video_TSTRB(s_axis_video_TSTRB),
    .s_axis_video_TUSER(s_axis_video_TUSER),
    .s_axis_video_TLAST(s_axis_video_TLAST),
    .s_axis_video_TID(s_axis_video_TID),
    .s_axis_video_TDEST(s_axis_video_TDEST),
    .eol_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_eol_out),
    .eol_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_eol_out_ap_vld),
    .axi_data_V_6_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_axi_data_V_6_out),
    .axi_data_V_6_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_axi_data_V_6_out_ap_vld)
);

design_1_v_tpg_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID),
    .axi_data_2_lcssa(axi_data_2_lcssa_reg_148),
    .axi_last_2_lcssa(axi_last_2_lcssa_reg_158),
    .eol_0_lcssa(eol_0_lcssa_reg_169),
    .s_axis_video_TDATA(s_axis_video_TDATA),
    .s_axis_video_TREADY(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP),
    .s_axis_video_TSTRB(s_axis_video_TSTRB),
    .s_axis_video_TUSER(s_axis_video_TUSER),
    .s_axis_video_TLAST(s_axis_video_TLAST),
    .s_axis_video_TID(s_axis_video_TID),
    .s_axis_video_TDEST(s_axis_video_TDEST),
    .axi_data_V_8_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_axi_data_V_8_out),
    .axi_data_V_8_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_axi_data_V_8_out_ap_vld),
    .axi_last_V_4_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_axi_last_V_4_out),
    .axi_last_V_4_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_axi_last_V_4_out_ap_vld)
);

design_1_v_tpg_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_255(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(height),
    .ap_return(grp_reg_unsigned_short_s_fu_255_ap_return),
    .ap_ce(grp_reg_unsigned_short_s_fu_255_ap_ce)
);

design_1_v_tpg_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_261(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(width),
    .ap_return(grp_reg_unsigned_short_s_fu_261_ap_return),
    .ap_ce(grp_reg_unsigned_short_s_fu_261_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln789_reg_380 == 1'd1) | (icmp_ln800_fu_312_p2 == 1'd1)))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln789_fu_275_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_start_reg <= 1'b0;
    end else begin
        if (((cmp9451_reg_408 == 1'd0) & (icmp_ln789_reg_380 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln800_fu_312_p2 == 1'd0))) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((cmp9451_reg_408 == 1'd1) & (icmp_ln789_reg_380 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln800_fu_312_p2 == 1'd0))) begin
        axi_data_2_lcssa_reg_148 <= axi_data_V_5_fu_106;
    end else if (((cmp9451_reg_408 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        axi_data_2_lcssa_reg_148 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_axi_data_V_6_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_axi_data_V_8_out_ap_vld == 1'b1))) begin
        axi_data_V_5_fu_106 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_axi_data_V_8_out;
    end else if (((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_axi_data_V_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        axi_data_V_5_fu_106 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_axi_data_V_out;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp9451_reg_408 == 1'd1) & (icmp_ln789_reg_380 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln800_fu_312_p2 == 1'd0))) begin
        axi_last_2_lcssa_reg_158 <= axi_last_V_2_reg_138;
    end else if (((cmp9451_reg_408 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        axi_last_2_lcssa_reg_158 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_eol_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        axi_last_V_2_reg_138 <= axi_last_V_4_loc_fu_86;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        axi_last_V_2_reg_138 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_axi_last_V_out;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp9451_reg_408 == 1'd1) & (icmp_ln789_reg_380 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln800_fu_312_p2 == 1'd0))) begin
        eol_0_lcssa_reg_169 <= 1'd0;
    end else if (((cmp9451_reg_408 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        eol_0_lcssa_reg_169 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_eol_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln789_fu_275_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_102 <= 10'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        i_fu_102 <= i_4_reg_423;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln789_fu_275_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        sof_fu_110 <= 1'd1;
    end else if (((cmp9451_reg_408 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        sof_fu_110 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_axi_last_V_4_out_ap_vld == 1'b1))) begin
        axi_last_V_4_loc_fu_86 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_axi_last_V_4_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        cmp9451_reg_408 <= cmp9451_fu_294_p2;
        cond_reg_412 <= cond_fu_299_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        empty_reg_374 <= empty_fu_271_p1;
        icmp_ln789_reg_380 <= icmp_ln789_fu_275_p2;
        trunc_ln782_reg_369 <= trunc_ln782_fu_267_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln789_reg_380 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        i_4_reg_423 <= i_4_fu_317_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln789_reg_380 == 1'd1) | (icmp_ln800_fu_312_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln789_reg_380 == 1'd1) | (icmp_ln800_fu_312_p2 == 1'd1)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_reg_unsigned_short_s_fu_255_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_255_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_reg_unsigned_short_s_fu_261_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_261_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        s_axis_video_TREADY = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        s_axis_video_TREADY = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        s_axis_video_TREADY = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_s_axis_video_TREADY;
    end else begin
        s_axis_video_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        srcYUV_write = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_srcYUV_write;
    end else begin
        srcYUV_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln789_fu_275_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln789_reg_380 == 1'd1) | (icmp_ln800_fu_312_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((cmp9451_reg_408 == 1'd1) & (icmp_ln789_reg_380 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln800_fu_312_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call12 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call15 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign cmp9451_fu_294_p2 = ((empty_reg_374 == 11'd0) ? 1'b1 : 1'b0);

assign cond_fu_299_p2 = ((colorFormat == 8'd0) ? 1'b1 : 1'b0);

assign empty_fu_271_p1 = grp_reg_unsigned_short_s_fu_261_ap_return[10:0];

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_start = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_229_ap_start_reg;

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_start = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_181_ap_start_reg;

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_start = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_ap_start_reg;

assign i_4_fu_317_p2 = (i_fu_102 + 10'd1);

assign icmp_ln789_fu_275_p2 = ((enableInput == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln800_fu_312_p2 = ((i_fu_102 == trunc_ln782_reg_369) ? 1'b1 : 1'b0);

assign srcYUV_din = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_201_srcYUV_din;

assign trunc_ln782_fu_267_p1 = grp_reg_unsigned_short_s_fu_255_ap_return[9:0];

endmodule //design_1_v_tpg_0_0_AXIvideo2MultiPixStream
