-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_tpg_0_0_tpgBackground is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    srcYUV_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    srcYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    srcYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    srcYUV_empty_n : IN STD_LOGIC;
    srcYUV_read : OUT STD_LOGIC;
    height_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    height_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val_empty_n : IN STD_LOGIC;
    height_val_read : OUT STD_LOGIC;
    width_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    width_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val_empty_n : IN STD_LOGIC;
    width_val_read : OUT STD_LOGIC;
    passthruStartX_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    passthruStartX_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    passthruStartX_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    passthruStartX_val_empty_n : IN STD_LOGIC;
    passthruStartX_val_read : OUT STD_LOGIC;
    passthruStartY_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    passthruStartY_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    passthruStartY_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    passthruStartY_val_empty_n : IN STD_LOGIC;
    passthruStartY_val_read : OUT STD_LOGIC;
    passthruEndX_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    passthruEndX_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    passthruEndX_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    passthruEndX_val_empty_n : IN STD_LOGIC;
    passthruEndX_val_read : OUT STD_LOGIC;
    passthruEndY_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    passthruEndY_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    passthruEndY_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    passthruEndY_val_empty_n : IN STD_LOGIC;
    passthruEndY_val_read : OUT STD_LOGIC;
    enableInput_val_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    enableInput_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    enableInput_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    enableInput_val_empty_n : IN STD_LOGIC;
    enableInput_val_read : OUT STD_LOGIC;
    patternId_val_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    patternId_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    patternId_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    patternId_val_empty_n : IN STD_LOGIC;
    patternId_val_read : OUT STD_LOGIC;
    ZplateHorContStart_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateHorContStart_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    ZplateHorContStart_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    ZplateHorContStart_val_empty_n : IN STD_LOGIC;
    ZplateHorContStart_val_read : OUT STD_LOGIC;
    ZplateHorContDelta_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateHorContDelta_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    ZplateHorContDelta_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    ZplateHorContDelta_val_empty_n : IN STD_LOGIC;
    ZplateHorContDelta_val_read : OUT STD_LOGIC;
    ZplateVerContStart_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContStart_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    ZplateVerContStart_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    ZplateVerContStart_val_empty_n : IN STD_LOGIC;
    ZplateVerContStart_val_read : OUT STD_LOGIC;
    ZplateVerContDelta_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContDelta_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    ZplateVerContDelta_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    ZplateVerContDelta_val_empty_n : IN STD_LOGIC;
    ZplateVerContDelta_val_read : OUT STD_LOGIC;
    dpDynamicRange_val_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    dpDynamicRange_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    dpDynamicRange_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    dpDynamicRange_val_empty_n : IN STD_LOGIC;
    dpDynamicRange_val_read : OUT STD_LOGIC;
    dpYUVCoef_val_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    dpYUVCoef_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    dpYUVCoef_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    dpYUVCoef_val_empty_n : IN STD_LOGIC;
    dpYUVCoef_val_read : OUT STD_LOGIC;
    motionSpeed_val_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    motionSpeed_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    motionSpeed_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    motionSpeed_val_empty_n : IN STD_LOGIC;
    motionSpeed_val_read : OUT STD_LOGIC;
    colorFormat_val_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    colorFormat_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    colorFormat_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    colorFormat_val_empty_n : IN STD_LOGIC;
    colorFormat_val_read : OUT STD_LOGIC;
    bckgndYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_full_n : IN STD_LOGIC;
    bckgndYUV_write : OUT STD_LOGIC;
    height_val5_c14_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    height_val5_c14_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val5_c14_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val5_c14_full_n : IN STD_LOGIC;
    height_val5_c14_write : OUT STD_LOGIC;
    width_val10_c16_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    width_val10_c16_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val10_c16_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val10_c16_full_n : IN STD_LOGIC;
    width_val10_c16_write : OUT STD_LOGIC;
    motionSpeed_val23_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    motionSpeed_val23_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    motionSpeed_val23_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    motionSpeed_val23_c_full_n : IN STD_LOGIC;
    motionSpeed_val23_c_write : OUT STD_LOGIC;
    colorFormat_val27_c19_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    colorFormat_val27_c19_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    colorFormat_val27_c19_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    colorFormat_val27_c19_full_n : IN STD_LOGIC;
    colorFormat_val27_c19_write : OUT STD_LOGIC;
    s : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of design_1_v_tpg_0_0_tpgBackground is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_4C : STD_LOGIC_VECTOR (7 downto 0) := "01001100";
    constant ap_const_lv8_95 : STD_LOGIC_VECTOR (7 downto 0) := "10010101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv8_6B : STD_LOGIC_VECTOR (7 downto 0) := "01101011";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv14_7 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000111";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv14_F : STD_LOGIC_VECTOR (13 downto 0) := "00000000001111";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal rampStart : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal rampVal_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal rampVal : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_4_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal hBarSel_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal hdata : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal rampVal_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_1 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal hBarSel_5_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal height_val_blk_n : STD_LOGIC;
    signal width_val_blk_n : STD_LOGIC;
    signal passthruStartX_val_blk_n : STD_LOGIC;
    signal passthruStartY_val_blk_n : STD_LOGIC;
    signal passthruEndX_val_blk_n : STD_LOGIC;
    signal passthruEndY_val_blk_n : STD_LOGIC;
    signal enableInput_val_blk_n : STD_LOGIC;
    signal patternId_val_blk_n : STD_LOGIC;
    signal ZplateHorContStart_val_blk_n : STD_LOGIC;
    signal ZplateHorContDelta_val_blk_n : STD_LOGIC;
    signal ZplateVerContStart_val_blk_n : STD_LOGIC;
    signal ZplateVerContDelta_val_blk_n : STD_LOGIC;
    signal dpDynamicRange_val_blk_n : STD_LOGIC;
    signal dpYUVCoef_val_blk_n : STD_LOGIC;
    signal motionSpeed_val_blk_n : STD_LOGIC;
    signal colorFormat_val_blk_n : STD_LOGIC;
    signal height_val5_c14_blk_n : STD_LOGIC;
    signal width_val10_c16_blk_n : STD_LOGIC;
    signal motionSpeed_val23_c_blk_n : STD_LOGIC;
    signal colorFormat_val27_c19_blk_n : STD_LOGIC;
    signal dpYUVCoef_val_read_reg_1270 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal dpDynamicRange_val_read_reg_1275 : STD_LOGIC_VECTOR (7 downto 0);
    signal ZplateVerContDelta_val_read_reg_1280 : STD_LOGIC_VECTOR (15 downto 0);
    signal ZplateVerContStart_val_read_reg_1285 : STD_LOGIC_VECTOR (15 downto 0);
    signal ZplateHorContDelta_val_read_reg_1290 : STD_LOGIC_VECTOR (15 downto 0);
    signal ZplateHorContStart_val_read_reg_1295 : STD_LOGIC_VECTOR (15 downto 0);
    signal colorFormatLocal_reg_1300 : STD_LOGIC_VECTOR (7 downto 0);
    signal motionSpeed_val_read_reg_1305 : STD_LOGIC_VECTOR (7 downto 0);
    signal patternId_val_read_reg_1310 : STD_LOGIC_VECTOR (7 downto 0);
    signal passthruEndY_val_read_reg_1315 : STD_LOGIC_VECTOR (15 downto 0);
    signal passthruEndX_val_read_reg_1320 : STD_LOGIC_VECTOR (15 downto 0);
    signal passthruStartY_val_read_reg_1325 : STD_LOGIC_VECTOR (15 downto 0);
    signal passthruStartX_val_read_reg_1330 : STD_LOGIC_VECTOR (15 downto 0);
    signal loopWidth_reg_1335 : STD_LOGIC_VECTOR (15 downto 0);
    signal loopHeight_reg_1341 : STD_LOGIC_VECTOR (15 downto 0);
    signal cmp8_fu_714_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp8_reg_1347 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp2_i267_fu_720_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp2_i267_reg_1352 : STD_LOGIC_VECTOR (0 downto 0);
    signal outpix_fu_726_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_reg_1357 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_1_fu_734_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal outpix_1_reg_1362 : STD_LOGIC_VECTOR (0 downto 0);
    signal outpix_2_fu_740_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_2_reg_1367 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln552_fu_748_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln552_reg_1372 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln552_1_cast_cast_fu_756_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln552_1_cast_cast_reg_1377 : STD_LOGIC_VECTOR (2 downto 0);
    signal outpix_3_fu_764_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_3_reg_1382 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_fu_772_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_reg_1387 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_16_fu_780_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_16_reg_1392 : STD_LOGIC_VECTOR (7 downto 0);
    signal barWidth_reg_1397 : STD_LOGIC_VECTOR (10 downto 0);
    signal barWidthMinSamples_fu_824_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal barWidthMinSamples_reg_1403 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_fu_850_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_1408 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_i_i_i_fu_870_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_i_i_i_reg_1413 : STD_LOGIC_VECTOR (10 downto 0);
    signal rampStart_load_reg_1418 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_3_reg_1424 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal outpix_6_load_reg_1436 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_7_load_reg_1441 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_8_load_reg_1446 : STD_LOGIC_VECTOR (7 downto 0);
    signal ult_fu_1040_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ult_reg_1451 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln563_fu_1087_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln563_reg_1456 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal rev_fu_1091_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_reg_1461 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp12_i_fu_1097_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp12_i_reg_1466 : STD_LOGIC_VECTOR (0 downto 0);
    signal Sel_reg_1471 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_start : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_done : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_idle : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_ready : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_srcYUV_read : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_bckgndYUV_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_bckgndYUV_write : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_4_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_4_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_zonePlateVAddr_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_zonePlateVAddr_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_2_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_2_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_3_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_3_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_3_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_5_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_5_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_11_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_11_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_10_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_10_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_9_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_9_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_0248_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_0248_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_09246_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_09246_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_010244_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_010244_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_4_0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_4_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_zonePlateVAddr_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_3_0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_3_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_2_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_5_0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_5_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_1_ap_vld : STD_LOGIC;
    signal ap_phi_mux_rampVal_3_flag_0_phi_fu_496_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_3_flag_0_reg_492 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_phi_mux_hdata_flag_0_phi_fu_508_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal hdata_flag_0_reg_504 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_rampVal_2_flag_0_phi_fu_520_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_2_flag_0_reg_516 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal rampVal_3_new_0_fu_348 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_3_loc_0_fu_344 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal rampVal_loc_0_fu_340 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal hBarSel_4_0_loc_0_fu_336 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zonePlateVAddr_loc_0_fu_332 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_loc_0_fu_328 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_0_loc_0_fu_324 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hdata_new_0_fu_320 : STD_LOGIC_VECTOR (15 downto 0);
    signal hdata_loc_0_fu_316 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_2_loc_0_fu_312 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_3_0_loc_0_fu_308 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal rampVal_2_new_0_fu_304 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_2_loc_0_fu_300 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_3_loc_0_fu_296 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_5_0_loc_0_fu_292 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal outpix_8_fu_288 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_7_fu_284 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_6_fu_280 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0249_lcssa258_fu_272 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_09247_lcssa255_fu_268 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_010245_lcssa252_fu_264 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln750_fu_1050_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln563_fu_1020_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_fu_276 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal add_ln563_fu_1025_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln563_fu_948_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1775_fu_940_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1664_fu_928_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1545_fu_912_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1412_fu_904_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1257_fu_888_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_fu_788_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_i_fu_792_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add2_i_fu_808_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_cast_fu_814_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_118_fu_830_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_fu_840_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal add5_i_fu_834_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_1_fu_856_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal barHeight_cast_fu_866_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        srcYUV_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        srcYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        srcYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        srcYUV_empty_n : IN STD_LOGIC;
        srcYUV_read : OUT STD_LOGIC;
        bckgndYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_full_n : IN STD_LOGIC;
        bckgndYUV_write : OUT STD_LOGIC;
        rampVal_3_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        outpix_8 : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_7 : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_6 : IN STD_LOGIC_VECTOR (7 downto 0);
        loopWidth : IN STD_LOGIC_VECTOR (15 downto 0);
        pix_19 : IN STD_LOGIC_VECTOR (7 downto 0);
        pix_18 : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_3 : IN STD_LOGIC_VECTOR (7 downto 0);
        select_ln552 : IN STD_LOGIC_VECTOR (4 downto 0);
        sext_ln552 : IN STD_LOGIC_VECTOR (0 downto 0);
        select_ln552_1_cast_cast : IN STD_LOGIC_VECTOR (2 downto 0);
        outpix_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix : IN STD_LOGIC_VECTOR (7 downto 0);
        rampStart_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        cmp8 : IN STD_LOGIC_VECTOR (0 downto 0);
        patternId_val_load : IN STD_LOGIC_VECTOR (7 downto 0);
        Zplate_Hor_Control_Start : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp2_i267 : IN STD_LOGIC_VECTOR (0 downto 0);
        zext_ln1084 : IN STD_LOGIC_VECTOR (7 downto 0);
        y : IN STD_LOGIC_VECTOR (15 downto 0);
        colorFormatLocal : IN STD_LOGIC_VECTOR (7 downto 0);
        barWidth_cast : IN STD_LOGIC_VECTOR (10 downto 0);
        barWidth : IN STD_LOGIC_VECTOR (10 downto 0);
        Zplate_Hor_Control_Delta : IN STD_LOGIC_VECTOR (15 downto 0);
        Zplate_Ver_Control_Start : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp12_i : IN STD_LOGIC_VECTOR (0 downto 0);
        Zplate_Ver_Control_Delta : IN STD_LOGIC_VECTOR (15 downto 0);
        sub_i_i_i : IN STD_LOGIC_VECTOR (10 downto 0);
        barWidthMinSamples : IN STD_LOGIC_VECTOR (9 downto 0);
        width_val_cast30 : IN STD_LOGIC_VECTOR (15 downto 0);
        height_val_cast24 : IN STD_LOGIC_VECTOR (15 downto 0);
        zext_ln565 : IN STD_LOGIC_VECTOR (15 downto 0);
        empty : IN STD_LOGIC_VECTOR (7 downto 0);
        icmp : IN STD_LOGIC_VECTOR (0 downto 0);
        Sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dpDynamicRange : IN STD_LOGIC_VECTOR (7 downto 0);
        dpYUVCoef : IN STD_LOGIC_VECTOR (7 downto 0);
        passthruEndX_val_load : IN STD_LOGIC_VECTOR (15 downto 0);
        passthruStartX_val_load : IN STD_LOGIC_VECTOR (15 downto 0);
        passthruStartY_val_load : IN STD_LOGIC_VECTOR (15 downto 0);
        rev : IN STD_LOGIC_VECTOR (0 downto 0);
        rampVal_3_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_3_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_4_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        zonePlateVAddr_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hdata_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_1_out_ap_vld : OUT STD_LOGIC;
        hdata_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_new_1_out_ap_vld : OUT STD_LOGIC;
        hdata_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_2_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_3_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_3_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_3_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_2_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_3_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_5_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_5_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_5_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        outpix_11_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        outpix_11_out_ap_vld : OUT STD_LOGIC;
        outpix_10_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        outpix_10_out_ap_vld : OUT STD_LOGIC;
        outpix_9_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        outpix_9_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0248_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0248_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0248_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_09246_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_09246_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_09246_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_010244_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_010244_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_010244_out_o_ap_vld : OUT STD_LOGIC;
        rampVal : OUT STD_LOGIC_VECTOR (7 downto 0);
        rampVal_ap_vld : OUT STD_LOGIC;
        hBarSel_4_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_0_ap_vld : OUT STD_LOGIC;
        s : IN STD_LOGIC_VECTOR (31 downto 0);
        zonePlateVAddr : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_ap_vld : OUT STD_LOGIC;
        hBarSel_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_0_ap_vld : OUT STD_LOGIC;
        vBarSel : OUT STD_LOGIC_VECTOR (2 downto 0);
        vBarSel_ap_vld : OUT STD_LOGIC;
        hBarSel_3_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_3_0_ap_vld : OUT STD_LOGIC;
        vBarSel_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_ap_vld : OUT STD_LOGIC;
        hBarSel_5_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_5_0_ap_vld : OUT STD_LOGIC;
        vBarSel_1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        vBarSel_1_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528 : component design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_start,
        ap_done => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_done,
        ap_idle => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_idle,
        ap_ready => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_ready,
        srcYUV_dout => srcYUV_dout,
        srcYUV_num_data_valid => ap_const_lv5_0,
        srcYUV_fifo_cap => ap_const_lv5_0,
        srcYUV_empty_n => srcYUV_empty_n,
        srcYUV_read => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_srcYUV_read,
        bckgndYUV_din => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_bckgndYUV_din,
        bckgndYUV_num_data_valid => ap_const_lv5_0,
        bckgndYUV_fifo_cap => ap_const_lv5_0,
        bckgndYUV_full_n => bckgndYUV_full_n,
        bckgndYUV_write => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_bckgndYUV_write,
        rampVal_3_flag_0 => rampVal_3_flag_0_reg_492,
        hdata_flag_0 => hdata_flag_0_reg_504,
        rampVal_2_flag_0 => rampVal_2_flag_0_reg_516,
        outpix_8 => outpix_8_load_reg_1446,
        outpix_7 => outpix_7_load_reg_1441,
        outpix_6 => outpix_6_load_reg_1436,
        loopWidth => loopWidth_reg_1335,
        pix_19 => pix_16_reg_1392,
        pix_18 => pix_reg_1387,
        outpix_3 => outpix_3_reg_1382,
        select_ln552 => select_ln552_reg_1372,
        sext_ln552 => outpix_1_reg_1362,
        select_ln552_1_cast_cast => select_ln552_1_cast_cast_reg_1377,
        outpix_2 => outpix_2_reg_1367,
        outpix => outpix_reg_1357,
        rampStart_1 => rampStart_load_reg_1418,
        cmp8 => cmp8_reg_1347,
        patternId_val_load => patternId_val_read_reg_1310,
        Zplate_Hor_Control_Start => ZplateHorContStart_val_read_reg_1295,
        cmp2_i267 => cmp2_i267_reg_1352,
        zext_ln1084 => rampStart_load_reg_1418,
        y => y_3_reg_1424,
        colorFormatLocal => colorFormatLocal_reg_1300,
        barWidth_cast => barWidth_reg_1397,
        barWidth => barWidth_reg_1397,
        Zplate_Hor_Control_Delta => ZplateHorContDelta_val_read_reg_1290,
        Zplate_Ver_Control_Start => ZplateVerContStart_val_read_reg_1285,
        cmp12_i => cmp12_i_reg_1466,
        Zplate_Ver_Control_Delta => ZplateVerContDelta_val_read_reg_1280,
        sub_i_i_i => sub_i_i_i_reg_1413,
        barWidthMinSamples => barWidthMinSamples_reg_1403,
        width_val_cast30 => loopWidth_reg_1335,
        height_val_cast24 => loopHeight_reg_1341,
        zext_ln565 => y_3_reg_1424,
        empty => trunc_ln563_reg_1456,
        icmp => icmp_reg_1408,
        Sel => Sel_reg_1471,
        dpDynamicRange => dpDynamicRange_val_read_reg_1275,
        dpYUVCoef => dpYUVCoef_val_read_reg_1270,
        passthruEndX_val_load => passthruEndX_val_read_reg_1320,
        passthruStartX_val_load => passthruStartX_val_read_reg_1330,
        passthruStartY_val_load => passthruStartY_val_read_reg_1325,
        rev => rev_reg_1461,
        rampVal_3_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_flag_1_out,
        rampVal_3_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_flag_1_out_ap_vld,
        rampVal_3_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_new_1_out,
        rampVal_3_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_new_1_out_ap_vld,
        rampVal_3_loc_1_out_i => rampVal_3_loc_0_fu_344,
        rampVal_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_loc_1_out_o,
        rampVal_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_loc_1_out_o_ap_vld,
        rampVal_loc_1_out_i => rampVal_loc_0_fu_340,
        rampVal_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_loc_1_out_o,
        rampVal_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_loc_1_out_o_ap_vld,
        hBarSel_4_0_loc_1_out_i => hBarSel_4_0_loc_0_fu_336,
        hBarSel_4_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_4_0_loc_1_out_o,
        hBarSel_4_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_4_0_loc_1_out_o_ap_vld,
        zonePlateVAddr_loc_1_out_i => zonePlateVAddr_loc_0_fu_332,
        zonePlateVAddr_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_zonePlateVAddr_loc_1_out_o,
        zonePlateVAddr_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_zonePlateVAddr_loc_1_out_o_ap_vld,
        vBarSel_loc_1_out_i => vBarSel_loc_0_fu_328,
        vBarSel_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_loc_1_out_o,
        vBarSel_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_loc_1_out_o_ap_vld,
        hBarSel_0_loc_1_out_i => hBarSel_0_loc_0_fu_324,
        hBarSel_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_0_loc_1_out_o,
        hBarSel_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_0_loc_1_out_o_ap_vld,
        hdata_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_flag_1_out,
        hdata_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_flag_1_out_ap_vld,
        hdata_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_new_1_out,
        hdata_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_new_1_out_ap_vld,
        hdata_loc_1_out_i => hdata_loc_0_fu_316,
        hdata_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_loc_1_out_o,
        hdata_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_loc_1_out_o_ap_vld,
        vBarSel_2_loc_1_out_i => vBarSel_2_loc_0_fu_312,
        vBarSel_2_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_2_loc_1_out_o,
        vBarSel_2_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_2_loc_1_out_o_ap_vld,
        hBarSel_3_0_loc_1_out_i => hBarSel_3_0_loc_0_fu_308,
        hBarSel_3_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_3_0_loc_1_out_o,
        hBarSel_3_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_3_0_loc_1_out_o_ap_vld,
        rampVal_2_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_flag_1_out,
        rampVal_2_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_flag_1_out_ap_vld,
        rampVal_2_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_new_1_out,
        rampVal_2_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_new_1_out_ap_vld,
        rampVal_2_loc_1_out_i => rampVal_2_loc_0_fu_300,
        rampVal_2_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_loc_1_out_o,
        rampVal_2_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_loc_1_out_o_ap_vld,
        vBarSel_3_loc_1_out_i => vBarSel_3_loc_0_fu_296,
        vBarSel_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_3_loc_1_out_o,
        vBarSel_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_3_loc_1_out_o_ap_vld,
        hBarSel_5_0_loc_1_out_i => hBarSel_5_0_loc_0_fu_292,
        hBarSel_5_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_5_0_loc_1_out_o,
        hBarSel_5_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_5_0_loc_1_out_o_ap_vld,
        outpix_11_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_11_out,
        outpix_11_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_11_out_ap_vld,
        outpix_10_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_10_out,
        outpix_10_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_10_out_ap_vld,
        outpix_9_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_9_out,
        outpix_9_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_9_out_ap_vld,
        p_0_0_0248_out_i => p_0_0_0249_lcssa258_fu_272,
        p_0_0_0248_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_0248_out_o,
        p_0_0_0248_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_0248_out_o_ap_vld,
        p_0_0_09246_out_i => p_0_0_09247_lcssa255_fu_268,
        p_0_0_09246_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_09246_out_o,
        p_0_0_09246_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_09246_out_o_ap_vld,
        p_0_0_010244_out_i => p_0_0_010245_lcssa252_fu_264,
        p_0_0_010244_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_010244_out_o,
        p_0_0_010244_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_010244_out_o_ap_vld,
        rampVal => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal,
        rampVal_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_ap_vld,
        hBarSel_4_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_4_0,
        hBarSel_4_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_4_0_ap_vld,
        s => s,
        zonePlateVAddr => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_zonePlateVAddr,
        zonePlateVAddr_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_zonePlateVAddr_ap_vld,
        hBarSel_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_0,
        hBarSel_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_0_ap_vld,
        vBarSel => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel,
        vBarSel_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_ap_vld,
        hBarSel_3_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_3_0,
        hBarSel_3_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_3_0_ap_vld,
        vBarSel_2 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_2,
        vBarSel_2_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_2_ap_vld,
        hBarSel_5_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_5_0,
        hBarSel_5_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_5_0_ap_vld,
        vBarSel_1 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_1,
        vBarSel_1_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_1_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln563_fu_1020_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_ready = ap_const_logic_1)) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    hBarSel_0_loc_0_fu_324_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_0_loc_0_fu_324 <= zext_ln1545_fu_912_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_0_loc_0_fu_324 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_3_0_loc_0_fu_308_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_3_0_loc_0_fu_308 <= zext_ln1664_fu_928_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_3_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_3_0_loc_0_fu_308 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_3_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_4_0_loc_0_fu_336_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_4_0_loc_0_fu_336 <= hBarSel_4_0;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_4_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_4_0_loc_0_fu_336 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_4_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_5_0_loc_0_fu_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_5_0_loc_0_fu_292 <= zext_ln563_fu_948_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_5_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_5_0_loc_0_fu_292 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_5_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hdata_flag_0_reg_504_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                hdata_flag_0_reg_504 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_flag_1_out;
            elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hdata_flag_0_reg_504 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    hdata_loc_0_fu_316_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hdata_loc_0_fu_316 <= hdata;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hdata_loc_0_fu_316 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_2_flag_0_reg_516_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                rampVal_2_flag_0_reg_516 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_flag_1_out;
            elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_2_flag_0_reg_516 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_2_loc_0_fu_300_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_2_loc_0_fu_300 <= rampVal_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                rampVal_2_loc_0_fu_300 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_3_flag_0_reg_492_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                rampVal_3_flag_0_reg_492 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_flag_1_out;
            elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_3_flag_0_reg_492 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_3_loc_0_fu_344_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_3_loc_0_fu_344 <= rampVal_1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                rampVal_3_loc_0_fu_344 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_loc_0_fu_340_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_loc_0_fu_340 <= zext_ln1257_fu_888_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                rampVal_loc_0_fu_340 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_2_loc_0_fu_312_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vBarSel_2_loc_0_fu_312 <= vBarSel_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_2_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vBarSel_2_loc_0_fu_312 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_2_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_3_loc_0_fu_296_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vBarSel_3_loc_0_fu_296 <= zext_ln1775_fu_940_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vBarSel_3_loc_0_fu_296 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_loc_0_fu_328_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vBarSel_loc_0_fu_328 <= zext_ln1412_fu_904_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vBarSel_loc_0_fu_328 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_loc_1_out_o;
            end if; 
        end if;
    end process;

    y_fu_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_276 <= ap_const_lv16_0;
            elsif (((icmp_ln563_fu_1020_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                y_fu_276 <= add_ln563_fu_1025_p2;
            end if; 
        end if;
    end process;

    zonePlateVAddr_loc_0_fu_332_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                zonePlateVAddr_loc_0_fu_332 <= zonePlateVAddr;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_zonePlateVAddr_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                zonePlateVAddr_loc_0_fu_332 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_zonePlateVAddr_loc_1_out_o;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                Sel_reg_1471 <= y_3_reg_1424(7 downto 6);
                cmp12_i_reg_1466 <= cmp12_i_fu_1097_p2;
                rev_reg_1461 <= rev_fu_1091_p2;
                trunc_ln563_reg_1456 <= trunc_ln563_fu_1087_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                ZplateHorContDelta_val_read_reg_1290 <= ZplateHorContDelta_val_dout;
                ZplateHorContStart_val_read_reg_1295 <= ZplateHorContStart_val_dout;
                ZplateVerContDelta_val_read_reg_1280 <= ZplateVerContDelta_val_dout;
                ZplateVerContStart_val_read_reg_1285 <= ZplateVerContStart_val_dout;
                barWidthMinSamples_reg_1403 <= barWidthMinSamples_fu_824_p2;
                barWidth_reg_1397 <= add_i_fu_792_p2(13 downto 3);
                cmp2_i267_reg_1352 <= cmp2_i267_fu_720_p2;
                cmp8_reg_1347 <= cmp8_fu_714_p2;
                colorFormatLocal_reg_1300 <= colorFormat_val_dout;
                dpDynamicRange_val_read_reg_1275 <= dpDynamicRange_val_dout;
                dpYUVCoef_val_read_reg_1270 <= dpYUVCoef_val_dout;
                icmp_reg_1408 <= icmp_fu_850_p2;
                loopHeight_reg_1341 <= height_val_dout;
                loopWidth_reg_1335 <= width_val_dout;
                motionSpeed_val_read_reg_1305 <= motionSpeed_val_dout;
                outpix_1_reg_1362 <= outpix_1_fu_734_p2;
                    outpix_2_reg_1367(0) <= outpix_2_fu_740_p3(0);    outpix_2_reg_1367(2) <= outpix_2_fu_740_p3(2);    outpix_2_reg_1367(4) <= outpix_2_fu_740_p3(4);    outpix_2_reg_1367(7) <= outpix_2_fu_740_p3(7);
                    outpix_3_reg_1382(2) <= outpix_3_fu_764_p3(2);    outpix_3_reg_1382(4) <= outpix_3_fu_764_p3(4);    outpix_3_reg_1382(7) <= outpix_3_fu_764_p3(7);
                    outpix_reg_1357(1 downto 0) <= outpix_fu_726_p3(1 downto 0);    outpix_reg_1357(5 downto 4) <= outpix_fu_726_p3(5 downto 4);    outpix_reg_1357(7) <= outpix_fu_726_p3(7);
                passthruEndX_val_read_reg_1320 <= passthruEndX_val_dout;
                passthruEndY_val_read_reg_1315 <= passthruEndY_val_dout;
                passthruStartX_val_read_reg_1330 <= passthruStartX_val_dout;
                passthruStartY_val_read_reg_1325 <= passthruStartY_val_dout;
                patternId_val_read_reg_1310 <= patternId_val_dout;
                    pix_16_reg_1392(6 downto 0) <= pix_16_fu_780_p3(6 downto 0);
                    pix_reg_1387(7) <= pix_fu_772_p3(7);
                rampStart_load_reg_1418 <= rampStart;
                    select_ln552_1_cast_cast_reg_1377(0) <= select_ln552_1_cast_cast_fu_756_p3(0);    select_ln552_1_cast_cast_reg_1377(2) <= select_ln552_1_cast_cast_fu_756_p3(2);
                    select_ln552_reg_1372(0) <= select_ln552_fu_748_p3(0);    select_ln552_reg_1372(2) <= select_ln552_fu_748_p3(2);    select_ln552_reg_1372(4) <= select_ln552_fu_748_p3(4);
                sub_i_i_i_reg_1413 <= sub_i_i_i_fu_870_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_3_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_3_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_3_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_4_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_4_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_4_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_5_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_5_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hBarSel_5_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_1020_p2 = ap_const_lv1_1) and (ap_phi_mux_hdata_flag_0_phi_fu_508_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                hdata <= hdata_new_0_fu_320;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hdata_new_0_fu_320 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_hdata_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_9_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                outpix_6_fu_280 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_9_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                outpix_6_load_reg_1436 <= outpix_6_fu_280;
                outpix_7_load_reg_1441 <= outpix_7_fu_284;
                outpix_8_load_reg_1446 <= outpix_8_fu_288;
                ult_reg_1451 <= ult_fu_1040_p2;
                y_3_reg_1424 <= y_fu_276;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_10_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                outpix_7_fu_284 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_10_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_11_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                outpix_8_fu_288 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_outpix_11_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_010244_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_010245_lcssa252_fu_264 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_010244_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_0248_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0249_lcssa258_fu_272 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_0248_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_09246_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_09247_lcssa255_fu_268 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_p_0_0_09246_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_1020_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                rampStart <= add_ln750_fu_1050_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_1020_p2 = ap_const_lv1_1) and (ap_phi_mux_rampVal_3_flag_0_phi_fu_496_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                rampVal_1 <= rampVal_3_new_0_fu_348;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_1020_p2 = ap_const_lv1_1) and (ap_phi_mux_rampVal_2_flag_0_phi_fu_520_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                rampVal_2 <= rampVal_2_new_0_fu_304;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                rampVal_2_new_0_fu_304 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_2_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                rampVal_3_new_0_fu_348 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_rampVal_3_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                vBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_vBarSel_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_zonePlateVAddr_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_zonePlateVAddr;
            end if;
        end if;
    end process;
    outpix_reg_1357(3 downto 2) <= "11";
    outpix_reg_1357(6) <= '1';
    outpix_2_reg_1367(1) <= '0';
    outpix_2_reg_1367(3 downto 3) <= "0";
    outpix_2_reg_1367(6 downto 5) <= "00";
    select_ln552_reg_1372(1) <= '0';
    select_ln552_reg_1372(3) <= '0';
    select_ln552_1_cast_cast_reg_1377(1) <= '0';
    outpix_3_reg_1382(1 downto 0) <= "11";
    outpix_3_reg_1382(3 downto 3) <= "1";
    outpix_3_reg_1382(6 downto 5) <= "11";
    pix_reg_1387(6 downto 0) <= "0000000";
    pix_16_reg_1392(7) <= '1';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_done, ap_CS_fsm_state4, icmp_ln563_fu_1020_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln563_fu_1020_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;

    ZplateHorContDelta_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ZplateHorContDelta_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ZplateHorContDelta_val_blk_n <= ZplateHorContDelta_val_empty_n;
        else 
            ZplateHorContDelta_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ZplateHorContDelta_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ZplateHorContDelta_val_read <= ap_const_logic_1;
        else 
            ZplateHorContDelta_val_read <= ap_const_logic_0;
        end if; 
    end process;


    ZplateHorContStart_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ZplateHorContStart_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ZplateHorContStart_val_blk_n <= ZplateHorContStart_val_empty_n;
        else 
            ZplateHorContStart_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ZplateHorContStart_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ZplateHorContStart_val_read <= ap_const_logic_1;
        else 
            ZplateHorContStart_val_read <= ap_const_logic_0;
        end if; 
    end process;


    ZplateVerContDelta_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ZplateVerContDelta_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ZplateVerContDelta_val_blk_n <= ZplateVerContDelta_val_empty_n;
        else 
            ZplateVerContDelta_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ZplateVerContDelta_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ZplateVerContDelta_val_read <= ap_const_logic_1;
        else 
            ZplateVerContDelta_val_read <= ap_const_logic_0;
        end if; 
    end process;


    ZplateVerContStart_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ZplateVerContStart_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ZplateVerContStart_val_blk_n <= ZplateVerContStart_val_empty_n;
        else 
            ZplateVerContStart_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ZplateVerContStart_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ZplateVerContStart_val_read <= ap_const_logic_1;
        else 
            ZplateVerContStart_val_read <= ap_const_logic_0;
        end if; 
    end process;

    add2_i_fu_808_p2 <= std_logic_vector(unsigned(empty_fu_788_p1) + unsigned(ap_const_lv14_F));
    add5_i_fu_834_p2 <= std_logic_vector(unsigned(empty_118_fu_830_p1) + unsigned(ap_const_lv14_F));
    add_i_fu_792_p2 <= std_logic_vector(unsigned(empty_fu_788_p1) + unsigned(ap_const_lv14_7));
    add_ln563_fu_1025_p2 <= std_logic_vector(unsigned(y_fu_276) + unsigned(ap_const_lv16_1));
    add_ln750_fu_1050_p2 <= std_logic_vector(unsigned(rampStart) + unsigned(motionSpeed_val_read_reg_1305));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_done)
    begin
        if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, height_val_empty_n, width_val_empty_n, passthruStartX_val_empty_n, passthruStartY_val_empty_n, passthruEndX_val_empty_n, passthruEndY_val_empty_n, enableInput_val_empty_n, patternId_val_empty_n, ZplateHorContStart_val_empty_n, ZplateHorContDelta_val_empty_n, ZplateVerContStart_val_empty_n, ZplateVerContDelta_val_empty_n, dpDynamicRange_val_empty_n, dpYUVCoef_val_empty_n, motionSpeed_val_empty_n, colorFormat_val_empty_n, height_val5_c14_full_n, width_val10_c16_full_n, motionSpeed_val23_c_full_n, colorFormat_val27_c19_full_n)
    begin
                ap_block_state1 <= ((patternId_val_empty_n = ap_const_logic_0) or (enableInput_val_empty_n = ap_const_logic_0) or (passthruEndY_val_empty_n = ap_const_logic_0) or (passthruEndX_val_empty_n = ap_const_logic_0) or (passthruStartY_val_empty_n = ap_const_logic_0) or (passthruStartX_val_empty_n = ap_const_logic_0) or (width_val_empty_n = ap_const_logic_0) or (height_val_empty_n = ap_const_logic_0) or (ap_const_logic_0 = ZplateVerContStart_val_empty_n) or (ap_const_logic_0 = ZplateHorContDelta_val_empty_n) or (ap_const_logic_0 = ZplateHorContStart_val_empty_n) or (ap_const_logic_0 = ZplateVerContDelta_val_empty_n) or (colorFormat_val27_c19_full_n = ap_const_logic_0) or (motionSpeed_val23_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (width_val10_c16_full_n = ap_const_logic_0) or (height_val5_c14_full_n = ap_const_logic_0) or (colorFormat_val_empty_n = ap_const_logic_0) or (motionSpeed_val_empty_n = ap_const_logic_0) or (dpYUVCoef_val_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (dpDynamicRange_val_empty_n 
    = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln563_fu_1020_p2)
    begin
        if (((icmp_ln563_fu_1020_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_mux_hdata_flag_0_phi_fu_508_p4 <= hdata_flag_0_reg_504;
    ap_phi_mux_rampVal_2_flag_0_phi_fu_520_p4 <= rampVal_2_flag_0_reg_516;
    ap_phi_mux_rampVal_3_flag_0_phi_fu_496_p4 <= rampVal_3_flag_0_reg_492;

    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln563_fu_1020_p2)
    begin
        if (((icmp_ln563_fu_1020_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    barHeight_cast_fu_866_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_856_p4),11));
    barWidthMinSamples_fu_824_p2 <= std_logic_vector(unsigned(p_cast_fu_814_p4) + unsigned(ap_const_lv10_3FF));
    bckgndYUV_din <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_bckgndYUV_din;

    bckgndYUV_write_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_bckgndYUV_write, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bckgndYUV_write <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_bckgndYUV_write;
        else 
            bckgndYUV_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp12_i_fu_1097_p2 <= "0" when (y_3_reg_1424 = ap_const_lv16_0) else "1";
    cmp2_i267_fu_720_p2 <= "1" when (colorFormat_val_dout = ap_const_lv8_0) else "0";
    cmp8_fu_714_p2 <= "0" when (enableInput_val_dout = ap_const_lv8_0) else "1";

    colorFormat_val27_c19_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, colorFormat_val27_c19_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            colorFormat_val27_c19_blk_n <= colorFormat_val27_c19_full_n;
        else 
            colorFormat_val27_c19_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    colorFormat_val27_c19_din <= colorFormat_val_dout;

    colorFormat_val27_c19_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            colorFormat_val27_c19_write <= ap_const_logic_1;
        else 
            colorFormat_val27_c19_write <= ap_const_logic_0;
        end if; 
    end process;


    colorFormat_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, colorFormat_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            colorFormat_val_blk_n <= colorFormat_val_empty_n;
        else 
            colorFormat_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    colorFormat_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            colorFormat_val_read <= ap_const_logic_1;
        else 
            colorFormat_val_read <= ap_const_logic_0;
        end if; 
    end process;


    dpDynamicRange_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, dpDynamicRange_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dpDynamicRange_val_blk_n <= dpDynamicRange_val_empty_n;
        else 
            dpDynamicRange_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dpDynamicRange_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dpDynamicRange_val_read <= ap_const_logic_1;
        else 
            dpDynamicRange_val_read <= ap_const_logic_0;
        end if; 
    end process;


    dpYUVCoef_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, dpYUVCoef_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dpYUVCoef_val_blk_n <= dpYUVCoef_val_empty_n;
        else 
            dpYUVCoef_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dpYUVCoef_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dpYUVCoef_val_read <= ap_const_logic_1;
        else 
            dpYUVCoef_val_read <= ap_const_logic_0;
        end if; 
    end process;

    empty_118_fu_830_p1 <= height_val_dout(14 - 1 downto 0);
    empty_fu_788_p1 <= width_val_dout(14 - 1 downto 0);

    enableInput_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, enableInput_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            enableInput_val_blk_n <= enableInput_val_empty_n;
        else 
            enableInput_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    enableInput_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            enableInput_val_read <= ap_const_logic_1;
        else 
            enableInput_val_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_start <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_ap_start_reg;

    height_val5_c14_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, height_val5_c14_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val5_c14_blk_n <= height_val5_c14_full_n;
        else 
            height_val5_c14_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    height_val5_c14_din <= height_val_dout;

    height_val5_c14_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val5_c14_write <= ap_const_logic_1;
        else 
            height_val5_c14_write <= ap_const_logic_0;
        end if; 
    end process;


    height_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, height_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val_blk_n <= height_val_empty_n;
        else 
            height_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    height_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val_read <= ap_const_logic_1;
        else 
            height_val_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_fu_850_p2 <= "0" when (tmp_fu_840_p4 = ap_const_lv7_0) else "1";
    icmp_ln563_fu_1020_p2 <= "1" when (y_fu_276 = loopHeight_reg_1341) else "0";

    motionSpeed_val23_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, motionSpeed_val23_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            motionSpeed_val23_c_blk_n <= motionSpeed_val23_c_full_n;
        else 
            motionSpeed_val23_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    motionSpeed_val23_c_din <= motionSpeed_val_dout;

    motionSpeed_val23_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            motionSpeed_val23_c_write <= ap_const_logic_1;
        else 
            motionSpeed_val23_c_write <= ap_const_logic_0;
        end if; 
    end process;


    motionSpeed_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, motionSpeed_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            motionSpeed_val_blk_n <= motionSpeed_val_empty_n;
        else 
            motionSpeed_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    motionSpeed_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            motionSpeed_val_read <= ap_const_logic_1;
        else 
            motionSpeed_val_read <= ap_const_logic_0;
        end if; 
    end process;

    outpix_1_fu_734_p2 <= (cmp2_i267_fu_720_p2 xor ap_const_lv1_1);
    outpix_2_fu_740_p3 <= 
        ap_const_lv8_0 when (cmp2_i267_fu_720_p2(0) = '1') else 
        ap_const_lv8_95;
    outpix_3_fu_764_p3 <= 
        ap_const_lv8_FF when (cmp2_i267_fu_720_p2(0) = '1') else 
        ap_const_lv8_6B;
    outpix_fu_726_p3 <= 
        ap_const_lv8_FF when (cmp2_i267_fu_720_p2(0) = '1') else 
        ap_const_lv8_4C;
    p_cast_fu_814_p4 <= add2_i_fu_808_p2(13 downto 4);

    passthruEndX_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, passthruEndX_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            passthruEndX_val_blk_n <= passthruEndX_val_empty_n;
        else 
            passthruEndX_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    passthruEndX_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            passthruEndX_val_read <= ap_const_logic_1;
        else 
            passthruEndX_val_read <= ap_const_logic_0;
        end if; 
    end process;


    passthruEndY_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, passthruEndY_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            passthruEndY_val_blk_n <= passthruEndY_val_empty_n;
        else 
            passthruEndY_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    passthruEndY_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            passthruEndY_val_read <= ap_const_logic_1;
        else 
            passthruEndY_val_read <= ap_const_logic_0;
        end if; 
    end process;


    passthruStartX_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, passthruStartX_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            passthruStartX_val_blk_n <= passthruStartX_val_empty_n;
        else 
            passthruStartX_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    passthruStartX_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            passthruStartX_val_read <= ap_const_logic_1;
        else 
            passthruStartX_val_read <= ap_const_logic_0;
        end if; 
    end process;


    passthruStartY_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, passthruStartY_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            passthruStartY_val_blk_n <= passthruStartY_val_empty_n;
        else 
            passthruStartY_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    passthruStartY_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            passthruStartY_val_read <= ap_const_logic_1;
        else 
            passthruStartY_val_read <= ap_const_logic_0;
        end if; 
    end process;


    patternId_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, patternId_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            patternId_val_blk_n <= patternId_val_empty_n;
        else 
            patternId_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    patternId_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            patternId_val_read <= ap_const_logic_1;
        else 
            patternId_val_read <= ap_const_logic_0;
        end if; 
    end process;

    pix_16_fu_780_p3 <= 
        ap_const_lv8_FF when (cmp2_i267_fu_720_p2(0) = '1') else 
        ap_const_lv8_80;
    pix_fu_772_p3 <= 
        ap_const_lv8_0 when (cmp2_i267_fu_720_p2(0) = '1') else 
        ap_const_lv8_80;
    rev_fu_1091_p2 <= (ult_reg_1451 xor ap_const_lv1_1);
    select_ln552_1_cast_cast_fu_756_p3 <= 
        ap_const_lv3_0 when (cmp2_i267_fu_720_p2(0) = '1') else 
        ap_const_lv3_5;
    select_ln552_fu_748_p3 <= 
        ap_const_lv5_0 when (cmp2_i267_fu_720_p2(0) = '1') else 
        ap_const_lv5_15;

    srcYUV_read_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_srcYUV_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            srcYUV_read <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_528_srcYUV_read;
        else 
            srcYUV_read <= ap_const_logic_0;
        end if; 
    end process;

    sub_i_i_i_fu_870_p2 <= std_logic_vector(unsigned(barHeight_cast_fu_866_p1) + unsigned(ap_const_lv11_7FF));
    tmp_1_fu_856_p4 <= add5_i_fu_834_p2(13 downto 4);
    tmp_fu_840_p4 <= colorFormat_val_dout(7 downto 1);
    trunc_ln563_fu_1087_p1 <= y_3_reg_1424(8 - 1 downto 0);
    ult_fu_1040_p2 <= "1" when (unsigned(y_fu_276) < unsigned(passthruEndY_val_read_reg_1315)) else "0";

    width_val10_c16_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_val10_c16_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val10_c16_blk_n <= width_val10_c16_full_n;
        else 
            width_val10_c16_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    width_val10_c16_din <= width_val_dout;

    width_val10_c16_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val10_c16_write <= ap_const_logic_1;
        else 
            width_val10_c16_write <= ap_const_logic_0;
        end if; 
    end process;


    width_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val_blk_n <= width_val_empty_n;
        else 
            width_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    width_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val_read <= ap_const_logic_1;
        else 
            width_val_read <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln1257_fu_888_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rampVal),16));
    zext_ln1412_fu_904_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vBarSel),8));
    zext_ln1545_fu_912_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_0),8));
    zext_ln1664_fu_928_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_3_0),8));
    zext_ln1775_fu_940_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vBarSel_1),8));
    zext_ln563_fu_948_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_5_0),8));
end behav;
