// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_tpgBackground (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        srcYUV_dout,
        srcYUV_num_data_valid,
        srcYUV_fifo_cap,
        srcYUV_empty_n,
        srcYUV_read,
        height,
        width,
        passthruStartX,
        passthruStartY,
        passthruEndX,
        passthruEndY,
        enableInput,
        bckgndId,
        ZplateHorContStart,
        ZplateHorContDelta,
        ZplateVerContStart,
        ZplateVerContDelta,
        dpDynamicRange,
        dpYUVCoef,
        motionSpeed,
        colorFormat,
        bckgndYUV_din,
        bckgndYUV_num_data_valid,
        bckgndYUV_fifo_cap,
        bckgndYUV_full_n,
        bckgndYUV_write,
        s
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [23:0] srcYUV_dout;
input  [5:0] srcYUV_num_data_valid;
input  [5:0] srcYUV_fifo_cap;
input   srcYUV_empty_n;
output   srcYUV_read;
input  [15:0] height;
input  [15:0] width;
input  [15:0] passthruStartX;
input  [15:0] passthruStartY;
input  [15:0] passthruEndX;
input  [15:0] passthruEndY;
input  [7:0] enableInput;
input  [7:0] bckgndId;
input  [15:0] ZplateHorContStart;
input  [15:0] ZplateHorContDelta;
input  [15:0] ZplateVerContStart;
input  [15:0] ZplateVerContDelta;
input  [7:0] dpDynamicRange;
input  [7:0] dpYUVCoef;
input  [7:0] motionSpeed;
input  [7:0] colorFormat;
output  [23:0] bckgndYUV_din;
input  [4:0] bckgndYUV_num_data_valid;
input  [4:0] bckgndYUV_fifo_cap;
input   bckgndYUV_full_n;
output   bckgndYUV_write;
input  [31:0] s;

reg ap_done;
reg ap_idle;
reg start_write;
reg srcYUV_read;
reg bckgndYUV_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] rampStart;
reg   [15:0] rampVal_1;
reg   [7:0] rampVal;
reg   [7:0] hBarSel_2;
reg   [15:0] zonePlateVAddr;
reg   [2:0] vBarSel;
reg   [2:0] hBarSel;
reg   [15:0] hdata;
reg   [7:0] vBarSel_2;
reg   [2:0] hBarSel_3;
reg   [15:0] rampVal_2;
reg   [0:0] vBarSel_1;
reg   [2:0] hBarSel_1;
wire   [0:0] cmp8_fu_696_p2;
reg   [0:0] cmp8_reg_1397;
wire   [0:0] cmp2_i381_fu_702_p2;
reg   [0:0] cmp2_i381_reg_1447;
wire   [7:0] outpix_val_V_fu_708_p3;
reg   [7:0] outpix_val_V_reg_1452;
wire   [0:0] outpix_val_V_1_fu_716_p2;
reg   [0:0] outpix_val_V_1_reg_1457;
wire   [7:0] outpix_val_V_2_fu_722_p3;
reg   [7:0] outpix_val_V_2_reg_1462;
wire   [4:0] select_ln507_fu_730_p3;
reg   [4:0] select_ln507_reg_1467;
wire   [2:0] select_ln507_1_cast_cast_fu_738_p3;
reg   [2:0] select_ln507_1_cast_cast_reg_1472;
wire   [7:0] outpix_val_V_3_fu_746_p3;
reg   [7:0] outpix_val_V_3_reg_1477;
wire   [7:0] pix_val_V_fu_754_p3;
reg   [7:0] pix_val_V_reg_1482;
wire   [7:0] pix_val_V_14_fu_762_p3;
reg   [7:0] pix_val_V_14_reg_1487;
wire   [9:0] barWidthMinSamples_fu_794_p2;
reg   [9:0] barWidthMinSamples_reg_1492;
wire   [0:0] icmp_fu_824_p2;
reg   [0:0] icmp_reg_1497;
reg   [10:0] barWidth_reg_1502;
wire   [10:0] sub_i_i_i_fu_860_p2;
reg   [10:0] sub_i_i_i_reg_1508;
wire   [16:0] sub40_i_fu_866_p2;
reg   [16:0] sub40_i_reg_1513;
wire   [16:0] add_ln1404_fu_872_p2;
reg   [16:0] add_ln1404_reg_1518;
wire   [0:0] cmp59_i_fu_878_p2;
reg   [0:0] cmp59_i_reg_1523;
wire   [0:0] cmp126_i_fu_884_p2;
reg   [0:0] cmp126_i_reg_1528;
wire   [0:0] cmp141_i_fu_890_p2;
reg   [0:0] cmp141_i_reg_1533;
reg   [7:0] rampStart_load_reg_1538;
wire   [7:0] select_ln214_fu_972_p3;
reg   [7:0] select_ln214_reg_1545;
wire   [15:0] shl_ln_fu_980_p3;
reg   [15:0] shl_ln_reg_1550;
wire   [0:0] icmp_ln1217_fu_988_p2;
reg   [0:0] icmp_ln1217_reg_1555;
reg   [15:0] y_3_reg_1560;
wire    ap_CS_fsm_state2;
wire   [7:0] trunc_ln518_fu_1062_p1;
reg   [7:0] trunc_ln518_reg_1568;
reg   [7:0] outpix_val_V_6_load_reg_1576;
wire   [0:0] icmp_ln518_fu_1066_p2;
reg   [7:0] outpix_val_V_7_load_reg_1581;
reg   [7:0] outpix_val_V_8_load_reg_1586;
wire   [0:0] ult_fu_1086_p2;
reg   [0:0] ult_reg_1591;
wire   [0:0] icmp_ln691_fu_1091_p2;
reg   [0:0] icmp_ln691_reg_1596;
wire   [0:0] icmp_ln1404_1_fu_1100_p2;
reg   [0:0] icmp_ln1404_1_reg_1601;
wire   [0:0] rev357_fu_1148_p2;
reg   [0:0] rev357_reg_1606;
wire    ap_CS_fsm_state3;
wire   [0:0] cmp12_i_fu_1154_p2;
reg   [0:0] cmp12_i_reg_1611;
wire   [0:0] xor_ln691_fu_1169_p2;
reg   [0:0] xor_ln691_reg_1616;
wire   [0:0] icmp_ln1404_fu_1175_p2;
reg   [0:0] icmp_ln1404_reg_1621;
wire   [7:0] add_ln1488_fu_1181_p2;
reg   [7:0] add_ln1488_reg_1626;
wire   [0:0] or_ln1592_fu_1198_p2;
reg   [0:0] or_ln1592_reg_1631;
wire   [0:0] or_ln1592_1_fu_1211_p2;
reg   [0:0] or_ln1592_1_reg_1636;
wire   [0:0] or_ln1592_2_fu_1218_p2;
reg   [0:0] or_ln1592_2_reg_1641;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_done;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_idle;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_ready;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_srcYUV_read;
wire   [23:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_bckgndYUV_din;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_bckgndYUV_write;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_4_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_4_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_3_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_5_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_5_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_11_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_11_out_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_10_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_10_out_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_9_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_9_out_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_2_0_0_0133363_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_2_0_0_0133363_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_1_0_0_0131361_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_1_0_0_0131361_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_0_0_0_0129359_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_0_0_0_0129359_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_2_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_1_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_1_ap_vld;
wire   [0:0] ap_phi_mux_rampVal_3_flag_0_phi_fu_464_p4;
reg   [0:0] rampVal_3_flag_0_reg_460;
reg    ap_block_state1;
wire    ap_CS_fsm_state5;
wire   [0:0] ap_phi_mux_hdata_flag_0_phi_fu_476_p4;
reg   [0:0] hdata_flag_0_reg_472;
wire   [0:0] ap_phi_mux_rampVal_2_flag_0_phi_fu_488_p4;
reg   [0:0] rampVal_2_flag_0_reg_484;
reg    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start_reg;
wire    ap_CS_fsm_state4;
reg   [15:0] rampVal_3_new_0_fu_348;
reg   [15:0] rampVal_3_loc_0_fu_344;
reg   [15:0] rampVal_loc_0_fu_340;
reg   [7:0] hBarSel_4_loc_0_fu_336;
reg   [15:0] zonePlateVAddr_loc_0_fu_332;
reg   [7:0] vBarSel_loc_0_fu_328;
reg   [7:0] hBarSel_loc_0_fu_324;
reg   [15:0] hdata_new_0_fu_320;
reg   [15:0] hdata_loc_0_fu_316;
reg   [7:0] vBarSel_2_loc_0_fu_312;
reg   [7:0] hBarSel_3_loc_0_fu_308;
reg   [15:0] rampVal_2_new_0_fu_304;
reg   [15:0] rampVal_2_loc_0_fu_300;
reg   [7:0] vBarSel_3_loc_0_fu_296;
reg   [7:0] hBarSel_5_loc_0_fu_292;
reg   [7:0] outpix_val_V_8_fu_288;
reg   [7:0] outpix_val_V_7_fu_284;
reg   [7:0] outpix_val_V_6_fu_280;
reg   [7:0] p_0_2_0_0_0133364_lcssa373_fu_272;
reg   [7:0] p_0_1_0_0_0131362_lcssa370_fu_268;
reg   [7:0] p_0_0_0_0_0129360_lcssa367_fu_264;
wire   [7:0] add_ln705_fu_1110_p2;
reg   [15:0] y_fu_276;
wire   [15:0] add_ln518_fu_1071_p2;
wire   [7:0] zext_ln518_fu_968_p1;
wire   [7:0] zext_ln1730_fu_960_p1;
wire   [7:0] zext_ln1610_fu_948_p1;
wire   [7:0] zext_ln1493_fu_932_p1;
wire   [7:0] zext_ln1367_fu_924_p1;
wire   [15:0] zext_ln1212_fu_908_p1;
wire   [13:0] empty_fu_774_p1;
wire   [13:0] add2_i_fu_778_p2;
wire   [9:0] p_cast_fu_784_p4;
wire   [13:0] empty_81_fu_804_p1;
wire   [6:0] tmp_23_fu_814_p4;
wire   [13:0] add_i_fu_830_p2;
wire   [13:0] add5_i_fu_808_p2;
wire   [9:0] tmp_fu_846_p4;
wire   [10:0] barHeight_cast_cast_fu_856_p1;
wire   [16:0] loopWidth_cast15_fu_770_p1;
wire   [16:0] loopHeight_cast16_fu_800_p1;
wire   [16:0] zext_ln1404_fu_1096_p1;
wire   [1:0] Sel_fu_1160_p4;
wire   [0:0] icmp_ln1592_fu_1186_p2;
wire   [0:0] icmp_ln1592_1_fu_1192_p2;
wire   [0:0] icmp_ln1592_2_fu_1205_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 rampStart = 8'd0;
#0 rampVal_1 = 16'd0;
#0 rampVal = 8'd0;
#0 hBarSel_2 = 8'd0;
#0 zonePlateVAddr = 16'd0;
#0 vBarSel = 3'd0;
#0 hBarSel = 3'd0;
#0 hdata = 16'd0;
#0 vBarSel_2 = 8'd0;
#0 hBarSel_3 = 3'd0;
#0 rampVal_2 = 16'd0;
#0 vBarSel_1 = 1'd0;
#0 hBarSel_1 = 3'd0;
#0 grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start_reg = 1'b0;
end

design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2 grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start),
    .ap_done(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_done),
    .ap_idle(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_idle),
    .ap_ready(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_ready),
    .srcYUV_dout(srcYUV_dout),
    .srcYUV_num_data_valid(srcYUV_num_data_valid),
    .srcYUV_fifo_cap(5'd0),
    .srcYUV_empty_n(srcYUV_empty_n),
    .srcYUV_read(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_srcYUV_read),
    .bckgndYUV_din(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_bckgndYUV_din),
    .bckgndYUV_num_data_valid(5'd0),
    .bckgndYUV_fifo_cap(5'd0),
    .bckgndYUV_full_n(bckgndYUV_full_n),
    .bckgndYUV_write(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_bckgndYUV_write),
    .rampVal_3_flag_0(rampVal_3_flag_0_reg_460),
    .hdata_flag_0(hdata_flag_0_reg_472),
    .rampVal_2_flag_0(rampVal_2_flag_0_reg_484),
    .outpix_val_V_8(outpix_val_V_8_load_reg_1586),
    .outpix_val_V_7(outpix_val_V_7_load_reg_1581),
    .outpix_val_V_6(outpix_val_V_6_load_reg_1576),
    .loopWidth(width),
    .pix_val_V_17(pix_val_V_14_reg_1487),
    .pix_val_V_16(pix_val_V_reg_1482),
    .outpix_val_V_3(outpix_val_V_3_reg_1477),
    .select_ln507(select_ln507_reg_1467),
    .sext_ln507(outpix_val_V_1_reg_1457),
    .outpix_val_V_18(select_ln214_reg_1545),
    .select_ln507_1_cast_cast(select_ln507_1_cast_cast_reg_1472),
    .outpix_val_V_2(outpix_val_V_2_reg_1462),
    .outpix_val_V(outpix_val_V_reg_1452),
    .rampStart_1(rampStart_load_reg_1538),
    .cmp8(cmp8_reg_1397),
    .bckgndId_load(bckgndId),
    .Zplate_Hor_Control_Start(ZplateHorContStart),
    .cmp2_i381(cmp2_i381_reg_1447),
    .zext_ln1032(rampStart_load_reg_1538),
    .y(y_3_reg_1560),
    .colorFormatLocal(colorFormat),
    .cmp141_i(cmp141_i_reg_1533),
    .icmp_ln1217(icmp_ln1217_reg_1555),
    .barWidth_cast(barWidth_reg_1502),
    .barWidth(barWidth_reg_1502),
    .shl_ln(shl_ln_reg_1550),
    .Zplate_Hor_Control_Delta(ZplateHorContDelta),
    .Zplate_Ver_Control_Start(ZplateVerContStart),
    .cmp12_i(cmp12_i_reg_1611),
    .Zplate_Ver_Control_Delta(ZplateVerContDelta),
    .sub_i_i_i(sub_i_i_i_reg_1508),
    .barWidthMinSamples(barWidthMinSamples_reg_1492),
    .icmp_ln1404_1(icmp_ln1404_1_reg_1601),
    .icmp_ln1404(icmp_ln1404_reg_1621),
    .sub40_i(sub40_i_reg_1513),
    .add_ln1488(add_ln1488_reg_1626),
    .cmp35_i586(icmp_reg_1497),
    .or_ln1592(or_ln1592_reg_1631),
    .or_ln1592_1(or_ln1592_1_reg_1636),
    .or_ln1592_2(or_ln1592_2_reg_1641),
    .cmp59_i(cmp59_i_reg_1523),
    .cmp126_i(cmp126_i_reg_1528),
    .passthruStartX_load(passthruStartX),
    .passthruEndX_load(passthruEndX),
    .icmp_ln691(xor_ln691_reg_1616),
    .cmp68_not(rev357_reg_1606),
    .rampVal_3_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_flag_1_out),
    .rampVal_3_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_flag_1_out_ap_vld),
    .rampVal_3_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_new_1_out),
    .rampVal_3_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_new_1_out_ap_vld),
    .rampVal_3_loc_1_out_i(rampVal_3_loc_0_fu_344),
    .rampVal_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_loc_1_out_o),
    .rampVal_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_loc_1_out_o_ap_vld),
    .rampVal_loc_1_out_i(rampVal_loc_0_fu_340),
    .rampVal_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_loc_1_out_o),
    .rampVal_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_loc_1_out_o_ap_vld),
    .hBarSel_4_loc_1_out_i(hBarSel_4_loc_0_fu_336),
    .hBarSel_4_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_4_loc_1_out_o),
    .hBarSel_4_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_4_loc_1_out_o_ap_vld),
    .zonePlateVAddr_loc_1_out_i(zonePlateVAddr_loc_0_fu_332),
    .zonePlateVAddr_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_loc_1_out_o),
    .zonePlateVAddr_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_loc_1_out_o_ap_vld),
    .vBarSel_loc_1_out_i(vBarSel_loc_0_fu_328),
    .vBarSel_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_loc_1_out_o),
    .vBarSel_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_loc_1_out_o_ap_vld),
    .hBarSel_loc_1_out_i(hBarSel_loc_0_fu_324),
    .hBarSel_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_loc_1_out_o),
    .hBarSel_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_loc_1_out_o_ap_vld),
    .hdata_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_flag_1_out),
    .hdata_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_flag_1_out_ap_vld),
    .hdata_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_new_1_out),
    .hdata_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_new_1_out_ap_vld),
    .hdata_loc_1_out_i(hdata_loc_0_fu_316),
    .hdata_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_loc_1_out_o),
    .hdata_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_loc_1_out_o_ap_vld),
    .vBarSel_2_loc_1_out_i(vBarSel_2_loc_0_fu_312),
    .vBarSel_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_loc_1_out_o),
    .vBarSel_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_loc_1_out_o_ap_vld),
    .hBarSel_3_loc_1_out_i(hBarSel_3_loc_0_fu_308),
    .hBarSel_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_loc_1_out_o),
    .hBarSel_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_loc_1_out_o_ap_vld),
    .rampVal_2_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_flag_1_out),
    .rampVal_2_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_flag_1_out_ap_vld),
    .rampVal_2_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_new_1_out),
    .rampVal_2_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_new_1_out_ap_vld),
    .rampVal_2_loc_1_out_i(rampVal_2_loc_0_fu_300),
    .rampVal_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_loc_1_out_o),
    .rampVal_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_loc_1_out_o_ap_vld),
    .vBarSel_3_loc_1_out_i(vBarSel_3_loc_0_fu_296),
    .vBarSel_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_3_loc_1_out_o),
    .vBarSel_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_3_loc_1_out_o_ap_vld),
    .hBarSel_5_loc_1_out_i(hBarSel_5_loc_0_fu_292),
    .hBarSel_5_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_5_loc_1_out_o),
    .hBarSel_5_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_5_loc_1_out_o_ap_vld),
    .outpix_val_V_11_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_11_out),
    .outpix_val_V_11_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_11_out_ap_vld),
    .outpix_val_V_10_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_10_out),
    .outpix_val_V_10_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_10_out_ap_vld),
    .outpix_val_V_9_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_9_out),
    .outpix_val_V_9_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_9_out_ap_vld),
    .p_0_2_0_0_0133363_out_i(p_0_2_0_0_0133364_lcssa373_fu_272),
    .p_0_2_0_0_0133363_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_2_0_0_0133363_out_o),
    .p_0_2_0_0_0133363_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_2_0_0_0133363_out_o_ap_vld),
    .p_0_1_0_0_0131361_out_i(p_0_1_0_0_0131362_lcssa370_fu_268),
    .p_0_1_0_0_0131361_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_1_0_0_0131361_out_o),
    .p_0_1_0_0_0131361_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_1_0_0_0131361_out_o_ap_vld),
    .p_0_0_0_0_0129359_out_i(p_0_0_0_0_0129360_lcssa367_fu_264),
    .p_0_0_0_0_0129359_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_0_0_0_0129359_out_o),
    .p_0_0_0_0_0129359_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_0_0_0_0129359_out_o_ap_vld),
    .rampVal(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal),
    .rampVal_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_ap_vld),
    .hBarSel_2(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_2),
    .hBarSel_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_2_ap_vld),
    .s(s),
    .zonePlateVAddr(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr),
    .zonePlateVAddr_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_ap_vld),
    .hBarSel(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel),
    .hBarSel_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_ap_vld),
    .vBarSel(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel),
    .vBarSel_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_ap_vld),
    .hBarSel_3(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3),
    .hBarSel_3_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_ap_vld),
    .vBarSel_2(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2),
    .vBarSel_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_ap_vld),
    .hBarSel_1(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_1),
    .hBarSel_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_1_ap_vld),
    .vBarSel_1(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_1),
    .vBarSel_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_1_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_1066_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start_reg <= 1'b1;
        end else if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_ready == 1'b1)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_3_loc_0_fu_308 <= zext_ln1610_fu_948_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_3_loc_0_fu_308 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_4_loc_0_fu_336 <= hBarSel_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_4_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_4_loc_0_fu_336 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_4_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_5_loc_0_fu_292 <= zext_ln518_fu_968_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_5_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_5_loc_0_fu_292 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_5_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_loc_0_fu_324 <= zext_ln1493_fu_932_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_loc_0_fu_324 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        hdata_flag_0_reg_472 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_flag_1_out;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hdata_flag_0_reg_472 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hdata_loc_0_fu_316 <= hdata;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hdata_loc_0_fu_316 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        rampVal_2_flag_0_reg_484 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_flag_1_out;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_2_flag_0_reg_484 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_2_loc_0_fu_300 <= rampVal_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_2_loc_0_fu_300 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        rampVal_3_flag_0_reg_460 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_flag_1_out;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_3_flag_0_reg_460 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_3_loc_0_fu_344 <= rampVal_1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_3_loc_0_fu_344 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_loc_0_fu_340 <= zext_ln1212_fu_908_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_loc_0_fu_340 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_2_loc_0_fu_312 <= vBarSel_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_2_loc_0_fu_312 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_3_loc_0_fu_296 <= zext_ln1730_fu_960_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_3_loc_0_fu_296 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_loc_0_fu_328 <= zext_ln1367_fu_924_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_loc_0_fu_328 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_276 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_1066_p2 == 1'd0))) begin
        y_fu_276 <= add_ln518_fu_1071_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        zonePlateVAddr_loc_0_fu_332 <= zonePlateVAddr;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        zonePlateVAddr_loc_0_fu_332 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln1404_reg_1518 <= add_ln1404_fu_872_p2;
        barWidthMinSamples_reg_1492 <= barWidthMinSamples_fu_794_p2;
        barWidth_reg_1502 <= {{add_i_fu_830_p2[13:3]}};
        cmp126_i_reg_1528 <= cmp126_i_fu_884_p2;
        cmp141_i_reg_1533 <= cmp141_i_fu_890_p2;
        cmp2_i381_reg_1447 <= cmp2_i381_fu_702_p2;
        cmp59_i_reg_1523 <= cmp59_i_fu_878_p2;
        cmp8_reg_1397 <= cmp8_fu_696_p2;
        icmp_ln1217_reg_1555 <= icmp_ln1217_fu_988_p2;
        icmp_reg_1497 <= icmp_fu_824_p2;
        outpix_val_V_1_reg_1457 <= outpix_val_V_1_fu_716_p2;
        outpix_val_V_2_reg_1462[0] <= outpix_val_V_2_fu_722_p3[0];
outpix_val_V_2_reg_1462[2] <= outpix_val_V_2_fu_722_p3[2];
outpix_val_V_2_reg_1462[4] <= outpix_val_V_2_fu_722_p3[4];
outpix_val_V_2_reg_1462[7] <= outpix_val_V_2_fu_722_p3[7];
        outpix_val_V_3_reg_1477[2] <= outpix_val_V_3_fu_746_p3[2];
outpix_val_V_3_reg_1477[4] <= outpix_val_V_3_fu_746_p3[4];
outpix_val_V_3_reg_1477[7] <= outpix_val_V_3_fu_746_p3[7];
        outpix_val_V_reg_1452[1 : 0] <= outpix_val_V_fu_708_p3[1 : 0];
outpix_val_V_reg_1452[5 : 4] <= outpix_val_V_fu_708_p3[5 : 4];
outpix_val_V_reg_1452[7] <= outpix_val_V_fu_708_p3[7];
        pix_val_V_14_reg_1487[6 : 0] <= pix_val_V_14_fu_762_p3[6 : 0];
        pix_val_V_reg_1482[7] <= pix_val_V_fu_754_p3[7];
        rampStart_load_reg_1538 <= rampStart;
        select_ln214_reg_1545 <= select_ln214_fu_972_p3;
        select_ln507_1_cast_cast_reg_1472[0] <= select_ln507_1_cast_cast_fu_738_p3[0];
select_ln507_1_cast_cast_reg_1472[2] <= select_ln507_1_cast_cast_fu_738_p3[2];
        select_ln507_reg_1467[0] <= select_ln507_fu_730_p3[0];
select_ln507_reg_1467[2] <= select_ln507_fu_730_p3[2];
select_ln507_reg_1467[4] <= select_ln507_fu_730_p3[4];
        shl_ln_reg_1550[15 : 8] <= shl_ln_fu_980_p3[15 : 8];
        sub40_i_reg_1513 <= sub40_i_fu_866_p2;
        sub_i_i_i_reg_1508 <= sub_i_i_i_fu_860_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln1488_reg_1626 <= add_ln1488_fu_1181_p2;
        cmp12_i_reg_1611 <= cmp12_i_fu_1154_p2;
        icmp_ln1404_reg_1621 <= icmp_ln1404_fu_1175_p2;
        or_ln1592_1_reg_1636 <= or_ln1592_1_fu_1211_p2;
        or_ln1592_2_reg_1641 <= or_ln1592_2_fu_1218_p2;
        or_ln1592_reg_1631 <= or_ln1592_fu_1198_p2;
        rev357_reg_1606 <= rev357_fu_1148_p2;
        xor_ln691_reg_1616 <= xor_ln691_fu_1169_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_3 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hBarSel_3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_hdata_flag_0_phi_fu_476_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_1066_p2 == 1'd1))) begin
        hdata <= hdata_new_0_fu_320;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hdata_new_0_fu_320 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_hdata_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_1066_p2 == 1'd0))) begin
        icmp_ln1404_1_reg_1601 <= icmp_ln1404_1_fu_1100_p2;
        icmp_ln691_reg_1596 <= icmp_ln691_fu_1091_p2;
        outpix_val_V_6_load_reg_1576 <= outpix_val_V_6_fu_280;
        outpix_val_V_7_load_reg_1581 <= outpix_val_V_7_fu_284;
        outpix_val_V_8_load_reg_1586 <= outpix_val_V_8_fu_288;
        ult_reg_1591 <= ult_fu_1086_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_9_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_val_V_6_fu_280 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_9_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_10_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_val_V_7_fu_284 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_10_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_11_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_val_V_8_fu_288 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_outpix_val_V_11_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_0_0_0_0129359_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0_0_0129360_lcssa367_fu_264 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_0_0_0_0129359_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_1_0_0_0131361_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_1_0_0_0131362_lcssa370_fu_268 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_1_0_0_0131361_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_2_0_0_0133363_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_2_0_0_0133364_lcssa373_fu_272 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_p_0_2_0_0_0133363_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_1066_p2 == 1'd1))) begin
        rampStart <= add_ln705_fu_1110_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_rampVal_3_flag_0_phi_fu_464_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_1066_p2 == 1'd1))) begin
        rampVal_1 <= rampVal_3_new_0_fu_348;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_rampVal_2_flag_0_phi_fu_488_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_1066_p2 == 1'd1))) begin
        rampVal_2 <= rampVal_2_new_0_fu_304;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_2_new_0_fu_304 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_2_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_3_new_0_fu_348 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_rampVal_3_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln518_reg_1568 <= trunc_ln518_fu_1062_p1;
        y_3_reg_1560 <= y_fu_276;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_vBarSel_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_zonePlateVAddr;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_1066_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bckgndYUV_write = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_bckgndYUV_write;
    end else begin
        bckgndYUV_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_1066_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        srcYUV_read = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_srcYUV_read;
    end else begin
        srcYUV_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_1066_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Sel_fu_1160_p4 = {{y_3_reg_1560[7:6]}};

assign add2_i_fu_778_p2 = (empty_fu_774_p1 + 14'd15);

assign add5_i_fu_808_p2 = (empty_81_fu_804_p1 + 14'd15);

assign add_i_fu_830_p2 = (empty_fu_774_p1 + 14'd7);

assign add_ln1404_fu_872_p2 = ($signed(loopHeight_cast16_fu_800_p1) + $signed(17'd131071));

assign add_ln1488_fu_1181_p2 = (rampStart_load_reg_1538 + trunc_ln518_reg_1568);

assign add_ln518_fu_1071_p2 = (y_fu_276 + 16'd1);

assign add_ln705_fu_1110_p2 = (motionSpeed + rampStart);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_phi_mux_hdata_flag_0_phi_fu_476_p4 = hdata_flag_0_reg_472;

assign ap_phi_mux_rampVal_2_flag_0_phi_fu_488_p4 = rampVal_2_flag_0_reg_484;

assign ap_phi_mux_rampVal_3_flag_0_phi_fu_464_p4 = rampVal_3_flag_0_reg_460;

assign ap_ready = internal_ap_ready;

assign barHeight_cast_cast_fu_856_p1 = tmp_fu_846_p4;

assign barWidthMinSamples_fu_794_p2 = ($signed(p_cast_fu_784_p4) + $signed(10'd1023));

assign bckgndYUV_din = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_bckgndYUV_din;

assign cmp126_i_fu_884_p2 = ((dpYUVCoef == 8'd0) ? 1'b1 : 1'b0);

assign cmp12_i_fu_1154_p2 = ((y_3_reg_1560 != 16'd0) ? 1'b1 : 1'b0);

assign cmp141_i_fu_890_p2 = ((colorFormat != 8'd1) ? 1'b1 : 1'b0);

assign cmp2_i381_fu_702_p2 = ((colorFormat == 8'd0) ? 1'b1 : 1'b0);

assign cmp59_i_fu_878_p2 = ((dpDynamicRange == 8'd0) ? 1'b1 : 1'b0);

assign cmp8_fu_696_p2 = ((enableInput != 8'd0) ? 1'b1 : 1'b0);

assign empty_81_fu_804_p1 = height[13:0];

assign empty_fu_774_p1 = width[13:0];

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_496_ap_start_reg;

assign icmp_fu_824_p2 = ((tmp_23_fu_814_p4 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln1217_fu_988_p2 = ((colorFormat != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln1404_1_fu_1100_p2 = ((add_ln1404_reg_1518 == zext_ln1404_fu_1096_p1) ? 1'b1 : 1'b0);

assign icmp_ln1404_fu_1175_p2 = ((y_3_reg_1560 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1592_1_fu_1192_p2 = ((Sel_fu_1160_p4 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln1592_2_fu_1205_p2 = ((Sel_fu_1160_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1592_fu_1186_p2 = ((Sel_fu_1160_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln518_fu_1066_p2 = ((y_fu_276 == height) ? 1'b1 : 1'b0);

assign icmp_ln691_fu_1091_p2 = ((y_fu_276 < passthruStartY) ? 1'b1 : 1'b0);

assign loopHeight_cast16_fu_800_p1 = height;

assign loopWidth_cast15_fu_770_p1 = width;

assign or_ln1592_1_fu_1211_p2 = (icmp_ln1592_2_fu_1205_p2 | icmp_ln1592_1_fu_1192_p2);

assign or_ln1592_2_fu_1218_p2 = (icmp_ln1592_fu_1186_p2 | icmp_ln1592_2_fu_1205_p2);

assign or_ln1592_fu_1198_p2 = (icmp_ln1592_fu_1186_p2 | icmp_ln1592_1_fu_1192_p2);

assign outpix_val_V_1_fu_716_p2 = (cmp2_i381_fu_702_p2 ^ 1'd1);

assign outpix_val_V_2_fu_722_p3 = ((cmp2_i381_fu_702_p2[0:0] == 1'b1) ? 8'd0 : 8'd149);

assign outpix_val_V_3_fu_746_p3 = ((cmp2_i381_fu_702_p2[0:0] == 1'b1) ? 8'd255 : 8'd107);

assign outpix_val_V_fu_708_p3 = ((cmp2_i381_fu_702_p2[0:0] == 1'b1) ? 8'd255 : 8'd76);

assign p_cast_fu_784_p4 = {{add2_i_fu_778_p2[13:4]}};

assign pix_val_V_14_fu_762_p3 = ((cmp2_i381_fu_702_p2[0:0] == 1'b1) ? 8'd255 : 8'd128);

assign pix_val_V_fu_754_p3 = ((cmp2_i381_fu_702_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign rev357_fu_1148_p2 = (ult_reg_1591 ^ 1'd1);

assign select_ln214_fu_972_p3 = ((cmp2_i381_fu_702_p2[0:0] == 1'b1) ? rampStart : 8'd128);

assign select_ln507_1_cast_cast_fu_738_p3 = ((cmp2_i381_fu_702_p2[0:0] == 1'b1) ? 3'd0 : 3'd5);

assign select_ln507_fu_730_p3 = ((cmp2_i381_fu_702_p2[0:0] == 1'b1) ? 5'd0 : 5'd21);

assign shl_ln_fu_980_p3 = {{rampStart}, {8'd0}};

assign start_out = real_start;

assign sub40_i_fu_866_p2 = ($signed(loopWidth_cast15_fu_770_p1) + $signed(17'd131071));

assign sub_i_i_i_fu_860_p2 = ($signed(barHeight_cast_cast_fu_856_p1) + $signed(11'd2047));

assign tmp_23_fu_814_p4 = {{colorFormat[7:1]}};

assign tmp_fu_846_p4 = {{add5_i_fu_808_p2[13:4]}};

assign trunc_ln518_fu_1062_p1 = y_fu_276[7:0];

assign ult_fu_1086_p2 = ((y_fu_276 < passthruEndY) ? 1'b1 : 1'b0);

assign xor_ln691_fu_1169_p2 = (icmp_ln691_reg_1596 ^ 1'd1);

assign zext_ln1212_fu_908_p1 = rampVal;

assign zext_ln1367_fu_924_p1 = vBarSel;

assign zext_ln1404_fu_1096_p1 = y_fu_276;

assign zext_ln1493_fu_932_p1 = hBarSel;

assign zext_ln1610_fu_948_p1 = hBarSel_3;

assign zext_ln1730_fu_960_p1 = vBarSel_1;

assign zext_ln518_fu_968_p1 = hBarSel_1;

always @ (posedge ap_clk) begin
    outpix_val_V_reg_1452[3:2] <= 2'b11;
    outpix_val_V_reg_1452[6] <= 1'b1;
    outpix_val_V_2_reg_1462[1] <= 1'b0;
    outpix_val_V_2_reg_1462[3:3] <= 1'b0;
    outpix_val_V_2_reg_1462[6:5] <= 2'b00;
    select_ln507_reg_1467[1] <= 1'b0;
    select_ln507_reg_1467[3] <= 1'b0;
    select_ln507_1_cast_cast_reg_1472[1] <= 1'b0;
    outpix_val_V_3_reg_1477[1:0] <= 2'b11;
    outpix_val_V_3_reg_1477[3:3] <= 1'b1;
    outpix_val_V_3_reg_1477[6:5] <= 2'b11;
    pix_val_V_reg_1482[6:0] <= 7'b0000000;
    pix_val_V_14_reg_1487[7] <= 1'b1;
    shl_ln_reg_1550[7:0] <= 8'b00000000;
end

endmodule //design_1_v_tpg_0_0_tpgBackground
